//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AnyPartyCommunicationDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="AnyPartyCommunicationDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AnyPartyPhoneNumberIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="AnyPartyEmailAddressIdentifier" type="{}genericStringType0_70" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnyPartyCommunicationDetailsType", propOrder = {
		"anyPartyPhoneNumberIdentifier", "anyPartyEmailAddressIdentifier" })
public class AnyPartyCommunicationDetailsType {

	@XmlElement(name = "AnyPartyPhoneNumberIdentifier")
	protected String anyPartyPhoneNumberIdentifier;
	@XmlElement(name = "AnyPartyEmailAddressIdentifier")
	protected String anyPartyEmailAddressIdentifier;

	/**
	 * Gets the value of the anyPartyPhoneNumberIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAnyPartyPhoneNumberIdentifier() {
		return anyPartyPhoneNumberIdentifier;
	}

	/**
	 * Sets the value of the anyPartyPhoneNumberIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAnyPartyPhoneNumberIdentifier(String value) {
		this.anyPartyPhoneNumberIdentifier = value;
	}

	/**
	 * Gets the value of the anyPartyEmailAddressIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAnyPartyEmailAddressIdentifier() {
		return anyPartyEmailAddressIdentifier;
	}

	/**
	 * Sets the value of the anyPartyEmailAddressIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAnyPartyEmailAddressIdentifier(String value) {
		this.anyPartyEmailAddressIdentifier = value;
	}

}
