//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for BuyerPostalAddressDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="BuyerPostalAddressDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BuyerStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
 *         &lt;element name="BuyerTownName" type="{}genericStringType2_35"/>
 *         &lt;element name="BuyerPostCodeIdentifier" type="{}genericStringType2_35"/>
 *         &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
 *         &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="BuyerPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuyerPostalAddressDetailsType", propOrder = {
		"buyerStreetName", "buyerTownName", "buyerPostCodeIdentifier",
		"countryCode", "countryName", "buyerPostOfficeBoxIdentifier" })
public class BuyerPostalAddressDetailsType {

	@XmlElement(name = "BuyerStreetName", required = true)
	protected List<String> buyerStreetName;
	@XmlElement(name = "BuyerTownName", required = true)
	protected String buyerTownName;
	@XmlElement(name = "BuyerPostCodeIdentifier", required = true)
	protected String buyerPostCodeIdentifier;
	@XmlElement(name = "CountryCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String countryCode;
	@XmlElement(name = "CountryName")
	protected String countryName;
	@XmlElement(name = "BuyerPostOfficeBoxIdentifier")
	protected String buyerPostOfficeBoxIdentifier;

	/**
	 * Gets the value of the buyerStreetName property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the buyerStreetName property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBuyerStreetName().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getBuyerStreetName() {
		if (buyerStreetName == null) {
			buyerStreetName = new ArrayList<String>();
		}
		return this.buyerStreetName;
	}

	/**
	 * Gets the value of the buyerTownName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBuyerTownName() {
		return buyerTownName;
	}

	/**
	 * Sets the value of the buyerTownName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBuyerTownName(String value) {
		this.buyerTownName = value;
	}

	/**
	 * Gets the value of the buyerPostCodeIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBuyerPostCodeIdentifier() {
		return buyerPostCodeIdentifier;
	}

	/**
	 * Sets the value of the buyerPostCodeIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBuyerPostCodeIdentifier(String value) {
		this.buyerPostCodeIdentifier = value;
	}

	/**
	 * Gets the value of the countryCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountryCode() {
		return countryCode;
	}

	/**
	 * Sets the value of the countryCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountryCode(String value) {
		this.countryCode = value;
	}

	/**
	 * Gets the value of the countryName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountryName() {
		return countryName;
	}

	/**
	 * Sets the value of the countryName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountryName(String value) {
		this.countryName = value;
	}

	/**
	 * Gets the value of the buyerPostOfficeBoxIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBuyerPostOfficeBoxIdentifier() {
		return buyerPostOfficeBoxIdentifier;
	}

	/**
	 * Sets the value of the buyerPostOfficeBoxIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBuyerPostOfficeBoxIdentifier(String value) {
		this.buyerPostOfficeBoxIdentifier = value;
	}

}
