//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for DeliveryDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeliveryDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="DeliveryPeriodDetails" type="{}DeliveryPeriodDetailsType" minOccurs="0"/>
 *         &lt;element name="ShipmentPartyDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ShipmentPartyIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="ShipmentOrganisationName" type="{}genericStringType2_35" maxOccurs="unbounded"/>
 *                   &lt;element name="ShipmentOrganisationDepartment" type="{}genericStringType0_35" maxOccurs="2" minOccurs="0"/>
 *                   &lt;element name="ShipmentOrganisationTaxCode" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="ShipmentCode" type="{}PartyIdentifierType" minOccurs="0"/>
 *                   &lt;element name="ShipmentPostalAddressDetails" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ShipmentStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
 *                             &lt;element name="ShipmentTownName" type="{}genericStringType2_35"/>
 *                             &lt;element name="ShipmentPostCodeIdentifier" type="{}genericStringType2_35"/>
 *                             &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
 *                             &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
 *                             &lt;element name="ShipmentPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ShipmentSiteCode" type="{}genericStringType0_35" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DeliveryMethodText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="DeliveryTermsText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="DeliveryTermsCode" type="{}genericStringType1_4" minOccurs="0"/>
 *         &lt;element name="TerminalAddressText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="WaybillIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="WaybillTypeCode" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="ClearanceIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="DeliveryNoteIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="DelivererIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="DelivererName" type="{}genericStringType0_35" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="DelivererCountryCode" type="{}CountryCodeType" minOccurs="0"/>
 *         &lt;element name="DelivererCountryName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="ModeOfTransportIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="CarrierName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="VesselName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="LocationIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="TransportInformationDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="CountryOfOrigin" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="CountryOfDestinationName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="DestinationCountryCode" type="{}CountryCodeType" minOccurs="0"/>
 *         &lt;element name="PlaceOfDischarge" type="{}genericStringType0_35" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="FinalDestinationName" type="{}genericStringType0_35" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="ManufacturerIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="ManufacturerName" type="{}genericStringType0_35" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="ManufacturerCountryCode" type="{}CountryCodeType" minOccurs="0"/>
 *         &lt;element name="ManufacturerCountryName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="ManufacturerOrderIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="PackageDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PackageLength" type="{}QuantityType0_14" minOccurs="0"/>
 *                   &lt;element name="PackageWidth" type="{}QuantityType0_14" minOccurs="0"/>
 *                   &lt;element name="PackageHeight" type="{}QuantityType0_14" minOccurs="0"/>
 *                   &lt;element name="PackageWeight" type="{}QuantityType0_14" minOccurs="0"/>
 *                   &lt;element name="PackageNetWeight" type="{}QuantityType0_14" minOccurs="0"/>
 *                   &lt;element name="PackageVolume" type="{}QuantityType0_14" minOccurs="0"/>
 *                   &lt;element name="TransportCarriageQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryDetailsType", propOrder = { "deliveryDate",
		"deliveryPeriodDetails", "shipmentPartyDetails", "deliveryMethodText",
		"deliveryTermsText", "deliveryTermsCode", "terminalAddressText",
		"waybillIdentifier", "waybillTypeCode", "clearanceIdentifier",
		"deliveryNoteIdentifier", "delivererIdentifier", "delivererName",
		"delivererCountryCode", "delivererCountryName",
		"modeOfTransportIdentifier", "carrierName", "vesselName",
		"locationIdentifier", "transportInformationDate", "countryOfOrigin",
		"countryOfDestinationName", "destinationCountryCode",
		"placeOfDischarge", "finalDestinationName", "manufacturerIdentifier",
		"manufacturerName", "manufacturerCountryCode",
		"manufacturerCountryName", "manufacturerOrderIdentifier",
		"packageDetails" })
public class DeliveryDetailsType {

	@XmlElement(name = "DeliveryDate")
	protected Date deliveryDate;
	@XmlElement(name = "DeliveryPeriodDetails")
	protected DeliveryPeriodDetailsType deliveryPeriodDetails;
	@XmlElement(name = "ShipmentPartyDetails")
	protected DeliveryDetailsType.ShipmentPartyDetails shipmentPartyDetails;
	@XmlElement(name = "DeliveryMethodText")
	protected String deliveryMethodText;
	@XmlElement(name = "DeliveryTermsText")
	protected String deliveryTermsText;
	@XmlElement(name = "DeliveryTermsCode")
	protected String deliveryTermsCode;
	@XmlElement(name = "TerminalAddressText")
	protected String terminalAddressText;
	@XmlElement(name = "WaybillIdentifier")
	protected String waybillIdentifier;
	@XmlElement(name = "WaybillTypeCode")
	protected String waybillTypeCode;
	@XmlElement(name = "ClearanceIdentifier")
	protected String clearanceIdentifier;
	@XmlElement(name = "DeliveryNoteIdentifier")
	protected String deliveryNoteIdentifier;
	@XmlElement(name = "DelivererIdentifier")
	protected String delivererIdentifier;
	@XmlElement(name = "DelivererName")
	protected List<String> delivererName;
	@XmlElement(name = "DelivererCountryCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String delivererCountryCode;
	@XmlElement(name = "DelivererCountryName")
	protected String delivererCountryName;
	@XmlElement(name = "ModeOfTransportIdentifier")
	protected String modeOfTransportIdentifier;
	@XmlElement(name = "CarrierName")
	protected String carrierName;
	@XmlElement(name = "VesselName")
	protected String vesselName;
	@XmlElement(name = "LocationIdentifier")
	protected String locationIdentifier;
	@XmlElement(name = "TransportInformationDate")
	protected Date transportInformationDate;
	@XmlElement(name = "CountryOfOrigin")
	protected String countryOfOrigin;
	@XmlElement(name = "CountryOfDestinationName")
	protected String countryOfDestinationName;
	@XmlElement(name = "DestinationCountryCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String destinationCountryCode;
	@XmlElement(name = "PlaceOfDischarge")
	protected List<String> placeOfDischarge;
	@XmlElement(name = "FinalDestinationName")
	protected List<String> finalDestinationName;
	@XmlElement(name = "ManufacturerIdentifier")
	protected String manufacturerIdentifier;
	@XmlElement(name = "ManufacturerName")
	protected List<String> manufacturerName;
	@XmlElement(name = "ManufacturerCountryCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String manufacturerCountryCode;
	@XmlElement(name = "ManufacturerCountryName")
	protected String manufacturerCountryName;
	@XmlElement(name = "ManufacturerOrderIdentifier")
	protected String manufacturerOrderIdentifier;
	@XmlElement(name = "PackageDetails")
	protected DeliveryDetailsType.PackageDetails packageDetails;

	/**
	 * Gets the value of the deliveryDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getDeliveryDate() {
		return deliveryDate;
	}

	/**
	 * Sets the value of the deliveryDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setDeliveryDate(Date value) {
		this.deliveryDate = value;
	}

	/**
	 * Gets the value of the deliveryPeriodDetails property.
	 * 
	 * @return possible object is {@link DeliveryPeriodDetailsType }
	 * 
	 */
	public DeliveryPeriodDetailsType getDeliveryPeriodDetails() {
		return deliveryPeriodDetails;
	}

	/**
	 * Sets the value of the deliveryPeriodDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link DeliveryPeriodDetailsType }
	 * 
	 */
	public void setDeliveryPeriodDetails(DeliveryPeriodDetailsType value) {
		this.deliveryPeriodDetails = value;
	}

	/**
	 * Gets the value of the shipmentPartyDetails property.
	 * 
	 * @return possible object is
	 *         {@link DeliveryDetailsType.ShipmentPartyDetails }
	 * 
	 */
	public DeliveryDetailsType.ShipmentPartyDetails getShipmentPartyDetails() {
		return shipmentPartyDetails;
	}

	/**
	 * Sets the value of the shipmentPartyDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link DeliveryDetailsType.ShipmentPartyDetails }
	 * 
	 */
	public void setShipmentPartyDetails(
			DeliveryDetailsType.ShipmentPartyDetails value) {
		this.shipmentPartyDetails = value;
	}

	/**
	 * Gets the value of the deliveryMethodText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeliveryMethodText() {
		return deliveryMethodText;
	}

	/**
	 * Sets the value of the deliveryMethodText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeliveryMethodText(String value) {
		this.deliveryMethodText = value;
	}

	/**
	 * Gets the value of the deliveryTermsText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeliveryTermsText() {
		return deliveryTermsText;
	}

	/**
	 * Sets the value of the deliveryTermsText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeliveryTermsText(String value) {
		this.deliveryTermsText = value;
	}

	/**
	 * Gets the value of the deliveryTermsCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeliveryTermsCode() {
		return deliveryTermsCode;
	}

	/**
	 * Sets the value of the deliveryTermsCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeliveryTermsCode(String value) {
		this.deliveryTermsCode = value;
	}

	/**
	 * Gets the value of the terminalAddressText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTerminalAddressText() {
		return terminalAddressText;
	}

	/**
	 * Sets the value of the terminalAddressText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTerminalAddressText(String value) {
		this.terminalAddressText = value;
	}

	/**
	 * Gets the value of the waybillIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWaybillIdentifier() {
		return waybillIdentifier;
	}

	/**
	 * Sets the value of the waybillIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWaybillIdentifier(String value) {
		this.waybillIdentifier = value;
	}

	/**
	 * Gets the value of the waybillTypeCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWaybillTypeCode() {
		return waybillTypeCode;
	}

	/**
	 * Sets the value of the waybillTypeCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWaybillTypeCode(String value) {
		this.waybillTypeCode = value;
	}

	/**
	 * Gets the value of the clearanceIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClearanceIdentifier() {
		return clearanceIdentifier;
	}

	/**
	 * Sets the value of the clearanceIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClearanceIdentifier(String value) {
		this.clearanceIdentifier = value;
	}

	/**
	 * Gets the value of the deliveryNoteIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeliveryNoteIdentifier() {
		return deliveryNoteIdentifier;
	}

	/**
	 * Sets the value of the deliveryNoteIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeliveryNoteIdentifier(String value) {
		this.deliveryNoteIdentifier = value;
	}

	/**
	 * Gets the value of the delivererIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDelivererIdentifier() {
		return delivererIdentifier;
	}

	/**
	 * Sets the value of the delivererIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDelivererIdentifier(String value) {
		this.delivererIdentifier = value;
	}

	/**
	 * Gets the value of the delivererName property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the delivererName property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDelivererName().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getDelivererName() {
		if (delivererName == null) {
			delivererName = new ArrayList<String>();
		}
		return this.delivererName;
	}

	/**
	 * Gets the value of the delivererCountryCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDelivererCountryCode() {
		return delivererCountryCode;
	}

	/**
	 * Sets the value of the delivererCountryCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDelivererCountryCode(String value) {
		this.delivererCountryCode = value;
	}

	/**
	 * Gets the value of the delivererCountryName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDelivererCountryName() {
		return delivererCountryName;
	}

	/**
	 * Sets the value of the delivererCountryName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDelivererCountryName(String value) {
		this.delivererCountryName = value;
	}

	/**
	 * Gets the value of the modeOfTransportIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getModeOfTransportIdentifier() {
		return modeOfTransportIdentifier;
	}

	/**
	 * Sets the value of the modeOfTransportIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModeOfTransportIdentifier(String value) {
		this.modeOfTransportIdentifier = value;
	}

	/**
	 * Gets the value of the carrierName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCarrierName() {
		return carrierName;
	}

	/**
	 * Sets the value of the carrierName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCarrierName(String value) {
		this.carrierName = value;
	}

	/**
	 * Gets the value of the vesselName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVesselName() {
		return vesselName;
	}

	/**
	 * Sets the value of the vesselName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVesselName(String value) {
		this.vesselName = value;
	}

	/**
	 * Gets the value of the locationIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLocationIdentifier() {
		return locationIdentifier;
	}

	/**
	 * Sets the value of the locationIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLocationIdentifier(String value) {
		this.locationIdentifier = value;
	}

	/**
	 * Gets the value of the transportInformationDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getTransportInformationDate() {
		return transportInformationDate;
	}

	/**
	 * Sets the value of the transportInformationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setTransportInformationDate(Date value) {
		this.transportInformationDate = value;
	}

	/**
	 * Gets the value of the countryOfOrigin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountryOfOrigin() {
		return countryOfOrigin;
	}

	/**
	 * Sets the value of the countryOfOrigin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountryOfOrigin(String value) {
		this.countryOfOrigin = value;
	}

	/**
	 * Gets the value of the countryOfDestinationName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountryOfDestinationName() {
		return countryOfDestinationName;
	}

	/**
	 * Sets the value of the countryOfDestinationName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountryOfDestinationName(String value) {
		this.countryOfDestinationName = value;
	}

	/**
	 * Gets the value of the destinationCountryCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDestinationCountryCode() {
		return destinationCountryCode;
	}

	/**
	 * Sets the value of the destinationCountryCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDestinationCountryCode(String value) {
		this.destinationCountryCode = value;
	}

	/**
	 * Gets the value of the placeOfDischarge property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the placeOfDischarge property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPlaceOfDischarge().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getPlaceOfDischarge() {
		if (placeOfDischarge == null) {
			placeOfDischarge = new ArrayList<String>();
		}
		return this.placeOfDischarge;
	}

	/**
	 * Gets the value of the finalDestinationName property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the finalDestinationName property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFinalDestinationName().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getFinalDestinationName() {
		if (finalDestinationName == null) {
			finalDestinationName = new ArrayList<String>();
		}
		return this.finalDestinationName;
	}

	/**
	 * Gets the value of the manufacturerIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getManufacturerIdentifier() {
		return manufacturerIdentifier;
	}

	/**
	 * Sets the value of the manufacturerIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setManufacturerIdentifier(String value) {
		this.manufacturerIdentifier = value;
	}

	/**
	 * Gets the value of the manufacturerName property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the manufacturerName property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getManufacturerName().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getManufacturerName() {
		if (manufacturerName == null) {
			manufacturerName = new ArrayList<String>();
		}
		return this.manufacturerName;
	}

	/**
	 * Gets the value of the manufacturerCountryCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getManufacturerCountryCode() {
		return manufacturerCountryCode;
	}

	/**
	 * Sets the value of the manufacturerCountryCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setManufacturerCountryCode(String value) {
		this.manufacturerCountryCode = value;
	}

	/**
	 * Gets the value of the manufacturerCountryName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getManufacturerCountryName() {
		return manufacturerCountryName;
	}

	/**
	 * Sets the value of the manufacturerCountryName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setManufacturerCountryName(String value) {
		this.manufacturerCountryName = value;
	}

	/**
	 * Gets the value of the manufacturerOrderIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getManufacturerOrderIdentifier() {
		return manufacturerOrderIdentifier;
	}

	/**
	 * Sets the value of the manufacturerOrderIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setManufacturerOrderIdentifier(String value) {
		this.manufacturerOrderIdentifier = value;
	}

	/**
	 * Gets the value of the packageDetails property.
	 * 
	 * @return possible object is {@link DeliveryDetailsType.PackageDetails }
	 * 
	 */
	public DeliveryDetailsType.PackageDetails getPackageDetails() {
		return packageDetails;
	}

	/**
	 * Sets the value of the packageDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link DeliveryDetailsType.PackageDetails }
	 * 
	 */
	public void setPackageDetails(DeliveryDetailsType.PackageDetails value) {
		this.packageDetails = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="PackageLength" type="{}QuantityType0_14" minOccurs="0"/>
	 *         &lt;element name="PackageWidth" type="{}QuantityType0_14" minOccurs="0"/>
	 *         &lt;element name="PackageHeight" type="{}QuantityType0_14" minOccurs="0"/>
	 *         &lt;element name="PackageWeight" type="{}QuantityType0_14" minOccurs="0"/>
	 *         &lt;element name="PackageNetWeight" type="{}QuantityType0_14" minOccurs="0"/>
	 *         &lt;element name="PackageVolume" type="{}QuantityType0_14" minOccurs="0"/>
	 *         &lt;element name="TransportCarriageQuantity" type="{}QuantityType0_14" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "packageLength", "packageWidth",
			"packageHeight", "packageWeight", "packageNetWeight",
			"packageVolume", "transportCarriageQuantity" })
	public static class PackageDetails {

		@XmlElement(name = "PackageLength")
		protected QuantityType014 packageLength;
		@XmlElement(name = "PackageWidth")
		protected QuantityType014 packageWidth;
		@XmlElement(name = "PackageHeight")
		protected QuantityType014 packageHeight;
		@XmlElement(name = "PackageWeight")
		protected QuantityType014 packageWeight;
		@XmlElement(name = "PackageNetWeight")
		protected QuantityType014 packageNetWeight;
		@XmlElement(name = "PackageVolume")
		protected QuantityType014 packageVolume;
		@XmlElement(name = "TransportCarriageQuantity")
		protected QuantityType014 transportCarriageQuantity;

		/**
		 * Gets the value of the packageLength property.
		 * 
		 * @return possible object is {@link QuantityType014 }
		 * 
		 */
		public QuantityType014 getPackageLength() {
			return packageLength;
		}

		/**
		 * Sets the value of the packageLength property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType014 }
		 * 
		 */
		public void setPackageLength(QuantityType014 value) {
			this.packageLength = value;
		}

		/**
		 * Gets the value of the packageWidth property.
		 * 
		 * @return possible object is {@link QuantityType014 }
		 * 
		 */
		public QuantityType014 getPackageWidth() {
			return packageWidth;
		}

		/**
		 * Sets the value of the packageWidth property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType014 }
		 * 
		 */
		public void setPackageWidth(QuantityType014 value) {
			this.packageWidth = value;
		}

		/**
		 * Gets the value of the packageHeight property.
		 * 
		 * @return possible object is {@link QuantityType014 }
		 * 
		 */
		public QuantityType014 getPackageHeight() {
			return packageHeight;
		}

		/**
		 * Sets the value of the packageHeight property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType014 }
		 * 
		 */
		public void setPackageHeight(QuantityType014 value) {
			this.packageHeight = value;
		}

		/**
		 * Gets the value of the packageWeight property.
		 * 
		 * @return possible object is {@link QuantityType014 }
		 * 
		 */
		public QuantityType014 getPackageWeight() {
			return packageWeight;
		}

		/**
		 * Sets the value of the packageWeight property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType014 }
		 * 
		 */
		public void setPackageWeight(QuantityType014 value) {
			this.packageWeight = value;
		}

		/**
		 * Gets the value of the packageNetWeight property.
		 * 
		 * @return possible object is {@link QuantityType014 }
		 * 
		 */
		public QuantityType014 getPackageNetWeight() {
			return packageNetWeight;
		}

		/**
		 * Sets the value of the packageNetWeight property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType014 }
		 * 
		 */
		public void setPackageNetWeight(QuantityType014 value) {
			this.packageNetWeight = value;
		}

		/**
		 * Gets the value of the packageVolume property.
		 * 
		 * @return possible object is {@link QuantityType014 }
		 * 
		 */
		public QuantityType014 getPackageVolume() {
			return packageVolume;
		}

		/**
		 * Sets the value of the packageVolume property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType014 }
		 * 
		 */
		public void setPackageVolume(QuantityType014 value) {
			this.packageVolume = value;
		}

		/**
		 * Gets the value of the transportCarriageQuantity property.
		 * 
		 * @return possible object is {@link QuantityType014 }
		 * 
		 */
		public QuantityType014 getTransportCarriageQuantity() {
			return transportCarriageQuantity;
		}

		/**
		 * Sets the value of the transportCarriageQuantity property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType014 }
		 * 
		 */
		public void setTransportCarriageQuantity(QuantityType014 value) {
			this.transportCarriageQuantity = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="ShipmentPartyIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="ShipmentOrganisationName" type="{}genericStringType2_35" maxOccurs="unbounded"/>
	 *         &lt;element name="ShipmentOrganisationDepartment" type="{}genericStringType0_35" maxOccurs="2" minOccurs="0"/>
	 *         &lt;element name="ShipmentOrganisationTaxCode" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="ShipmentCode" type="{}PartyIdentifierType" minOccurs="0"/>
	 *         &lt;element name="ShipmentPostalAddressDetails" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="ShipmentStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
	 *                   &lt;element name="ShipmentTownName" type="{}genericStringType2_35"/>
	 *                   &lt;element name="ShipmentPostCodeIdentifier" type="{}genericStringType2_35"/>
	 *                   &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
	 *                   &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
	 *                   &lt;element name="ShipmentPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="ShipmentSiteCode" type="{}genericStringType0_35" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "shipmentPartyIdentifier",
			"shipmentOrganisationName", "shipmentOrganisationDepartment",
			"shipmentOrganisationTaxCode", "shipmentCode",
			"shipmentPostalAddressDetails", "shipmentSiteCode" })
	public static class ShipmentPartyDetails {

		@XmlElement(name = "ShipmentPartyIdentifier")
		protected String shipmentPartyIdentifier;
		@XmlElement(name = "ShipmentOrganisationName", required = true)
		protected List<String> shipmentOrganisationName;
		@XmlElement(name = "ShipmentOrganisationDepartment")
		protected List<String> shipmentOrganisationDepartment;
		@XmlElement(name = "ShipmentOrganisationTaxCode")
		protected String shipmentOrganisationTaxCode;
		@XmlElement(name = "ShipmentCode")
		protected PartyIdentifierType shipmentCode;
		@XmlElement(name = "ShipmentPostalAddressDetails")
		protected DeliveryDetailsType.ShipmentPartyDetails.ShipmentPostalAddressDetails shipmentPostalAddressDetails;
		@XmlElement(name = "ShipmentSiteCode")
		protected String shipmentSiteCode;

		/**
		 * Gets the value of the shipmentPartyIdentifier property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getShipmentPartyIdentifier() {
			return shipmentPartyIdentifier;
		}

		/**
		 * Sets the value of the shipmentPartyIdentifier property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setShipmentPartyIdentifier(String value) {
			this.shipmentPartyIdentifier = value;
		}

		/**
		 * Gets the value of the shipmentOrganisationName property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the shipmentOrganisationName property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getShipmentOrganisationName().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getShipmentOrganisationName() {
			if (shipmentOrganisationName == null) {
				shipmentOrganisationName = new ArrayList<String>();
			}
			return this.shipmentOrganisationName;
		}

		/**
		 * Gets the value of the shipmentOrganisationDepartment property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the shipmentOrganisationDepartment
		 * property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getShipmentOrganisationDepartment().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getShipmentOrganisationDepartment() {
			if (shipmentOrganisationDepartment == null) {
				shipmentOrganisationDepartment = new ArrayList<String>();
			}
			return this.shipmentOrganisationDepartment;
		}

		/**
		 * Gets the value of the shipmentOrganisationTaxCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getShipmentOrganisationTaxCode() {
			return shipmentOrganisationTaxCode;
		}

		/**
		 * Sets the value of the shipmentOrganisationTaxCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setShipmentOrganisationTaxCode(String value) {
			this.shipmentOrganisationTaxCode = value;
		}

		/**
		 * Gets the value of the shipmentCode property.
		 * 
		 * @return possible object is {@link PartyIdentifierType }
		 * 
		 */
		public PartyIdentifierType getShipmentCode() {
			return shipmentCode;
		}

		/**
		 * Sets the value of the shipmentCode property.
		 * 
		 * @param value
		 *            allowed object is {@link PartyIdentifierType }
		 * 
		 */
		public void setShipmentCode(PartyIdentifierType value) {
			this.shipmentCode = value;
		}

		/**
		 * Gets the value of the shipmentPostalAddressDetails property.
		 * 
		 * @return possible object is
		 *         {@link DeliveryDetailsType.ShipmentPartyDetails.ShipmentPostalAddressDetails }
		 * 
		 */
		public DeliveryDetailsType.ShipmentPartyDetails.ShipmentPostalAddressDetails getShipmentPostalAddressDetails() {
			return shipmentPostalAddressDetails;
		}

		/**
		 * Sets the value of the shipmentPostalAddressDetails property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link DeliveryDetailsType.ShipmentPartyDetails.ShipmentPostalAddressDetails }
		 * 
		 */
		public void setShipmentPostalAddressDetails(
				DeliveryDetailsType.ShipmentPartyDetails.ShipmentPostalAddressDetails value) {
			this.shipmentPostalAddressDetails = value;
		}

		/**
		 * Gets the value of the shipmentSiteCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getShipmentSiteCode() {
			return shipmentSiteCode;
		}

		/**
		 * Sets the value of the shipmentSiteCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setShipmentSiteCode(String value) {
			this.shipmentSiteCode = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="ShipmentStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
		 *         &lt;element name="ShipmentTownName" type="{}genericStringType2_35"/>
		 *         &lt;element name="ShipmentPostCodeIdentifier" type="{}genericStringType2_35"/>
		 *         &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
		 *         &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
		 *         &lt;element name="ShipmentPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "shipmentStreetName",
				"shipmentTownName", "shipmentPostCodeIdentifier",
				"countryCode", "countryName", "shipmentPostOfficeBoxIdentifier" })
		public static class ShipmentPostalAddressDetails {

			@XmlElement(name = "ShipmentStreetName", required = true)
			protected List<String> shipmentStreetName;
			@XmlElement(name = "ShipmentTownName", required = true)
			protected String shipmentTownName;
			@XmlElement(name = "ShipmentPostCodeIdentifier", required = true)
			protected String shipmentPostCodeIdentifier;
			@XmlElement(name = "CountryCode")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String countryCode;
			@XmlElement(name = "CountryName")
			protected String countryName;
			@XmlElement(name = "ShipmentPostOfficeBoxIdentifier")
			protected String shipmentPostOfficeBoxIdentifier;

			/**
			 * Gets the value of the shipmentStreetName property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the shipmentStreetName
			 * property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getShipmentStreetName().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getShipmentStreetName() {
				if (shipmentStreetName == null) {
					shipmentStreetName = new ArrayList<String>();
				}
				return this.shipmentStreetName;
			}

			/**
			 * Gets the value of the shipmentTownName property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getShipmentTownName() {
				return shipmentTownName;
			}

			/**
			 * Sets the value of the shipmentTownName property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setShipmentTownName(String value) {
				this.shipmentTownName = value;
			}

			/**
			 * Gets the value of the shipmentPostCodeIdentifier property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getShipmentPostCodeIdentifier() {
				return shipmentPostCodeIdentifier;
			}

			/**
			 * Sets the value of the shipmentPostCodeIdentifier property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setShipmentPostCodeIdentifier(String value) {
				this.shipmentPostCodeIdentifier = value;
			}

			/**
			 * Gets the value of the countryCode property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCountryCode() {
				return countryCode;
			}

			/**
			 * Sets the value of the countryCode property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCountryCode(String value) {
				this.countryCode = value;
			}

			/**
			 * Gets the value of the countryName property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCountryName() {
				return countryName;
			}

			/**
			 * Sets the value of the countryName property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCountryName(String value) {
				this.countryName = value;
			}

			/**
			 * Gets the value of the shipmentPostOfficeBoxIdentifier property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getShipmentPostOfficeBoxIdentifier() {
				return shipmentPostOfficeBoxIdentifier;
			}

			/**
			 * Sets the value of the shipmentPostOfficeBoxIdentifier property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setShipmentPostOfficeBoxIdentifier(String value) {
				this.shipmentPostOfficeBoxIdentifier = value;
			}

		}

	}

}
