//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DeliveryPartyDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryPartyDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeliveryPartyIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="DeliveryOrganisationName" type="{}genericStringType2_35" maxOccurs="unbounded"/>
 *         &lt;element name="DeliveryOrganisationDepartment" type="{}genericStringType0_35" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="DeliveryOrganisationTaxCode" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="DeliveryCode" type="{}PartyIdentifierType" minOccurs="0"/>
 *         &lt;element name="DeliveryPostalAddressDetails" type="{}DeliveryPostalAddressDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryPartyDetailsType", propOrder = {
		"deliveryPartyIdentifier", "deliveryOrganisationName",
		"deliveryOrganisationDepartment", "deliveryOrganisationTaxCode",
		"deliveryCode", "deliveryPostalAddressDetails" })
public class DeliveryPartyDetailsType {

	@XmlElement(name = "DeliveryPartyIdentifier")
	protected String deliveryPartyIdentifier;
	@XmlElement(name = "DeliveryOrganisationName", required = true)
	protected List<String> deliveryOrganisationName;
	@XmlElement(name = "DeliveryOrganisationDepartment")
	protected List<String> deliveryOrganisationDepartment;
	@XmlElement(name = "DeliveryOrganisationTaxCode")
	protected String deliveryOrganisationTaxCode;
	@XmlElement(name = "DeliveryCode")
	protected PartyIdentifierType deliveryCode;
	@XmlElement(name = "DeliveryPostalAddressDetails", required = true)
	protected DeliveryPostalAddressDetailsType deliveryPostalAddressDetails;

	/**
	 * Gets the value of the deliveryPartyIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeliveryPartyIdentifier() {
		return deliveryPartyIdentifier;
	}

	/**
	 * Sets the value of the deliveryPartyIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeliveryPartyIdentifier(String value) {
		this.deliveryPartyIdentifier = value;
	}

	/**
	 * Gets the value of the deliveryOrganisationName property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the deliveryOrganisationName property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDeliveryOrganisationName().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getDeliveryOrganisationName() {
		if (deliveryOrganisationName == null) {
			deliveryOrganisationName = new ArrayList<String>();
		}
		return this.deliveryOrganisationName;
	}

	/**
	 * Gets the value of the deliveryOrganisationDepartment property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the deliveryOrganisationDepartment property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDeliveryOrganisationDepartment().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getDeliveryOrganisationDepartment() {
		if (deliveryOrganisationDepartment == null) {
			deliveryOrganisationDepartment = new ArrayList<String>();
		}
		return this.deliveryOrganisationDepartment;
	}

	/**
	 * Gets the value of the deliveryOrganisationTaxCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeliveryOrganisationTaxCode() {
		return deliveryOrganisationTaxCode;
	}

	/**
	 * Sets the value of the deliveryOrganisationTaxCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeliveryOrganisationTaxCode(String value) {
		this.deliveryOrganisationTaxCode = value;
	}

	/**
	 * Gets the value of the deliveryCode property.
	 * 
	 * @return possible object is {@link PartyIdentifierType }
	 * 
	 */
	public PartyIdentifierType getDeliveryCode() {
		return deliveryCode;
	}

	/**
	 * Sets the value of the deliveryCode property.
	 * 
	 * @param value
	 *            allowed object is {@link PartyIdentifierType }
	 * 
	 */
	public void setDeliveryCode(PartyIdentifierType value) {
		this.deliveryCode = value;
	}

	/**
	 * Gets the value of the deliveryPostalAddressDetails property.
	 * 
	 * @return possible object is {@link DeliveryPostalAddressDetailsType }
	 * 
	 */
	public DeliveryPostalAddressDetailsType getDeliveryPostalAddressDetails() {
		return deliveryPostalAddressDetails;
	}

	/**
	 * Sets the value of the deliveryPostalAddressDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link DeliveryPostalAddressDetailsType }
	 * 
	 */
	public void setDeliveryPostalAddressDetails(
			DeliveryPostalAddressDetailsType value) {
		this.deliveryPostalAddressDetails = value;
	}

}
