//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EpiBfiPartyDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EpiBfiPartyDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EpiBfiIdentifier" type="{}EpiBfiIdentifierType" minOccurs="0"/>
 *         &lt;element name="EpiBfiName" type="{}genericStringType1_35" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpiBfiPartyDetailsType", propOrder = { "epiBfiIdentifier",
		"epiBfiName" })
public class EpiBfiPartyDetailsType {

	@XmlElement(name = "EpiBfiIdentifier")
	protected EpiBfiIdentifierType epiBfiIdentifier;
	@XmlElement(name = "EpiBfiName")
	protected String epiBfiName;

	/**
	 * Gets the value of the epiBfiIdentifier property.
	 * 
	 * @return possible object is {@link EpiBfiIdentifierType }
	 * 
	 */
	public EpiBfiIdentifierType getEpiBfiIdentifier() {
		return epiBfiIdentifier;
	}

	/**
	 * Sets the value of the epiBfiIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link EpiBfiIdentifierType }
	 * 
	 */
	public void setEpiBfiIdentifier(EpiBfiIdentifierType value) {
		this.epiBfiIdentifier = value;
	}

	/**
	 * Gets the value of the epiBfiName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEpiBfiName() {
		return epiBfiName;
	}

	/**
	 * Sets the value of the epiBfiName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEpiBfiName(String value) {
		this.epiBfiName = value;
	}

}
