//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for EpiIdentificationDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EpiIdentificationDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EpiDate" type="{}date"/>
 *         &lt;element name="EpiReference" type="{}genericNMtokenType0_35"/>
 *         &lt;element name="EpiUrl" type="{}genericNMtokenType0_512" minOccurs="0"/>
 *         &lt;element name="EpiEmail" type="{}genericStringType0_70" minOccurs="0"/>
 *         &lt;element name="EpiOrderInfo" type="{}genericTokenType0_70" maxOccurs="7" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpiIdentificationDetailsType", propOrder = { "epiDate",
		"epiReference", "epiUrl", "epiEmail", "epiOrderInfo" })
public class EpiIdentificationDetailsType {

	@XmlElement(name = "EpiDate", required = true)
	protected Date epiDate;
	@XmlElement(name = "EpiReference", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String epiReference;
	@XmlElement(name = "EpiUrl")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String epiUrl;
	@XmlElement(name = "EpiEmail")
	protected String epiEmail;
	@XmlElement(name = "EpiOrderInfo")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected List<String> epiOrderInfo;

	/**
	 * Gets the value of the epiDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getEpiDate() {
		return epiDate;
	}

	/**
	 * Sets the value of the epiDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setEpiDate(Date value) {
		this.epiDate = value;
	}

	/**
	 * Gets the value of the epiReference property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEpiReference() {
		return epiReference;
	}

	/**
	 * Sets the value of the epiReference property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEpiReference(String value) {
		this.epiReference = value;
	}

	/**
	 * Gets the value of the epiUrl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEpiUrl() {
		return epiUrl;
	}

	/**
	 * Sets the value of the epiUrl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEpiUrl(String value) {
		this.epiUrl = value;
	}

	/**
	 * Gets the value of the epiEmail property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEpiEmail() {
		return epiEmail;
	}

	/**
	 * Sets the value of the epiEmail property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEpiEmail(String value) {
		this.epiEmail = value;
	}

	/**
	 * Gets the value of the epiOrderInfo property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the epiOrderInfo property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEpiOrderInfo().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getEpiOrderInfo() {
		if (epiOrderInfo == null) {
			epiOrderInfo = new ArrayList<String>();
		}
		return this.epiOrderInfo;
	}

}
