//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for EpiPaymentInstructionDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EpiPaymentInstructionDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EpiPaymentInstructionId" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="EpiTransactionTypeCode" type="{}genericTokenType3" minOccurs="0"/>
 *         &lt;element name="EpiInstructionCode" type="{}genericNMtokenType0_35" minOccurs="0"/>
 *         &lt;element name="EpiRemittanceInfoIdentifier" type="{}EpiRemittanceInfoIdentifierType" minOccurs="0"/>
 *         &lt;element name="EpiInstructedAmount" type="{}epiAmount"/>
 *         &lt;element name="EpiCharge" type="{}EpiChargeType"/>
 *         &lt;element name="EpiDateOptionDate" type="{}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpiPaymentInstructionDetailsType", propOrder = {
		"epiPaymentInstructionId", "epiTransactionTypeCode",
		"epiInstructionCode", "epiRemittanceInfoIdentifier",
		"epiInstructedAmount", "epiCharge", "epiDateOptionDate" })
public class EpiPaymentInstructionDetailsType {

	@XmlElement(name = "EpiPaymentInstructionId")
	protected String epiPaymentInstructionId;
	@XmlElement(name = "EpiTransactionTypeCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String epiTransactionTypeCode;
	@XmlElement(name = "EpiInstructionCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String epiInstructionCode;
	@XmlElement(name = "EpiRemittanceInfoIdentifier")
	protected EpiRemittanceInfoIdentifierType epiRemittanceInfoIdentifier;
	@XmlElement(name = "EpiInstructedAmount", required = true)
	protected EpiAmount epiInstructedAmount;
	@XmlElement(name = "EpiCharge", required = true)
	protected EpiChargeType epiCharge;
	@XmlElement(name = "EpiDateOptionDate", required = true)
	protected Date epiDateOptionDate;

	/**
	 * Gets the value of the epiPaymentInstructionId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEpiPaymentInstructionId() {
		return epiPaymentInstructionId;
	}

	/**
	 * Sets the value of the epiPaymentInstructionId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEpiPaymentInstructionId(String value) {
		this.epiPaymentInstructionId = value;
	}

	/**
	 * Gets the value of the epiTransactionTypeCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEpiTransactionTypeCode() {
		return epiTransactionTypeCode;
	}

	/**
	 * Sets the value of the epiTransactionTypeCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEpiTransactionTypeCode(String value) {
		this.epiTransactionTypeCode = value;
	}

	/**
	 * Gets the value of the epiInstructionCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEpiInstructionCode() {
		return epiInstructionCode;
	}

	/**
	 * Sets the value of the epiInstructionCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEpiInstructionCode(String value) {
		this.epiInstructionCode = value;
	}

	/**
	 * Gets the value of the epiRemittanceInfoIdentifier property.
	 * 
	 * @return possible object is {@link EpiRemittanceInfoIdentifierType }
	 * 
	 */
	public EpiRemittanceInfoIdentifierType getEpiRemittanceInfoIdentifier() {
		return epiRemittanceInfoIdentifier;
	}

	/**
	 * Sets the value of the epiRemittanceInfoIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link EpiRemittanceInfoIdentifierType }
	 * 
	 */
	public void setEpiRemittanceInfoIdentifier(
			EpiRemittanceInfoIdentifierType value) {
		this.epiRemittanceInfoIdentifier = value;
	}

	/**
	 * Gets the value of the epiInstructedAmount property.
	 * 
	 * @return possible object is {@link EpiAmount }
	 * 
	 */
	public EpiAmount getEpiInstructedAmount() {
		return epiInstructedAmount;
	}

	/**
	 * Sets the value of the epiInstructedAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link EpiAmount }
	 * 
	 */
	public void setEpiInstructedAmount(EpiAmount value) {
		this.epiInstructedAmount = value;
	}

	/**
	 * Gets the value of the epiCharge property.
	 * 
	 * @return possible object is {@link EpiChargeType }
	 * 
	 */
	public EpiChargeType getEpiCharge() {
		return epiCharge;
	}

	/**
	 * Sets the value of the epiCharge property.
	 * 
	 * @param value
	 *            allowed object is {@link EpiChargeType }
	 * 
	 */
	public void setEpiCharge(EpiChargeType value) {
		this.epiCharge = value;
	}

	/**
	 * Gets the value of the epiDateOptionDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getEpiDateOptionDate() {
		return epiDateOptionDate;
	}

	/**
	 * Sets the value of the epiDateOptionDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setEpiDateOptionDate(Date value) {
		this.epiDateOptionDate = value;
	}

}
