//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EpiPartyDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EpiPartyDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EpiBfiPartyDetails" type="{}EpiBfiPartyDetailsType"/>
 *         &lt;element name="EpiBeneficiaryPartyDetails" type="{}EpiBeneficiaryPartyDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpiPartyDetailsType", propOrder = { "epiBfiPartyDetails",
		"epiBeneficiaryPartyDetails" })
public class EpiPartyDetailsType {

	@XmlElement(name = "EpiBfiPartyDetails", required = true)
	protected EpiBfiPartyDetailsType epiBfiPartyDetails;
	@XmlElement(name = "EpiBeneficiaryPartyDetails", required = true)
	protected EpiBeneficiaryPartyDetailsType epiBeneficiaryPartyDetails;

	/**
	 * Gets the value of the epiBfiPartyDetails property.
	 * 
	 * @return possible object is {@link EpiBfiPartyDetailsType }
	 * 
	 */
	public EpiBfiPartyDetailsType getEpiBfiPartyDetails() {
		return epiBfiPartyDetails;
	}

	/**
	 * Sets the value of the epiBfiPartyDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link EpiBfiPartyDetailsType }
	 * 
	 */
	public void setEpiBfiPartyDetails(EpiBfiPartyDetailsType value) {
		this.epiBfiPartyDetails = value;
	}

	/**
	 * Gets the value of the epiBeneficiaryPartyDetails property.
	 * 
	 * @return possible object is {@link EpiBeneficiaryPartyDetailsType }
	 * 
	 */
	public EpiBeneficiaryPartyDetailsType getEpiBeneficiaryPartyDetails() {
		return epiBeneficiaryPartyDetails;
	}

	/**
	 * Sets the value of the epiBeneficiaryPartyDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link EpiBeneficiaryPartyDetailsType }
	 * 
	 */
	public void setEpiBeneficiaryPartyDetails(
			EpiBeneficiaryPartyDetailsType value) {
		this.epiBeneficiaryPartyDetails = value;
	}

}
