//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for InvoiceRowType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceRowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RowSubIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="ArticleIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="ArticleGroupIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="ArticleName" type="{}genericStringType0_100" minOccurs="0"/>
 *         &lt;element name="ArticleInfoUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="BuyerArticleIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="EanCode" type="{}genericTokenType0_35" minOccurs="0"/>
 *         &lt;element name="RowRegistrationNumberIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SerialNumberIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowActionCode" type="{}genericTokenType0_35" minOccurs="0"/>
 *         &lt;element name="RowDefinitionDetails" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RowDefinitionHeaderText">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;>genericStringType0_70">
 *                           &lt;attribute name="DefinitionCode" type="{}genericTokenType1_20" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RowDefinitionValue" type="{}QuantityType0_70" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OfferedQuantity" type="{}QuantityType0_14" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeliveredQuantity" type="{}QuantityType0_14" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OrderedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="ConfirmedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="PostDeliveredQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="InvoicedQuantity" type="{}QuantityType0_14" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreditRequestedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="ReturnedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="StartDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="EndDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="UnitPriceAmount" type="{}unitAmount" minOccurs="0"/>
 *         &lt;element name="UnitPriceVatIncludedAmount" type="{}unitAmount" minOccurs="0"/>
 *         &lt;element name="UnitPriceBaseQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="RowIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="RowOrderPositionIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowIdentifierDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="RowPositionIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="OriginalInvoiceNumber" type="{}genericStringType1_20" minOccurs="0"/>
 *         &lt;element name="RowOrdererName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowSalesPersonName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowOrderConfirmationIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowOrderConfirmationDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="RowDeliveryIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowDeliveryIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="RowDeliveryDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="RowQuotationIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowQuotationIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="RowAgreementIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowAgreementIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="RowRequestOfQuotationIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowRequestOfQuotationIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="RowPriceListIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowPriceListIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="RowProjectReferenceIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowOverDuePaymentDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RowOriginalInvoiceIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="RowOriginalInvoiceDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="RowOriginalDueDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="RowOriginalInvoiceTotalAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="RowOriginalEpiRemittanceInfoIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="RowPaidVatExcludedAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="RowPaidVatIncludedAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="RowPaidDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="RowUnPaidVatExcludedAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="RowUnPaidVatIncludedAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="RowCollectionDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="RowCollectionQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *                   &lt;element name="RowCollectionChargeAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="RowInterestRate" type="{}percentage" minOccurs="0"/>
 *                   &lt;element name="RowInterestStartDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="RowInterestEndDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="RowInterestPeriodText" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="RowInterestDateNumber" type="{}genericNMtokenType0_14" minOccurs="0"/>
 *                   &lt;element name="RowInterestChargeAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="RowInterestChargeVatAmount" type="{}amount" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RowAnyPartyDetails" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RowAnyPartyText" type="{}anypartytexttype0_35"/>
 *                   &lt;element name="RowAnyPartyIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="RowAnyPartyOrganisationName" type="{}genericStringType2_35" maxOccurs="2"/>
 *                   &lt;element name="RowAnyPartyOrganisationDepartment" type="{}genericStringType0_35" maxOccurs="2" minOccurs="0"/>
 *                   &lt;element name="RowAnyPartyOrganisationTaxCode" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="RowAnyPartyPostalAddressDetails" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RowAnyPartyStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
 *                             &lt;element name="RowAnyPartyTownName" type="{}genericStringType2_35"/>
 *                             &lt;element name="RowAnyPartyPostCodeIdentifier" type="{}genericStringType2_35"/>
 *                             &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
 *                             &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
 *                             &lt;element name="RowAnyPartyPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RowAnyPartyOrganisationUnitNumber" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="RowAnyPartySiteCode" type="{}genericStringType0_35" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RowDeliveryDetails" type="{}RowDeliveryDetailsType" minOccurs="0"/>
 *         &lt;element name="RowShortProposedAccountIdentifier" type="{}genericNMtokenType0_4" minOccurs="0"/>
 *         &lt;element name="RowNormalProposedAccountIdentifier" type="{}genericNMtokenType0_4" minOccurs="0"/>
 *         &lt;element name="RowProposedAccountText" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowAccountDimensionText" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowSellerAccountText" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowFreeText" type="{}genericStringType0_512" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RowUsedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="RowPreviousMeterReadingDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="RowLatestMeterReadingDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="RowCalculatedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="RowAveragePriceAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="RowDiscountPercent" type="{}percentage" minOccurs="0"/>
 *         &lt;element name="RowDiscountAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="RowDiscountTypeCode" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowDiscountTypeText" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="RowProgressiveDiscountDetails" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RowDiscountPercent" type="{}percentage" minOccurs="0"/>
 *                   &lt;element name="RowDiscountAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="RowDiscountTypeCode" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="RowDiscountTypeText" type="{}genericStringType0_35" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RowVatRatePercent" type="{}percentage" minOccurs="0"/>
 *         &lt;element name="RowVatCode" type="{}genericStringType0_10" minOccurs="0"/>
 *         &lt;element name="RowVatAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="RowVatExcludedAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="RowAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="RowTransactionDetails" type="{}TransactionDetailsType" minOccurs="0"/>
 *         &lt;element name="SubInvoiceRow" type="{}SubInvoiceRowType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceRowType", propOrder = { "rowSubIdentifier",
		"articleIdentifier", "articleGroupIdentifier", "articleName",
		"articleInfoUrlText", "buyerArticleIdentifier", "eanCode",
		"rowRegistrationNumberIdentifier", "serialNumberIdentifier",
		"rowActionCode", "rowDefinitionDetails", "offeredQuantity",
		"deliveredQuantity", "orderedQuantity", "confirmedQuantity",
		"postDeliveredQuantity", "invoicedQuantity", "creditRequestedQuantity",
		"returnedQuantity", "startDate", "endDate", "unitPriceAmount",
		"unitPriceVatIncludedAmount", "unitPriceBaseQuantity", "rowIdentifier",
		"rowIdentifierUrlText", "rowOrderPositionIdentifier",
		"rowIdentifierDate", "rowPositionIdentifier", "originalInvoiceNumber",
		"rowOrdererName", "rowSalesPersonName",
		"rowOrderConfirmationIdentifier", "rowOrderConfirmationDate",
		"rowDeliveryIdentifier", "rowDeliveryIdentifierUrlText",
		"rowDeliveryDate", "rowQuotationIdentifier",
		"rowQuotationIdentifierUrlText", "rowAgreementIdentifier",
		"rowAgreementIdentifierUrlText", "rowRequestOfQuotationIdentifier",
		"rowRequestOfQuotationIdentifierUrlText", "rowPriceListIdentifier",
		"rowPriceListIdentifierUrlText", "rowProjectReferenceIdentifier",
		"rowOverDuePaymentDetails", "rowAnyPartyDetails", "rowDeliveryDetails",
		"rowShortProposedAccountIdentifier",
		"rowNormalProposedAccountIdentifier", "rowProposedAccountText",
		"rowAccountDimensionText", "rowSellerAccountText", "rowFreeText",
		"rowUsedQuantity", "rowPreviousMeterReadingDate",
		"rowLatestMeterReadingDate", "rowCalculatedQuantity",
		"rowAveragePriceAmount", "rowDiscountPercent", "rowDiscountAmount",
		"rowDiscountTypeCode", "rowDiscountTypeText",
		"rowProgressiveDiscountDetails", "rowVatRatePercent", "rowVatCode",
		"rowVatAmount", "rowVatExcludedAmount", "rowAmount",
		"rowTransactionDetails", "subInvoiceRow" })
public class InvoiceRowType {

	@XmlElement(name = "RowSubIdentifier")
	protected String rowSubIdentifier;
	@XmlElement(name = "ArticleIdentifier")
	protected String articleIdentifier;
	@XmlElement(name = "ArticleGroupIdentifier")
	protected String articleGroupIdentifier;
	@XmlElement(name = "ArticleName")
	protected String articleName;
	@XmlElement(name = "ArticleInfoUrlText")
	protected String articleInfoUrlText;
	@XmlElement(name = "BuyerArticleIdentifier")
	protected String buyerArticleIdentifier;
	@XmlElement(name = "EanCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String eanCode;
	@XmlElement(name = "RowRegistrationNumberIdentifier")
	protected String rowRegistrationNumberIdentifier;
	@XmlElement(name = "SerialNumberIdentifier")
	protected String serialNumberIdentifier;
	@XmlElement(name = "RowActionCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String rowActionCode;
	@XmlElement(name = "RowDefinitionDetails")
	protected List<InvoiceRowType.RowDefinitionDetails> rowDefinitionDetails;
	@XmlElement(name = "OfferedQuantity")
	protected List<QuantityType014> offeredQuantity;
	@XmlElement(name = "DeliveredQuantity")
	protected List<QuantityType014> deliveredQuantity;
	@XmlElement(name = "OrderedQuantity")
	protected QuantityType014 orderedQuantity;
	@XmlElement(name = "ConfirmedQuantity")
	protected QuantityType014 confirmedQuantity;
	@XmlElement(name = "PostDeliveredQuantity")
	protected QuantityType014 postDeliveredQuantity;
	@XmlElement(name = "InvoicedQuantity")
	protected List<QuantityType014> invoicedQuantity;
	@XmlElement(name = "CreditRequestedQuantity")
	protected QuantityType014 creditRequestedQuantity;
	@XmlElement(name = "ReturnedQuantity")
	protected QuantityType014 returnedQuantity;
	@XmlElement(name = "StartDate")
	protected Date startDate;
	@XmlElement(name = "EndDate")
	protected Date endDate;
	@XmlElement(name = "UnitPriceAmount")
	protected UnitAmount unitPriceAmount;
	@XmlElement(name = "UnitPriceVatIncludedAmount")
	protected UnitAmount unitPriceVatIncludedAmount;
	@XmlElement(name = "UnitPriceBaseQuantity")
	protected QuantityType014 unitPriceBaseQuantity;
	@XmlElement(name = "RowIdentifier")
	protected String rowIdentifier;
	@XmlElement(name = "RowIdentifierUrlText")
	protected String rowIdentifierUrlText;
	@XmlElement(name = "RowOrderPositionIdentifier")
	protected String rowOrderPositionIdentifier;
	@XmlElement(name = "RowIdentifierDate")
	protected Date rowIdentifierDate;
	@XmlElement(name = "RowPositionIdentifier")
	protected String rowPositionIdentifier;
	@XmlElement(name = "OriginalInvoiceNumber")
	protected String originalInvoiceNumber;
	@XmlElement(name = "RowOrdererName")
	protected String rowOrdererName;
	@XmlElement(name = "RowSalesPersonName")
	protected String rowSalesPersonName;
	@XmlElement(name = "RowOrderConfirmationIdentifier")
	protected String rowOrderConfirmationIdentifier;
	@XmlElement(name = "RowOrderConfirmationDate")
	protected Date rowOrderConfirmationDate;
	@XmlElement(name = "RowDeliveryIdentifier")
	protected String rowDeliveryIdentifier;
	@XmlElement(name = "RowDeliveryIdentifierUrlText")
	protected String rowDeliveryIdentifierUrlText;
	@XmlElement(name = "RowDeliveryDate")
	protected Date rowDeliveryDate;
	@XmlElement(name = "RowQuotationIdentifier")
	protected String rowQuotationIdentifier;
	@XmlElement(name = "RowQuotationIdentifierUrlText")
	protected String rowQuotationIdentifierUrlText;
	@XmlElement(name = "RowAgreementIdentifier")
	protected String rowAgreementIdentifier;
	@XmlElement(name = "RowAgreementIdentifierUrlText")
	protected String rowAgreementIdentifierUrlText;
	@XmlElement(name = "RowRequestOfQuotationIdentifier")
	protected String rowRequestOfQuotationIdentifier;
	@XmlElement(name = "RowRequestOfQuotationIdentifierUrlText")
	protected String rowRequestOfQuotationIdentifierUrlText;
	@XmlElement(name = "RowPriceListIdentifier")
	protected String rowPriceListIdentifier;
	@XmlElement(name = "RowPriceListIdentifierUrlText")
	protected String rowPriceListIdentifierUrlText;
	@XmlElement(name = "RowProjectReferenceIdentifier")
	protected String rowProjectReferenceIdentifier;
	@XmlElement(name = "RowOverDuePaymentDetails")
	protected InvoiceRowType.RowOverDuePaymentDetails rowOverDuePaymentDetails;
	@XmlElement(name = "RowAnyPartyDetails")
	protected List<InvoiceRowType.RowAnyPartyDetails> rowAnyPartyDetails;
	@XmlElement(name = "RowDeliveryDetails")
	protected RowDeliveryDetailsType rowDeliveryDetails;
	@XmlElement(name = "RowShortProposedAccountIdentifier")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String rowShortProposedAccountIdentifier;
	@XmlElement(name = "RowNormalProposedAccountIdentifier")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String rowNormalProposedAccountIdentifier;
	@XmlElement(name = "RowProposedAccountText")
	protected String rowProposedAccountText;
	@XmlElement(name = "RowAccountDimensionText")
	protected String rowAccountDimensionText;
	@XmlElement(name = "RowSellerAccountText")
	protected String rowSellerAccountText;
	@XmlElement(name = "RowFreeText")
	protected List<String> rowFreeText;
	@XmlElement(name = "RowUsedQuantity")
	protected QuantityType014 rowUsedQuantity;
	@XmlElement(name = "RowPreviousMeterReadingDate")
	protected Date rowPreviousMeterReadingDate;
	@XmlElement(name = "RowLatestMeterReadingDate")
	protected Date rowLatestMeterReadingDate;
	@XmlElement(name = "RowCalculatedQuantity")
	protected QuantityType014 rowCalculatedQuantity;
	@XmlElement(name = "RowAveragePriceAmount")
	protected Amount rowAveragePriceAmount;
	@XmlElement(name = "RowDiscountPercent")
	protected String rowDiscountPercent;
	@XmlElement(name = "RowDiscountAmount")
	protected Amount rowDiscountAmount;
	@XmlElement(name = "RowDiscountTypeCode")
	protected String rowDiscountTypeCode;
	@XmlElement(name = "RowDiscountTypeText")
	protected String rowDiscountTypeText;
	@XmlElement(name = "RowProgressiveDiscountDetails")
	protected List<InvoiceRowType.RowProgressiveDiscountDetails> rowProgressiveDiscountDetails;
	@XmlElement(name = "RowVatRatePercent")
	protected String rowVatRatePercent;
	@XmlElement(name = "RowVatCode")
	protected String rowVatCode;
	@XmlElement(name = "RowVatAmount")
	protected Amount rowVatAmount;
	@XmlElement(name = "RowVatExcludedAmount")
	protected Amount rowVatExcludedAmount;
	@XmlElement(name = "RowAmount")
	protected Amount rowAmount;
	@XmlElement(name = "RowTransactionDetails")
	protected TransactionDetailsType rowTransactionDetails;
	@XmlElement(name = "SubInvoiceRow")
	protected List<SubInvoiceRowType> subInvoiceRow;

	/**
	 * Gets the value of the rowSubIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowSubIdentifier() {
		return rowSubIdentifier;
	}

	/**
	 * Sets the value of the rowSubIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowSubIdentifier(String value) {
		this.rowSubIdentifier = value;
	}

	/**
	 * Gets the value of the articleIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArticleIdentifier() {
		return articleIdentifier;
	}

	/**
	 * Sets the value of the articleIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArticleIdentifier(String value) {
		this.articleIdentifier = value;
	}

	/**
	 * Gets the value of the articleGroupIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArticleGroupIdentifier() {
		return articleGroupIdentifier;
	}

	/**
	 * Sets the value of the articleGroupIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArticleGroupIdentifier(String value) {
		this.articleGroupIdentifier = value;
	}

	/**
	 * Gets the value of the articleName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArticleName() {
		return articleName;
	}

	/**
	 * Sets the value of the articleName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArticleName(String value) {
		this.articleName = value;
	}

	/**
	 * Gets the value of the articleInfoUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArticleInfoUrlText() {
		return articleInfoUrlText;
	}

	/**
	 * Sets the value of the articleInfoUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArticleInfoUrlText(String value) {
		this.articleInfoUrlText = value;
	}

	/**
	 * Gets the value of the buyerArticleIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBuyerArticleIdentifier() {
		return buyerArticleIdentifier;
	}

	/**
	 * Sets the value of the buyerArticleIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBuyerArticleIdentifier(String value) {
		this.buyerArticleIdentifier = value;
	}

	/**
	 * Gets the value of the eanCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEanCode() {
		return eanCode;
	}

	/**
	 * Sets the value of the eanCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEanCode(String value) {
		this.eanCode = value;
	}

	/**
	 * Gets the value of the rowRegistrationNumberIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowRegistrationNumberIdentifier() {
		return rowRegistrationNumberIdentifier;
	}

	/**
	 * Sets the value of the rowRegistrationNumberIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowRegistrationNumberIdentifier(String value) {
		this.rowRegistrationNumberIdentifier = value;
	}

	/**
	 * Gets the value of the serialNumberIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSerialNumberIdentifier() {
		return serialNumberIdentifier;
	}

	/**
	 * Sets the value of the serialNumberIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSerialNumberIdentifier(String value) {
		this.serialNumberIdentifier = value;
	}

	/**
	 * Gets the value of the rowActionCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowActionCode() {
		return rowActionCode;
	}

	/**
	 * Sets the value of the rowActionCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowActionCode(String value) {
		this.rowActionCode = value;
	}

	/**
	 * Gets the value of the rowDefinitionDetails property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the rowDefinitionDetails property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRowDefinitionDetails().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link InvoiceRowType.RowDefinitionDetails }
	 * 
	 * 
	 */
	public List<InvoiceRowType.RowDefinitionDetails> getRowDefinitionDetails() {
		if (rowDefinitionDetails == null) {
			rowDefinitionDetails = new ArrayList<InvoiceRowType.RowDefinitionDetails>();
		}
		return this.rowDefinitionDetails;
	}

	/**
	 * Gets the value of the offeredQuantity property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the offeredQuantity property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOfferedQuantity().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link QuantityType014 }
	 * 
	 * 
	 */
	public List<QuantityType014> getOfferedQuantity() {
		if (offeredQuantity == null) {
			offeredQuantity = new ArrayList<QuantityType014>();
		}
		return this.offeredQuantity;
	}

	/**
	 * Gets the value of the deliveredQuantity property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the deliveredQuantity property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDeliveredQuantity().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link QuantityType014 }
	 * 
	 * 
	 */
	public List<QuantityType014> getDeliveredQuantity() {
		if (deliveredQuantity == null) {
			deliveredQuantity = new ArrayList<QuantityType014>();
		}
		return this.deliveredQuantity;
	}

	/**
	 * Gets the value of the orderedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getOrderedQuantity() {
		return orderedQuantity;
	}

	/**
	 * Sets the value of the orderedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setOrderedQuantity(QuantityType014 value) {
		this.orderedQuantity = value;
	}

	/**
	 * Gets the value of the confirmedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getConfirmedQuantity() {
		return confirmedQuantity;
	}

	/**
	 * Sets the value of the confirmedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setConfirmedQuantity(QuantityType014 value) {
		this.confirmedQuantity = value;
	}

	/**
	 * Gets the value of the postDeliveredQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getPostDeliveredQuantity() {
		return postDeliveredQuantity;
	}

	/**
	 * Sets the value of the postDeliveredQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setPostDeliveredQuantity(QuantityType014 value) {
		this.postDeliveredQuantity = value;
	}

	/**
	 * Gets the value of the invoicedQuantity property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the invoicedQuantity property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInvoicedQuantity().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link QuantityType014 }
	 * 
	 * 
	 */
	public List<QuantityType014> getInvoicedQuantity() {
		if (invoicedQuantity == null) {
			invoicedQuantity = new ArrayList<QuantityType014>();
		}
		return this.invoicedQuantity;
	}

	/**
	 * Gets the value of the creditRequestedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getCreditRequestedQuantity() {
		return creditRequestedQuantity;
	}

	/**
	 * Sets the value of the creditRequestedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setCreditRequestedQuantity(QuantityType014 value) {
		this.creditRequestedQuantity = value;
	}

	/**
	 * Gets the value of the returnedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getReturnedQuantity() {
		return returnedQuantity;
	}

	/**
	 * Sets the value of the returnedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setReturnedQuantity(QuantityType014 value) {
		this.returnedQuantity = value;
	}

	/**
	 * Gets the value of the startDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * Sets the value of the startDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setStartDate(Date value) {
		this.startDate = value;
	}

	/**
	 * Gets the value of the endDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * Sets the value of the endDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setEndDate(Date value) {
		this.endDate = value;
	}

	/**
	 * Gets the value of the unitPriceAmount property.
	 * 
	 * @return possible object is {@link UnitAmount }
	 * 
	 */
	public UnitAmount getUnitPriceAmount() {
		return unitPriceAmount;
	}

	/**
	 * Sets the value of the unitPriceAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link UnitAmount }
	 * 
	 */
	public void setUnitPriceAmount(UnitAmount value) {
		this.unitPriceAmount = value;
	}

	/**
	 * Gets the value of the unitPriceVatIncludedAmount property.
	 * 
	 * @return possible object is {@link UnitAmount }
	 * 
	 */
	public UnitAmount getUnitPriceVatIncludedAmount() {
		return unitPriceVatIncludedAmount;
	}

	/**
	 * Sets the value of the unitPriceVatIncludedAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link UnitAmount }
	 * 
	 */
	public void setUnitPriceVatIncludedAmount(UnitAmount value) {
		this.unitPriceVatIncludedAmount = value;
	}

	/**
	 * Gets the value of the unitPriceBaseQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getUnitPriceBaseQuantity() {
		return unitPriceBaseQuantity;
	}

	/**
	 * Sets the value of the unitPriceBaseQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setUnitPriceBaseQuantity(QuantityType014 value) {
		this.unitPriceBaseQuantity = value;
	}

	/**
	 * Gets the value of the rowIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowIdentifier() {
		return rowIdentifier;
	}

	/**
	 * Sets the value of the rowIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowIdentifier(String value) {
		this.rowIdentifier = value;
	}

	/**
	 * Gets the value of the rowIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowIdentifierUrlText() {
		return rowIdentifierUrlText;
	}

	/**
	 * Sets the value of the rowIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowIdentifierUrlText(String value) {
		this.rowIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the rowOrderPositionIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowOrderPositionIdentifier() {
		return rowOrderPositionIdentifier;
	}

	/**
	 * Sets the value of the rowOrderPositionIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowOrderPositionIdentifier(String value) {
		this.rowOrderPositionIdentifier = value;
	}

	/**
	 * Gets the value of the rowIdentifierDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getRowIdentifierDate() {
		return rowIdentifierDate;
	}

	/**
	 * Sets the value of the rowIdentifierDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setRowIdentifierDate(Date value) {
		this.rowIdentifierDate = value;
	}

	/**
	 * Gets the value of the rowPositionIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowPositionIdentifier() {
		return rowPositionIdentifier;
	}

	/**
	 * Sets the value of the rowPositionIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowPositionIdentifier(String value) {
		this.rowPositionIdentifier = value;
	}

	/**
	 * Gets the value of the originalInvoiceNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOriginalInvoiceNumber() {
		return originalInvoiceNumber;
	}

	/**
	 * Sets the value of the originalInvoiceNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOriginalInvoiceNumber(String value) {
		this.originalInvoiceNumber = value;
	}

	/**
	 * Gets the value of the rowOrdererName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowOrdererName() {
		return rowOrdererName;
	}

	/**
	 * Sets the value of the rowOrdererName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowOrdererName(String value) {
		this.rowOrdererName = value;
	}

	/**
	 * Gets the value of the rowSalesPersonName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowSalesPersonName() {
		return rowSalesPersonName;
	}

	/**
	 * Sets the value of the rowSalesPersonName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowSalesPersonName(String value) {
		this.rowSalesPersonName = value;
	}

	/**
	 * Gets the value of the rowOrderConfirmationIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowOrderConfirmationIdentifier() {
		return rowOrderConfirmationIdentifier;
	}

	/**
	 * Sets the value of the rowOrderConfirmationIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowOrderConfirmationIdentifier(String value) {
		this.rowOrderConfirmationIdentifier = value;
	}

	/**
	 * Gets the value of the rowOrderConfirmationDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getRowOrderConfirmationDate() {
		return rowOrderConfirmationDate;
	}

	/**
	 * Sets the value of the rowOrderConfirmationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setRowOrderConfirmationDate(Date value) {
		this.rowOrderConfirmationDate = value;
	}

	/**
	 * Gets the value of the rowDeliveryIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowDeliveryIdentifier() {
		return rowDeliveryIdentifier;
	}

	/**
	 * Sets the value of the rowDeliveryIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowDeliveryIdentifier(String value) {
		this.rowDeliveryIdentifier = value;
	}

	/**
	 * Gets the value of the rowDeliveryIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowDeliveryIdentifierUrlText() {
		return rowDeliveryIdentifierUrlText;
	}

	/**
	 * Sets the value of the rowDeliveryIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowDeliveryIdentifierUrlText(String value) {
		this.rowDeliveryIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the rowDeliveryDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getRowDeliveryDate() {
		return rowDeliveryDate;
	}

	/**
	 * Sets the value of the rowDeliveryDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setRowDeliveryDate(Date value) {
		this.rowDeliveryDate = value;
	}

	/**
	 * Gets the value of the rowQuotationIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowQuotationIdentifier() {
		return rowQuotationIdentifier;
	}

	/**
	 * Sets the value of the rowQuotationIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowQuotationIdentifier(String value) {
		this.rowQuotationIdentifier = value;
	}

	/**
	 * Gets the value of the rowQuotationIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowQuotationIdentifierUrlText() {
		return rowQuotationIdentifierUrlText;
	}

	/**
	 * Sets the value of the rowQuotationIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowQuotationIdentifierUrlText(String value) {
		this.rowQuotationIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the rowAgreementIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowAgreementIdentifier() {
		return rowAgreementIdentifier;
	}

	/**
	 * Sets the value of the rowAgreementIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowAgreementIdentifier(String value) {
		this.rowAgreementIdentifier = value;
	}

	/**
	 * Gets the value of the rowAgreementIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowAgreementIdentifierUrlText() {
		return rowAgreementIdentifierUrlText;
	}

	/**
	 * Sets the value of the rowAgreementIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowAgreementIdentifierUrlText(String value) {
		this.rowAgreementIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the rowRequestOfQuotationIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowRequestOfQuotationIdentifier() {
		return rowRequestOfQuotationIdentifier;
	}

	/**
	 * Sets the value of the rowRequestOfQuotationIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowRequestOfQuotationIdentifier(String value) {
		this.rowRequestOfQuotationIdentifier = value;
	}

	/**
	 * Gets the value of the rowRequestOfQuotationIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowRequestOfQuotationIdentifierUrlText() {
		return rowRequestOfQuotationIdentifierUrlText;
	}

	/**
	 * Sets the value of the rowRequestOfQuotationIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowRequestOfQuotationIdentifierUrlText(String value) {
		this.rowRequestOfQuotationIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the rowPriceListIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowPriceListIdentifier() {
		return rowPriceListIdentifier;
	}

	/**
	 * Sets the value of the rowPriceListIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowPriceListIdentifier(String value) {
		this.rowPriceListIdentifier = value;
	}

	/**
	 * Gets the value of the rowPriceListIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowPriceListIdentifierUrlText() {
		return rowPriceListIdentifierUrlText;
	}

	/**
	 * Sets the value of the rowPriceListIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowPriceListIdentifierUrlText(String value) {
		this.rowPriceListIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the rowProjectReferenceIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowProjectReferenceIdentifier() {
		return rowProjectReferenceIdentifier;
	}

	/**
	 * Sets the value of the rowProjectReferenceIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowProjectReferenceIdentifier(String value) {
		this.rowProjectReferenceIdentifier = value;
	}

	/**
	 * Gets the value of the rowOverDuePaymentDetails property.
	 * 
	 * @return possible object is
	 *         {@link InvoiceRowType.RowOverDuePaymentDetails }
	 * 
	 */
	public InvoiceRowType.RowOverDuePaymentDetails getRowOverDuePaymentDetails() {
		return rowOverDuePaymentDetails;
	}

	/**
	 * Sets the value of the rowOverDuePaymentDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link InvoiceRowType.RowOverDuePaymentDetails }
	 * 
	 */
	public void setRowOverDuePaymentDetails(
			InvoiceRowType.RowOverDuePaymentDetails value) {
		this.rowOverDuePaymentDetails = value;
	}

	/**
	 * Gets the value of the rowAnyPartyDetails property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the rowAnyPartyDetails property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRowAnyPartyDetails().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link InvoiceRowType.RowAnyPartyDetails }
	 * 
	 * 
	 */
	public List<InvoiceRowType.RowAnyPartyDetails> getRowAnyPartyDetails() {
		if (rowAnyPartyDetails == null) {
			rowAnyPartyDetails = new ArrayList<InvoiceRowType.RowAnyPartyDetails>();
		}
		return this.rowAnyPartyDetails;
	}

	/**
	 * Gets the value of the rowDeliveryDetails property.
	 * 
	 * @return possible object is {@link RowDeliveryDetailsType }
	 * 
	 */
	public RowDeliveryDetailsType getRowDeliveryDetails() {
		return rowDeliveryDetails;
	}

	/**
	 * Sets the value of the rowDeliveryDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link RowDeliveryDetailsType }
	 * 
	 */
	public void setRowDeliveryDetails(RowDeliveryDetailsType value) {
		this.rowDeliveryDetails = value;
	}

	/**
	 * Gets the value of the rowShortProposedAccountIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowShortProposedAccountIdentifier() {
		return rowShortProposedAccountIdentifier;
	}

	/**
	 * Sets the value of the rowShortProposedAccountIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowShortProposedAccountIdentifier(String value) {
		this.rowShortProposedAccountIdentifier = value;
	}

	/**
	 * Gets the value of the rowNormalProposedAccountIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowNormalProposedAccountIdentifier() {
		return rowNormalProposedAccountIdentifier;
	}

	/**
	 * Sets the value of the rowNormalProposedAccountIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowNormalProposedAccountIdentifier(String value) {
		this.rowNormalProposedAccountIdentifier = value;
	}

	/**
	 * Gets the value of the rowProposedAccountText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowProposedAccountText() {
		return rowProposedAccountText;
	}

	/**
	 * Sets the value of the rowProposedAccountText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowProposedAccountText(String value) {
		this.rowProposedAccountText = value;
	}

	/**
	 * Gets the value of the rowAccountDimensionText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowAccountDimensionText() {
		return rowAccountDimensionText;
	}

	/**
	 * Sets the value of the rowAccountDimensionText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowAccountDimensionText(String value) {
		this.rowAccountDimensionText = value;
	}

	/**
	 * Gets the value of the rowSellerAccountText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowSellerAccountText() {
		return rowSellerAccountText;
	}

	/**
	 * Sets the value of the rowSellerAccountText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowSellerAccountText(String value) {
		this.rowSellerAccountText = value;
	}

	/**
	 * Gets the value of the rowFreeText property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the rowFreeText property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRowFreeText().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getRowFreeText() {
		if (rowFreeText == null) {
			rowFreeText = new ArrayList<String>();
		}
		return this.rowFreeText;
	}

	/**
	 * Gets the value of the rowUsedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getRowUsedQuantity() {
		return rowUsedQuantity;
	}

	/**
	 * Sets the value of the rowUsedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setRowUsedQuantity(QuantityType014 value) {
		this.rowUsedQuantity = value;
	}

	/**
	 * Gets the value of the rowPreviousMeterReadingDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getRowPreviousMeterReadingDate() {
		return rowPreviousMeterReadingDate;
	}

	/**
	 * Sets the value of the rowPreviousMeterReadingDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setRowPreviousMeterReadingDate(Date value) {
		this.rowPreviousMeterReadingDate = value;
	}

	/**
	 * Gets the value of the rowLatestMeterReadingDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getRowLatestMeterReadingDate() {
		return rowLatestMeterReadingDate;
	}

	/**
	 * Sets the value of the rowLatestMeterReadingDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setRowLatestMeterReadingDate(Date value) {
		this.rowLatestMeterReadingDate = value;
	}

	/**
	 * Gets the value of the rowCalculatedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getRowCalculatedQuantity() {
		return rowCalculatedQuantity;
	}

	/**
	 * Sets the value of the rowCalculatedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setRowCalculatedQuantity(QuantityType014 value) {
		this.rowCalculatedQuantity = value;
	}

	/**
	 * Gets the value of the rowAveragePriceAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getRowAveragePriceAmount() {
		return rowAveragePriceAmount;
	}

	/**
	 * Sets the value of the rowAveragePriceAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setRowAveragePriceAmount(Amount value) {
		this.rowAveragePriceAmount = value;
	}

	/**
	 * Gets the value of the rowDiscountPercent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowDiscountPercent() {
		return rowDiscountPercent;
	}

	/**
	 * Sets the value of the rowDiscountPercent property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowDiscountPercent(String value) {
		this.rowDiscountPercent = value;
	}

	/**
	 * Gets the value of the rowDiscountAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getRowDiscountAmount() {
		return rowDiscountAmount;
	}

	/**
	 * Sets the value of the rowDiscountAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setRowDiscountAmount(Amount value) {
		this.rowDiscountAmount = value;
	}

	/**
	 * Gets the value of the rowDiscountTypeCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowDiscountTypeCode() {
		return rowDiscountTypeCode;
	}

	/**
	 * Sets the value of the rowDiscountTypeCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowDiscountTypeCode(String value) {
		this.rowDiscountTypeCode = value;
	}

	/**
	 * Gets the value of the rowDiscountTypeText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowDiscountTypeText() {
		return rowDiscountTypeText;
	}

	/**
	 * Sets the value of the rowDiscountTypeText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowDiscountTypeText(String value) {
		this.rowDiscountTypeText = value;
	}

	/**
	 * Gets the value of the rowProgressiveDiscountDetails property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the rowProgressiveDiscountDetails property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRowProgressiveDiscountDetails().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link InvoiceRowType.RowProgressiveDiscountDetails }
	 * 
	 * 
	 */
	public List<InvoiceRowType.RowProgressiveDiscountDetails> getRowProgressiveDiscountDetails() {
		if (rowProgressiveDiscountDetails == null) {
			rowProgressiveDiscountDetails = new ArrayList<InvoiceRowType.RowProgressiveDiscountDetails>();
		}
		return this.rowProgressiveDiscountDetails;
	}

	/**
	 * Gets the value of the rowVatRatePercent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowVatRatePercent() {
		return rowVatRatePercent;
	}

	/**
	 * Sets the value of the rowVatRatePercent property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowVatRatePercent(String value) {
		this.rowVatRatePercent = value;
	}

	/**
	 * Gets the value of the rowVatCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRowVatCode() {
		return rowVatCode;
	}

	/**
	 * Sets the value of the rowVatCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRowVatCode(String value) {
		this.rowVatCode = value;
	}

	/**
	 * Gets the value of the rowVatAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getRowVatAmount() {
		return rowVatAmount;
	}

	/**
	 * Sets the value of the rowVatAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setRowVatAmount(Amount value) {
		this.rowVatAmount = value;
	}

	/**
	 * Gets the value of the rowVatExcludedAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getRowVatExcludedAmount() {
		return rowVatExcludedAmount;
	}

	/**
	 * Sets the value of the rowVatExcludedAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setRowVatExcludedAmount(Amount value) {
		this.rowVatExcludedAmount = value;
	}

	/**
	 * Gets the value of the rowAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getRowAmount() {
		return rowAmount;
	}

	/**
	 * Sets the value of the rowAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setRowAmount(Amount value) {
		this.rowAmount = value;
	}

	/**
	 * Gets the value of the rowTransactionDetails property.
	 * 
	 * @return possible object is {@link TransactionDetailsType }
	 * 
	 */
	public TransactionDetailsType getRowTransactionDetails() {
		return rowTransactionDetails;
	}

	/**
	 * Sets the value of the rowTransactionDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link TransactionDetailsType }
	 * 
	 */
	public void setRowTransactionDetails(TransactionDetailsType value) {
		this.rowTransactionDetails = value;
	}

	/**
	 * Gets the value of the subInvoiceRow property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the subInvoiceRow property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubInvoiceRow().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SubInvoiceRowType }
	 * 
	 * 
	 */
	public List<SubInvoiceRowType> getSubInvoiceRow() {
		if (subInvoiceRow == null) {
			subInvoiceRow = new ArrayList<SubInvoiceRowType>();
		}
		return this.subInvoiceRow;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="RowAnyPartyText" type="{}anypartytexttype0_35"/>
	 *         &lt;element name="RowAnyPartyIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="RowAnyPartyOrganisationName" type="{}genericStringType2_35" maxOccurs="2"/>
	 *         &lt;element name="RowAnyPartyOrganisationDepartment" type="{}genericStringType0_35" maxOccurs="2" minOccurs="0"/>
	 *         &lt;element name="RowAnyPartyOrganisationTaxCode" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="RowAnyPartyPostalAddressDetails" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="RowAnyPartyStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
	 *                   &lt;element name="RowAnyPartyTownName" type="{}genericStringType2_35"/>
	 *                   &lt;element name="RowAnyPartyPostCodeIdentifier" type="{}genericStringType2_35"/>
	 *                   &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
	 *                   &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
	 *                   &lt;element name="RowAnyPartyPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="RowAnyPartyOrganisationUnitNumber" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="RowAnyPartySiteCode" type="{}genericStringType0_35" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "rowAnyPartyText",
			"rowAnyPartyIdentifier", "rowAnyPartyOrganisationName",
			"rowAnyPartyOrganisationDepartment",
			"rowAnyPartyOrganisationTaxCode",
			"rowAnyPartyPostalAddressDetails",
			"rowAnyPartyOrganisationUnitNumber", "rowAnyPartySiteCode" })
	public static class RowAnyPartyDetails {

		@XmlElement(name = "RowAnyPartyText", required = true)
		protected Anypartytexttype035 rowAnyPartyText;
		@XmlElement(name = "RowAnyPartyIdentifier")
		protected String rowAnyPartyIdentifier;
		@XmlElement(name = "RowAnyPartyOrganisationName", required = true)
		protected List<String> rowAnyPartyOrganisationName;
		@XmlElement(name = "RowAnyPartyOrganisationDepartment")
		protected List<String> rowAnyPartyOrganisationDepartment;
		@XmlElement(name = "RowAnyPartyOrganisationTaxCode")
		protected String rowAnyPartyOrganisationTaxCode;
		@XmlElement(name = "RowAnyPartyPostalAddressDetails")
		protected InvoiceRowType.RowAnyPartyDetails.RowAnyPartyPostalAddressDetails rowAnyPartyPostalAddressDetails;
		@XmlElement(name = "RowAnyPartyOrganisationUnitNumber")
		protected String rowAnyPartyOrganisationUnitNumber;
		@XmlElement(name = "RowAnyPartySiteCode")
		protected String rowAnyPartySiteCode;

		/**
		 * Gets the value of the rowAnyPartyText property.
		 * 
		 * @return possible object is {@link Anypartytexttype035 }
		 * 
		 */
		public Anypartytexttype035 getRowAnyPartyText() {
			return rowAnyPartyText;
		}

		/**
		 * Sets the value of the rowAnyPartyText property.
		 * 
		 * @param value
		 *            allowed object is {@link Anypartytexttype035 }
		 * 
		 */
		public void setRowAnyPartyText(Anypartytexttype035 value) {
			this.rowAnyPartyText = value;
		}

		/**
		 * Gets the value of the rowAnyPartyIdentifier property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowAnyPartyIdentifier() {
			return rowAnyPartyIdentifier;
		}

		/**
		 * Sets the value of the rowAnyPartyIdentifier property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowAnyPartyIdentifier(String value) {
			this.rowAnyPartyIdentifier = value;
		}

		/**
		 * Gets the value of the rowAnyPartyOrganisationName property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the rowAnyPartyOrganisationName property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getRowAnyPartyOrganisationName().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getRowAnyPartyOrganisationName() {
			if (rowAnyPartyOrganisationName == null) {
				rowAnyPartyOrganisationName = new ArrayList<String>();
			}
			return this.rowAnyPartyOrganisationName;
		}

		/**
		 * Gets the value of the rowAnyPartyOrganisationDepartment property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the rowAnyPartyOrganisationDepartment
		 * property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getRowAnyPartyOrganisationDepartment().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getRowAnyPartyOrganisationDepartment() {
			if (rowAnyPartyOrganisationDepartment == null) {
				rowAnyPartyOrganisationDepartment = new ArrayList<String>();
			}
			return this.rowAnyPartyOrganisationDepartment;
		}

		/**
		 * Gets the value of the rowAnyPartyOrganisationTaxCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowAnyPartyOrganisationTaxCode() {
			return rowAnyPartyOrganisationTaxCode;
		}

		/**
		 * Sets the value of the rowAnyPartyOrganisationTaxCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowAnyPartyOrganisationTaxCode(String value) {
			this.rowAnyPartyOrganisationTaxCode = value;
		}

		/**
		 * Gets the value of the rowAnyPartyPostalAddressDetails property.
		 * 
		 * @return possible object is
		 *         {@link InvoiceRowType.RowAnyPartyDetails.RowAnyPartyPostalAddressDetails }
		 * 
		 */
		public InvoiceRowType.RowAnyPartyDetails.RowAnyPartyPostalAddressDetails getRowAnyPartyPostalAddressDetails() {
			return rowAnyPartyPostalAddressDetails;
		}

		/**
		 * Sets the value of the rowAnyPartyPostalAddressDetails property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link InvoiceRowType.RowAnyPartyDetails.RowAnyPartyPostalAddressDetails }
		 * 
		 */
		public void setRowAnyPartyPostalAddressDetails(
				InvoiceRowType.RowAnyPartyDetails.RowAnyPartyPostalAddressDetails value) {
			this.rowAnyPartyPostalAddressDetails = value;
		}

		/**
		 * Gets the value of the rowAnyPartyOrganisationUnitNumber property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowAnyPartyOrganisationUnitNumber() {
			return rowAnyPartyOrganisationUnitNumber;
		}

		/**
		 * Sets the value of the rowAnyPartyOrganisationUnitNumber property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowAnyPartyOrganisationUnitNumber(String value) {
			this.rowAnyPartyOrganisationUnitNumber = value;
		}

		/**
		 * Gets the value of the rowAnyPartySiteCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowAnyPartySiteCode() {
			return rowAnyPartySiteCode;
		}

		/**
		 * Sets the value of the rowAnyPartySiteCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowAnyPartySiteCode(String value) {
			this.rowAnyPartySiteCode = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="RowAnyPartyStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
		 *         &lt;element name="RowAnyPartyTownName" type="{}genericStringType2_35"/>
		 *         &lt;element name="RowAnyPartyPostCodeIdentifier" type="{}genericStringType2_35"/>
		 *         &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
		 *         &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
		 *         &lt;element name="RowAnyPartyPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "rowAnyPartyStreetName",
				"rowAnyPartyTownName", "rowAnyPartyPostCodeIdentifier",
				"countryCode", "countryName",
				"rowAnyPartyPostOfficeBoxIdentifier" })
		public static class RowAnyPartyPostalAddressDetails {

			@XmlElement(name = "RowAnyPartyStreetName", required = true)
			protected List<String> rowAnyPartyStreetName;
			@XmlElement(name = "RowAnyPartyTownName", required = true)
			protected String rowAnyPartyTownName;
			@XmlElement(name = "RowAnyPartyPostCodeIdentifier", required = true)
			protected String rowAnyPartyPostCodeIdentifier;
			@XmlElement(name = "CountryCode")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String countryCode;
			@XmlElement(name = "CountryName")
			protected String countryName;
			@XmlElement(name = "RowAnyPartyPostOfficeBoxIdentifier")
			protected String rowAnyPartyPostOfficeBoxIdentifier;

			/**
			 * Gets the value of the rowAnyPartyStreetName property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the rowAnyPartyStreetName
			 * property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getRowAnyPartyStreetName().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getRowAnyPartyStreetName() {
				if (rowAnyPartyStreetName == null) {
					rowAnyPartyStreetName = new ArrayList<String>();
				}
				return this.rowAnyPartyStreetName;
			}

			/**
			 * Gets the value of the rowAnyPartyTownName property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRowAnyPartyTownName() {
				return rowAnyPartyTownName;
			}

			/**
			 * Sets the value of the rowAnyPartyTownName property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRowAnyPartyTownName(String value) {
				this.rowAnyPartyTownName = value;
			}

			/**
			 * Gets the value of the rowAnyPartyPostCodeIdentifier property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRowAnyPartyPostCodeIdentifier() {
				return rowAnyPartyPostCodeIdentifier;
			}

			/**
			 * Sets the value of the rowAnyPartyPostCodeIdentifier property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRowAnyPartyPostCodeIdentifier(String value) {
				this.rowAnyPartyPostCodeIdentifier = value;
			}

			/**
			 * Gets the value of the countryCode property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCountryCode() {
				return countryCode;
			}

			/**
			 * Sets the value of the countryCode property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCountryCode(String value) {
				this.countryCode = value;
			}

			/**
			 * Gets the value of the countryName property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCountryName() {
				return countryName;
			}

			/**
			 * Sets the value of the countryName property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCountryName(String value) {
				this.countryName = value;
			}

			/**
			 * Gets the value of the rowAnyPartyPostOfficeBoxIdentifier
			 * property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getRowAnyPartyPostOfficeBoxIdentifier() {
				return rowAnyPartyPostOfficeBoxIdentifier;
			}

			/**
			 * Sets the value of the rowAnyPartyPostOfficeBoxIdentifier
			 * property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setRowAnyPartyPostOfficeBoxIdentifier(String value) {
				this.rowAnyPartyPostOfficeBoxIdentifier = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="RowDefinitionHeaderText">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;>genericStringType0_70">
	 *                 &lt;attribute name="DefinitionCode" type="{}genericTokenType1_20" />
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="RowDefinitionValue" type="{}QuantityType0_70" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "rowDefinitionHeaderText",
			"rowDefinitionValue" })
	public static class RowDefinitionDetails {

		@XmlElement(name = "RowDefinitionHeaderText", required = true)
		protected InvoiceRowType.RowDefinitionDetails.RowDefinitionHeaderText rowDefinitionHeaderText;
		@XmlElement(name = "RowDefinitionValue")
		protected QuantityType070 rowDefinitionValue;

		/**
		 * Gets the value of the rowDefinitionHeaderText property.
		 * 
		 * @return possible object is
		 *         {@link InvoiceRowType.RowDefinitionDetails.RowDefinitionHeaderText }
		 * 
		 */
		public InvoiceRowType.RowDefinitionDetails.RowDefinitionHeaderText getRowDefinitionHeaderText() {
			return rowDefinitionHeaderText;
		}

		/**
		 * Sets the value of the rowDefinitionHeaderText property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link InvoiceRowType.RowDefinitionDetails.RowDefinitionHeaderText }
		 * 
		 */
		public void setRowDefinitionHeaderText(
				InvoiceRowType.RowDefinitionDetails.RowDefinitionHeaderText value) {
			this.rowDefinitionHeaderText = value;
		}

		/**
		 * Gets the value of the rowDefinitionValue property.
		 * 
		 * @return possible object is {@link QuantityType070 }
		 * 
		 */
		public QuantityType070 getRowDefinitionValue() {
			return rowDefinitionValue;
		}

		/**
		 * Sets the value of the rowDefinitionValue property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType070 }
		 * 
		 */
		public void setRowDefinitionValue(QuantityType070 value) {
			this.rowDefinitionValue = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;>genericStringType0_70">
		 *       &lt;attribute name="DefinitionCode" type="{}genericTokenType1_20" />
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "value" })
		public static class RowDefinitionHeaderText {

			@XmlValue
			protected String value;
			@XmlAttribute(name = "DefinitionCode")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String definitionCode;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the definitionCode property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDefinitionCode() {
				return definitionCode;
			}

			/**
			 * Sets the value of the definitionCode property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDefinitionCode(String value) {
				this.definitionCode = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="RowOriginalInvoiceIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="RowOriginalInvoiceDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="RowOriginalDueDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="RowOriginalInvoiceTotalAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="RowOriginalEpiRemittanceInfoIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="RowPaidVatExcludedAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="RowPaidVatIncludedAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="RowPaidDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="RowUnPaidVatExcludedAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="RowUnPaidVatIncludedAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="RowCollectionDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="RowCollectionQuantity" type="{}QuantityType0_14" minOccurs="0"/>
	 *         &lt;element name="RowCollectionChargeAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="RowInterestRate" type="{}percentage" minOccurs="0"/>
	 *         &lt;element name="RowInterestStartDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="RowInterestEndDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="RowInterestPeriodText" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="RowInterestDateNumber" type="{}genericNMtokenType0_14" minOccurs="0"/>
	 *         &lt;element name="RowInterestChargeAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="RowInterestChargeVatAmount" type="{}amount" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "rowOriginalInvoiceIdentifier",
			"rowOriginalInvoiceDate", "rowOriginalDueDate",
			"rowOriginalInvoiceTotalAmount",
			"rowOriginalEpiRemittanceInfoIdentifier",
			"rowPaidVatExcludedAmount", "rowPaidVatIncludedAmount",
			"rowPaidDate", "rowUnPaidVatExcludedAmount",
			"rowUnPaidVatIncludedAmount", "rowCollectionDate",
			"rowCollectionQuantity", "rowCollectionChargeAmount",
			"rowInterestRate", "rowInterestStartDate", "rowInterestEndDate",
			"rowInterestPeriodText", "rowInterestDateNumber",
			"rowInterestChargeAmount", "rowInterestChargeVatAmount" })
	public static class RowOverDuePaymentDetails {

		@XmlElement(name = "RowOriginalInvoiceIdentifier")
		protected String rowOriginalInvoiceIdentifier;
		@XmlElement(name = "RowOriginalInvoiceDate")
		protected Date rowOriginalInvoiceDate;
		@XmlElement(name = "RowOriginalDueDate")
		protected Date rowOriginalDueDate;
		@XmlElement(name = "RowOriginalInvoiceTotalAmount")
		protected Amount rowOriginalInvoiceTotalAmount;
		@XmlElement(name = "RowOriginalEpiRemittanceInfoIdentifier")
		protected String rowOriginalEpiRemittanceInfoIdentifier;
		@XmlElement(name = "RowPaidVatExcludedAmount")
		protected Amount rowPaidVatExcludedAmount;
		@XmlElement(name = "RowPaidVatIncludedAmount")
		protected Amount rowPaidVatIncludedAmount;
		@XmlElement(name = "RowPaidDate")
		protected Date rowPaidDate;
		@XmlElement(name = "RowUnPaidVatExcludedAmount")
		protected Amount rowUnPaidVatExcludedAmount;
		@XmlElement(name = "RowUnPaidVatIncludedAmount")
		protected Amount rowUnPaidVatIncludedAmount;
		@XmlElement(name = "RowCollectionDate")
		protected Date rowCollectionDate;
		@XmlElement(name = "RowCollectionQuantity")
		protected QuantityType014 rowCollectionQuantity;
		@XmlElement(name = "RowCollectionChargeAmount")
		protected Amount rowCollectionChargeAmount;
		@XmlElement(name = "RowInterestRate")
		protected String rowInterestRate;
		@XmlElement(name = "RowInterestStartDate")
		protected Date rowInterestStartDate;
		@XmlElement(name = "RowInterestEndDate")
		protected Date rowInterestEndDate;
		@XmlElement(name = "RowInterestPeriodText")
		protected String rowInterestPeriodText;
		@XmlElement(name = "RowInterestDateNumber")
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String rowInterestDateNumber;
		@XmlElement(name = "RowInterestChargeAmount")
		protected Amount rowInterestChargeAmount;
		@XmlElement(name = "RowInterestChargeVatAmount")
		protected Amount rowInterestChargeVatAmount;

		/**
		 * Gets the value of the rowOriginalInvoiceIdentifier property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowOriginalInvoiceIdentifier() {
			return rowOriginalInvoiceIdentifier;
		}

		/**
		 * Sets the value of the rowOriginalInvoiceIdentifier property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowOriginalInvoiceIdentifier(String value) {
			this.rowOriginalInvoiceIdentifier = value;
		}

		/**
		 * Gets the value of the rowOriginalInvoiceDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getRowOriginalInvoiceDate() {
			return rowOriginalInvoiceDate;
		}

		/**
		 * Sets the value of the rowOriginalInvoiceDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setRowOriginalInvoiceDate(Date value) {
			this.rowOriginalInvoiceDate = value;
		}

		/**
		 * Gets the value of the rowOriginalDueDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getRowOriginalDueDate() {
			return rowOriginalDueDate;
		}

		/**
		 * Sets the value of the rowOriginalDueDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setRowOriginalDueDate(Date value) {
			this.rowOriginalDueDate = value;
		}

		/**
		 * Gets the value of the rowOriginalInvoiceTotalAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getRowOriginalInvoiceTotalAmount() {
			return rowOriginalInvoiceTotalAmount;
		}

		/**
		 * Sets the value of the rowOriginalInvoiceTotalAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setRowOriginalInvoiceTotalAmount(Amount value) {
			this.rowOriginalInvoiceTotalAmount = value;
		}

		/**
		 * Gets the value of the rowOriginalEpiRemittanceInfoIdentifier
		 * property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowOriginalEpiRemittanceInfoIdentifier() {
			return rowOriginalEpiRemittanceInfoIdentifier;
		}

		/**
		 * Sets the value of the rowOriginalEpiRemittanceInfoIdentifier
		 * property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowOriginalEpiRemittanceInfoIdentifier(String value) {
			this.rowOriginalEpiRemittanceInfoIdentifier = value;
		}

		/**
		 * Gets the value of the rowPaidVatExcludedAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getRowPaidVatExcludedAmount() {
			return rowPaidVatExcludedAmount;
		}

		/**
		 * Sets the value of the rowPaidVatExcludedAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setRowPaidVatExcludedAmount(Amount value) {
			this.rowPaidVatExcludedAmount = value;
		}

		/**
		 * Gets the value of the rowPaidVatIncludedAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getRowPaidVatIncludedAmount() {
			return rowPaidVatIncludedAmount;
		}

		/**
		 * Sets the value of the rowPaidVatIncludedAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setRowPaidVatIncludedAmount(Amount value) {
			this.rowPaidVatIncludedAmount = value;
		}

		/**
		 * Gets the value of the rowPaidDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getRowPaidDate() {
			return rowPaidDate;
		}

		/**
		 * Sets the value of the rowPaidDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setRowPaidDate(Date value) {
			this.rowPaidDate = value;
		}

		/**
		 * Gets the value of the rowUnPaidVatExcludedAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getRowUnPaidVatExcludedAmount() {
			return rowUnPaidVatExcludedAmount;
		}

		/**
		 * Sets the value of the rowUnPaidVatExcludedAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setRowUnPaidVatExcludedAmount(Amount value) {
			this.rowUnPaidVatExcludedAmount = value;
		}

		/**
		 * Gets the value of the rowUnPaidVatIncludedAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getRowUnPaidVatIncludedAmount() {
			return rowUnPaidVatIncludedAmount;
		}

		/**
		 * Sets the value of the rowUnPaidVatIncludedAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setRowUnPaidVatIncludedAmount(Amount value) {
			this.rowUnPaidVatIncludedAmount = value;
		}

		/**
		 * Gets the value of the rowCollectionDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getRowCollectionDate() {
			return rowCollectionDate;
		}

		/**
		 * Sets the value of the rowCollectionDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setRowCollectionDate(Date value) {
			this.rowCollectionDate = value;
		}

		/**
		 * Gets the value of the rowCollectionQuantity property.
		 * 
		 * @return possible object is {@link QuantityType014 }
		 * 
		 */
		public QuantityType014 getRowCollectionQuantity() {
			return rowCollectionQuantity;
		}

		/**
		 * Sets the value of the rowCollectionQuantity property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType014 }
		 * 
		 */
		public void setRowCollectionQuantity(QuantityType014 value) {
			this.rowCollectionQuantity = value;
		}

		/**
		 * Gets the value of the rowCollectionChargeAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getRowCollectionChargeAmount() {
			return rowCollectionChargeAmount;
		}

		/**
		 * Sets the value of the rowCollectionChargeAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setRowCollectionChargeAmount(Amount value) {
			this.rowCollectionChargeAmount = value;
		}

		/**
		 * Gets the value of the rowInterestRate property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowInterestRate() {
			return rowInterestRate;
		}

		/**
		 * Sets the value of the rowInterestRate property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowInterestRate(String value) {
			this.rowInterestRate = value;
		}

		/**
		 * Gets the value of the rowInterestStartDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getRowInterestStartDate() {
			return rowInterestStartDate;
		}

		/**
		 * Sets the value of the rowInterestStartDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setRowInterestStartDate(Date value) {
			this.rowInterestStartDate = value;
		}

		/**
		 * Gets the value of the rowInterestEndDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getRowInterestEndDate() {
			return rowInterestEndDate;
		}

		/**
		 * Sets the value of the rowInterestEndDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setRowInterestEndDate(Date value) {
			this.rowInterestEndDate = value;
		}

		/**
		 * Gets the value of the rowInterestPeriodText property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowInterestPeriodText() {
			return rowInterestPeriodText;
		}

		/**
		 * Sets the value of the rowInterestPeriodText property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowInterestPeriodText(String value) {
			this.rowInterestPeriodText = value;
		}

		/**
		 * Gets the value of the rowInterestDateNumber property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowInterestDateNumber() {
			return rowInterestDateNumber;
		}

		/**
		 * Sets the value of the rowInterestDateNumber property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowInterestDateNumber(String value) {
			this.rowInterestDateNumber = value;
		}

		/**
		 * Gets the value of the rowInterestChargeAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getRowInterestChargeAmount() {
			return rowInterestChargeAmount;
		}

		/**
		 * Sets the value of the rowInterestChargeAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setRowInterestChargeAmount(Amount value) {
			this.rowInterestChargeAmount = value;
		}

		/**
		 * Gets the value of the rowInterestChargeVatAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getRowInterestChargeVatAmount() {
			return rowInterestChargeVatAmount;
		}

		/**
		 * Sets the value of the rowInterestChargeVatAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setRowInterestChargeVatAmount(Amount value) {
			this.rowInterestChargeVatAmount = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="RowDiscountPercent" type="{}percentage" minOccurs="0"/>
	 *         &lt;element name="RowDiscountAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="RowDiscountTypeCode" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="RowDiscountTypeText" type="{}genericStringType0_35" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "rowDiscountPercent",
			"rowDiscountAmount", "rowDiscountTypeCode", "rowDiscountTypeText" })
	public static class RowProgressiveDiscountDetails {

		@XmlElement(name = "RowDiscountPercent")
		protected String rowDiscountPercent;
		@XmlElement(name = "RowDiscountAmount")
		protected Amount rowDiscountAmount;
		@XmlElement(name = "RowDiscountTypeCode")
		protected String rowDiscountTypeCode;
		@XmlElement(name = "RowDiscountTypeText")
		protected String rowDiscountTypeText;

		/**
		 * Gets the value of the rowDiscountPercent property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowDiscountPercent() {
			return rowDiscountPercent;
		}

		/**
		 * Sets the value of the rowDiscountPercent property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowDiscountPercent(String value) {
			this.rowDiscountPercent = value;
		}

		/**
		 * Gets the value of the rowDiscountAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getRowDiscountAmount() {
			return rowDiscountAmount;
		}

		/**
		 * Sets the value of the rowDiscountAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setRowDiscountAmount(Amount value) {
			this.rowDiscountAmount = value;
		}

		/**
		 * Gets the value of the rowDiscountTypeCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowDiscountTypeCode() {
			return rowDiscountTypeCode;
		}

		/**
		 * Sets the value of the rowDiscountTypeCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowDiscountTypeCode(String value) {
			this.rowDiscountTypeCode = value;
		}

		/**
		 * Gets the value of the rowDiscountTypeText property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRowDiscountTypeText() {
			return rowDiscountTypeText;
		}

		/**
		 * Sets the value of the rowDiscountTypeText property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRowDiscountTypeText(String value) {
			this.rowDiscountTypeText = value;
		}

	}

}
