//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for InvoiceSenderPartyDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceSenderPartyDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceSenderPartyIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="InvoiceSenderOrganisationName" type="{}genericStringType2_35" maxOccurs="unbounded"/>
 *         &lt;element name="InvoiceSenderOrganisationTaxCode" type="{}genericNMtokenType0_35" minOccurs="0"/>
 *         &lt;element name="InvoiceSenderCode" type="{}PartyIdentifierType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceSenderPartyDetailsType", propOrder = {
		"invoiceSenderPartyIdentifier", "invoiceSenderOrganisationName",
		"invoiceSenderOrganisationTaxCode", "invoiceSenderCode" })
public class InvoiceSenderPartyDetailsType {

	@XmlElement(name = "InvoiceSenderPartyIdentifier")
	protected String invoiceSenderPartyIdentifier;
	@XmlElement(name = "InvoiceSenderOrganisationName", required = true)
	protected List<String> invoiceSenderOrganisationName;
	@XmlElement(name = "InvoiceSenderOrganisationTaxCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String invoiceSenderOrganisationTaxCode;
	@XmlElement(name = "InvoiceSenderCode")
	protected PartyIdentifierType invoiceSenderCode;

	/**
	 * Gets the value of the invoiceSenderPartyIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInvoiceSenderPartyIdentifier() {
		return invoiceSenderPartyIdentifier;
	}

	/**
	 * Sets the value of the invoiceSenderPartyIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInvoiceSenderPartyIdentifier(String value) {
		this.invoiceSenderPartyIdentifier = value;
	}

	/**
	 * Gets the value of the invoiceSenderOrganisationName property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the invoiceSenderOrganisationName property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInvoiceSenderOrganisationName().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getInvoiceSenderOrganisationName() {
		if (invoiceSenderOrganisationName == null) {
			invoiceSenderOrganisationName = new ArrayList<String>();
		}
		return this.invoiceSenderOrganisationName;
	}

	/**
	 * Gets the value of the invoiceSenderOrganisationTaxCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInvoiceSenderOrganisationTaxCode() {
		return invoiceSenderOrganisationTaxCode;
	}

	/**
	 * Sets the value of the invoiceSenderOrganisationTaxCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInvoiceSenderOrganisationTaxCode(String value) {
		this.invoiceSenderOrganisationTaxCode = value;
	}

	/**
	 * Gets the value of the invoiceSenderCode property.
	 * 
	 * @return possible object is {@link PartyIdentifierType }
	 * 
	 */
	public PartyIdentifierType getInvoiceSenderCode() {
		return invoiceSenderCode;
	}

	/**
	 * Sets the value of the invoiceSenderCode property.
	 * 
	 * @param value
	 *            allowed object is {@link PartyIdentifierType }
	 * 
	 */
	public void setInvoiceSenderCode(PartyIdentifierType value) {
		this.invoiceSenderCode = value;
	}

}
