//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for InvoiceRecipientPartyDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceRecipientPartyDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceRecipientPartyIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="InvoiceRecipientOrganisationName" type="{}genericStringType2_35" maxOccurs="unbounded"/>
 *         &lt;element name="InvoiceRecipientDepartment" type="{}genericStringType0_35" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="InvoiceRecipientOrganisationTaxCode" type="{}genericNMtokenType0_35" minOccurs="0"/>
 *         &lt;element name="InvoiceRecipientCode" type="{}PartyIdentifierType" minOccurs="0"/>
 *         &lt;element name="InvoiceRecipientPostalAddressDetails" type="{}InvoiceRecipientPostalAddressDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceRecipientPartyDetailsType", propOrder = {
		"invoiceRecipientPartyIdentifier", "invoiceRecipientOrganisationName",
		"invoiceRecipientDepartment", "invoiceRecipientOrganisationTaxCode",
		"invoiceRecipientCode", "invoiceRecipientPostalAddressDetails" })
public class InvoiceRecipientPartyDetailsType {

	@XmlElement(name = "InvoiceRecipientPartyIdentifier")
	protected String invoiceRecipientPartyIdentifier;
	@XmlElement(name = "InvoiceRecipientOrganisationName", required = true)
	protected List<String> invoiceRecipientOrganisationName;
	@XmlElement(name = "InvoiceRecipientDepartment")
	protected List<String> invoiceRecipientDepartment;
	@XmlElement(name = "InvoiceRecipientOrganisationTaxCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String invoiceRecipientOrganisationTaxCode;
	@XmlElement(name = "InvoiceRecipientCode")
	protected PartyIdentifierType invoiceRecipientCode;
	@XmlElement(name = "InvoiceRecipientPostalAddressDetails")
	protected InvoiceRecipientPostalAddressDetailsType invoiceRecipientPostalAddressDetails;

	/**
	 * Gets the value of the invoiceRecipientPartyIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInvoiceRecipientPartyIdentifier() {
		return invoiceRecipientPartyIdentifier;
	}

	/**
	 * Sets the value of the invoiceRecipientPartyIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInvoiceRecipientPartyIdentifier(String value) {
		this.invoiceRecipientPartyIdentifier = value;
	}

	/**
	 * Gets the value of the invoiceRecipientOrganisationName property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the invoiceRecipientOrganisationName
	 * property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInvoiceRecipientOrganisationName().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getInvoiceRecipientOrganisationName() {
		if (invoiceRecipientOrganisationName == null) {
			invoiceRecipientOrganisationName = new ArrayList<String>();
		}
		return this.invoiceRecipientOrganisationName;
	}

	/**
	 * Gets the value of the invoiceRecipientDepartment property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the invoiceRecipientDepartment property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInvoiceRecipientDepartment().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getInvoiceRecipientDepartment() {
		if (invoiceRecipientDepartment == null) {
			invoiceRecipientDepartment = new ArrayList<String>();
		}
		return this.invoiceRecipientDepartment;
	}

	/**
	 * Gets the value of the invoiceRecipientOrganisationTaxCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInvoiceRecipientOrganisationTaxCode() {
		return invoiceRecipientOrganisationTaxCode;
	}

	/**
	 * Sets the value of the invoiceRecipientOrganisationTaxCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInvoiceRecipientOrganisationTaxCode(String value) {
		this.invoiceRecipientOrganisationTaxCode = value;
	}

	/**
	 * Gets the value of the invoiceRecipientCode property.
	 * 
	 * @return possible object is {@link PartyIdentifierType }
	 * 
	 */
	public PartyIdentifierType getInvoiceRecipientCode() {
		return invoiceRecipientCode;
	}

	/**
	 * Sets the value of the invoiceRecipientCode property.
	 * 
	 * @param value
	 *            allowed object is {@link PartyIdentifierType }
	 * 
	 */
	public void setInvoiceRecipientCode(PartyIdentifierType value) {
		this.invoiceRecipientCode = value;
	}

	/**
	 * Gets the value of the invoiceRecipientPostalAddressDetails property.
	 * 
	 * @return possible object is
	 *         {@link InvoiceRecipientPostalAddressDetailsType }
	 * 
	 */
	public InvoiceRecipientPostalAddressDetailsType getInvoiceRecipientPostalAddressDetails() {
		return invoiceRecipientPostalAddressDetails;
	}

	/**
	 * Sets the value of the invoiceRecipientPostalAddressDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link InvoiceRecipientPostalAddressDetailsType }
	 * 
	 */
	public void setInvoiceRecipientPostalAddressDetails(
			InvoiceRecipientPostalAddressDetailsType value) {
		this.invoiceRecipientPostalAddressDetails = value;
	}

}
