//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for InvoiceRecipientDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceRecipientDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceRecipientAddress" type="{}genericStringType1_35"/>
 *         &lt;element name="InvoiceRecipientIntermediatorAddress" type="{}genericNMtokenType8_11"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceRecipientDetailsType", propOrder = {
		"invoiceRecipientAddress", "invoiceRecipientIntermediatorAddress" })
public class InvoiceRecipientDetailsType {

	@XmlElement(name = "InvoiceRecipientAddress", required = true)
	protected String invoiceRecipientAddress;
	@XmlElement(name = "InvoiceRecipientIntermediatorAddress", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String invoiceRecipientIntermediatorAddress;

	/**
	 * Gets the value of the invoiceRecipientAddress property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInvoiceRecipientAddress() {
		return invoiceRecipientAddress;
	}

	/**
	 * Sets the value of the invoiceRecipientAddress property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInvoiceRecipientAddress(String value) {
		this.invoiceRecipientAddress = value;
	}

	/**
	 * Gets the value of the invoiceRecipientIntermediatorAddress property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInvoiceRecipientIntermediatorAddress() {
		return invoiceRecipientIntermediatorAddress;
	}

	/**
	 * Sets the value of the invoiceRecipientIntermediatorAddress property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInvoiceRecipientIntermediatorAddress(String value) {
		this.invoiceRecipientIntermediatorAddress = value;
	}

}
