//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for InvoiceRecipientCommunicationDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceRecipientCommunicationDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceRecipientPhoneNumberIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="InvoiceRecipientEmailaddressIdentifier" type="{}genericStringType0_70" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceRecipientCommunicationDetailsType", propOrder = {
		"invoiceRecipientPhoneNumberIdentifier",
		"invoiceRecipientEmailaddressIdentifier" })
public class InvoiceRecipientCommunicationDetailsType {

	@XmlElement(name = "InvoiceRecipientPhoneNumberIdentifier")
	protected String invoiceRecipientPhoneNumberIdentifier;
	@XmlElement(name = "InvoiceRecipientEmailaddressIdentifier")
	protected String invoiceRecipientEmailaddressIdentifier;

	/**
	 * Gets the value of the invoiceRecipientPhoneNumberIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInvoiceRecipientPhoneNumberIdentifier() {
		return invoiceRecipientPhoneNumberIdentifier;
	}

	/**
	 * Sets the value of the invoiceRecipientPhoneNumberIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInvoiceRecipientPhoneNumberIdentifier(String value) {
		this.invoiceRecipientPhoneNumberIdentifier = value;
	}

	/**
	 * Gets the value of the invoiceRecipientEmailaddressIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInvoiceRecipientEmailaddressIdentifier() {
		return invoiceRecipientEmailaddressIdentifier;
	}

	/**
	 * Sets the value of the invoiceRecipientEmailaddressIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInvoiceRecipientEmailaddressIdentifier(String value) {
		this.invoiceRecipientEmailaddressIdentifier = value;
	}

}
