//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for MessageTransmissionDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="MessageTransmissionDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageSenderDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FromIdentifier" type="{}genericStringType2_35"/>
 *                   &lt;element name="FromIntermediator" type="{}genericStringType2_35"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MessageReceiverDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ToIdentifier" type="{}genericStringType2_35"/>
 *                   &lt;element name="ToIntermediator" type="{}genericStringType2_35"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MessageDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MessageIdentifier" type="{}genericStringType2_48"/>
 *                   &lt;element name="MessageTimeStamp" type="{}genericStringType2_35"/>
 *                   &lt;element name="RefToMessageIdentifier" type="{}genericStringType0_48" minOccurs="0"/>
 *                   &lt;element name="ImplementationCode" type="{}genericStringType0_4" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageTransmissionDetailsType", propOrder = {
		"messageSenderDetails", "messageReceiverDetails", "messageDetails" })
public class MessageTransmissionDetailsType {

	@XmlElement(name = "MessageSenderDetails", required = true)
	protected MessageTransmissionDetailsType.MessageSenderDetails messageSenderDetails;
	@XmlElement(name = "MessageReceiverDetails", required = true)
	protected MessageTransmissionDetailsType.MessageReceiverDetails messageReceiverDetails;
	@XmlElement(name = "MessageDetails", required = true)
	protected MessageTransmissionDetailsType.MessageDetails messageDetails;

	/**
	 * Gets the value of the messageSenderDetails property.
	 * 
	 * @return possible object is
	 *         {@link MessageTransmissionDetailsType.MessageSenderDetails }
	 * 
	 */
	public MessageTransmissionDetailsType.MessageSenderDetails getMessageSenderDetails() {
		return messageSenderDetails;
	}

	/**
	 * Sets the value of the messageSenderDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link MessageTransmissionDetailsType.MessageSenderDetails }
	 * 
	 */
	public void setMessageSenderDetails(
			MessageTransmissionDetailsType.MessageSenderDetails value) {
		this.messageSenderDetails = value;
	}

	/**
	 * Gets the value of the messageReceiverDetails property.
	 * 
	 * @return possible object is
	 *         {@link MessageTransmissionDetailsType.MessageReceiverDetails }
	 * 
	 */
	public MessageTransmissionDetailsType.MessageReceiverDetails getMessageReceiverDetails() {
		return messageReceiverDetails;
	}

	/**
	 * Sets the value of the messageReceiverDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link MessageTransmissionDetailsType.MessageReceiverDetails }
	 * 
	 */
	public void setMessageReceiverDetails(
			MessageTransmissionDetailsType.MessageReceiverDetails value) {
		this.messageReceiverDetails = value;
	}

	/**
	 * Gets the value of the messageDetails property.
	 * 
	 * @return possible object is
	 *         {@link MessageTransmissionDetailsType.MessageDetails }
	 * 
	 */
	public MessageTransmissionDetailsType.MessageDetails getMessageDetails() {
		return messageDetails;
	}

	/**
	 * Sets the value of the messageDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link MessageTransmissionDetailsType.MessageDetails }
	 * 
	 */
	public void setMessageDetails(
			MessageTransmissionDetailsType.MessageDetails value) {
		this.messageDetails = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="MessageIdentifier" type="{}genericStringType2_48"/>
	 *         &lt;element name="MessageTimeStamp" type="{}genericStringType2_35"/>
	 *         &lt;element name="RefToMessageIdentifier" type="{}genericStringType0_48" minOccurs="0"/>
	 *         &lt;element name="ImplementationCode" type="{}genericStringType0_4" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "messageIdentifier", "messageTimeStamp",
			"refToMessageIdentifier", "implementationCode" })
	public static class MessageDetails {

		@XmlElement(name = "MessageIdentifier", required = true)
		protected String messageIdentifier;
		@XmlElement(name = "MessageTimeStamp", required = true)
		protected String messageTimeStamp;
		@XmlElement(name = "RefToMessageIdentifier")
		protected String refToMessageIdentifier;
		@XmlElement(name = "ImplementationCode")
		protected String implementationCode;

		/**
		 * Gets the value of the messageIdentifier property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getMessageIdentifier() {
			return messageIdentifier;
		}

		/**
		 * Sets the value of the messageIdentifier property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setMessageIdentifier(String value) {
			this.messageIdentifier = value;
		}

		/**
		 * Gets the value of the messageTimeStamp property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getMessageTimeStamp() {
			return messageTimeStamp;
		}

		/**
		 * Sets the value of the messageTimeStamp property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setMessageTimeStamp(String value) {
			this.messageTimeStamp = value;
		}

		/**
		 * Gets the value of the refToMessageIdentifier property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRefToMessageIdentifier() {
			return refToMessageIdentifier;
		}

		/**
		 * Sets the value of the refToMessageIdentifier property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRefToMessageIdentifier(String value) {
			this.refToMessageIdentifier = value;
		}

		/**
		 * Gets the value of the implementationCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getImplementationCode() {
			return implementationCode;
		}

		/**
		 * Sets the value of the implementationCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setImplementationCode(String value) {
			this.implementationCode = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="ToIdentifier" type="{}genericStringType2_35"/>
	 *         &lt;element name="ToIntermediator" type="{}genericStringType2_35"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "toIdentifier", "toIntermediator" })
	public static class MessageReceiverDetails {

		@XmlElement(name = "ToIdentifier", required = true)
		protected String toIdentifier;
		@XmlElement(name = "ToIntermediator", required = true)
		protected String toIntermediator;

		/**
		 * Gets the value of the toIdentifier property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getToIdentifier() {
			return toIdentifier;
		}

		/**
		 * Sets the value of the toIdentifier property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setToIdentifier(String value) {
			this.toIdentifier = value;
		}

		/**
		 * Gets the value of the toIntermediator property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getToIntermediator() {
			return toIntermediator;
		}

		/**
		 * Sets the value of the toIntermediator property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setToIntermediator(String value) {
			this.toIntermediator = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="FromIdentifier" type="{}genericStringType2_35"/>
	 *         &lt;element name="FromIntermediator" type="{}genericStringType2_35"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "fromIdentifier", "fromIntermediator" })
	public static class MessageSenderDetails {

		@XmlElement(name = "FromIdentifier", required = true)
		protected String fromIdentifier;
		@XmlElement(name = "FromIntermediator", required = true)
		protected String fromIntermediator;

		/**
		 * Gets the value of the fromIdentifier property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFromIdentifier() {
			return fromIdentifier;
		}

		/**
		 * Sets the value of the fromIdentifier property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFromIdentifier(String value) {
			this.fromIdentifier = value;
		}

		/**
		 * Gets the value of the fromIntermediator property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFromIntermediator() {
			return fromIntermediator;
		}

		/**
		 * Sets the value of the fromIntermediator property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFromIntermediator(String value) {
			this.fromIntermediator = value;
		}

	}

}
