//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link InvoiceTypeCodeType }
	 * 
	 */
	public InvoiceTypeCodeType createInvoiceTypeCodeType() {
		return new InvoiceTypeCodeType();
	}

	/**
	 * Create an instance of {@link PaymentTermsDetailsType }
	 * 
	 */
	public PaymentTermsDetailsType createPaymentTermsDetailsType() {
		return new PaymentTermsDetailsType();
	}

	/**
	 * Create an instance of {@link VatSpecificationDetailsType }
	 * 
	 */
	public VatSpecificationDetailsType createVatSpecificationDetailsType() {
		return new VatSpecificationDetailsType();
	}

	/**
	 * Create an instance of {@link InvoiceRowType.RowDefinitionDetails }
	 * 
	 */
	public InvoiceRowType.RowDefinitionDetails createInvoiceRowTypeRowDefinitionDetails() {
		return new InvoiceRowType.RowDefinitionDetails();
	}

	/**
	 * Create an instance of {@link InvoiceRecipientDetailsType }
	 * 
	 */
	public InvoiceRecipientDetailsType createInvoiceRecipientDetailsType() {
		return new InvoiceRecipientDetailsType();
	}

	/**
	 * Create an instance of
	 * {@link InvoiceDetailsType.DefinitionDetails.DefinitionHeaderText }
	 * 
	 */
	public InvoiceDetailsType.DefinitionDetails.DefinitionHeaderText createInvoiceDetailsTypeDefinitionDetailsDefinitionHeaderText() {
		return new InvoiceDetailsType.DefinitionDetails.DefinitionHeaderText();
	}

	/**
	 * Create an instance of {@link BuyerPostalAddressDetailsType }
	 * 
	 */
	public BuyerPostalAddressDetailsType createBuyerPostalAddressDetailsType() {
		return new BuyerPostalAddressDetailsType();
	}

	/**
	 * Create an instance of
	 * {@link DeliveryDetailsType.ShipmentPartyDetails.ShipmentPostalAddressDetails }
	 * 
	 */
	public DeliveryDetailsType.ShipmentPartyDetails.ShipmentPostalAddressDetails createDeliveryDetailsTypeShipmentPartyDetailsShipmentPostalAddressDetails() {
		return new DeliveryDetailsType.ShipmentPartyDetails.ShipmentPostalAddressDetails();
	}

	/**
	 * Create an instance of
	 * {@link InvoiceRowType.RowProgressiveDiscountDetails }
	 * 
	 */
	public InvoiceRowType.RowProgressiveDiscountDetails createInvoiceRowTypeRowProgressiveDiscountDetails() {
		return new InvoiceRowType.RowProgressiveDiscountDetails();
	}

	/**
	 * Create an instance of {@link InvoiceDetailsType }
	 * 
	 */
	public InvoiceDetailsType createInvoiceDetailsType() {
		return new InvoiceDetailsType();
	}

	/**
	 * Create an instance of {@link SellerPostalAddressDetailsType }
	 * 
	 */
	public SellerPostalAddressDetailsType createSellerPostalAddressDetailsType() {
		return new SellerPostalAddressDetailsType();
	}

	/**
	 * Create an instance of {@link RowDeliveryDetailsType }
	 * 
	 */
	public RowDeliveryDetailsType createRowDeliveryDetailsType() {
		return new RowDeliveryDetailsType();
	}

	/**
	 * Create an instance of {@link FactoringAgreementDetailsType }
	 * 
	 */
	public FactoringAgreementDetailsType createFactoringAgreementDetailsType() {
		return new FactoringAgreementDetailsType();
	}

	/**
	 * Create an instance of {@link DeliveryPostalAddressDetailsType }
	 * 
	 */
	public DeliveryPostalAddressDetailsType createDeliveryPostalAddressDetailsType() {
		return new DeliveryPostalAddressDetailsType();
	}

	/**
	 * Create an instance of {@link RowDeliveryDetailsType.RowPackageDetails }
	 * 
	 */
	public RowDeliveryDetailsType.RowPackageDetails createRowDeliveryDetailsTypeRowPackageDetails() {
		return new RowDeliveryDetailsType.RowPackageDetails();
	}

	/**
	 * Create an instance of {@link InvoiceRowType.RowOverDuePaymentDetails }
	 * 
	 */
	public InvoiceRowType.RowOverDuePaymentDetails createInvoiceRowTypeRowOverDuePaymentDetails() {
		return new InvoiceRowType.RowOverDuePaymentDetails();
	}

	/**
	 * Create an instance of {@link DeliveryDetailsType.PackageDetails }
	 * 
	 */
	public DeliveryDetailsType.PackageDetails createDeliveryDetailsTypePackageDetails() {
		return new DeliveryDetailsType.PackageDetails();
	}

	/**
	 * Create an instance of {@link InvoiceRowType }
	 * 
	 */
	public InvoiceRowType createInvoiceRowType() {
		return new InvoiceRowType();
	}

	/**
	 * Create an instance of {@link SellerCommunicationDetailsType }
	 * 
	 */
	public SellerCommunicationDetailsType createSellerCommunicationDetailsType() {
		return new SellerCommunicationDetailsType();
	}

	/**
	 * Create an instance of {@link PaymentStatusDetailsType }
	 * 
	 */
	public PaymentStatusDetailsType createPaymentStatusDetailsType() {
		return new PaymentStatusDetailsType();
	}

	/**
	 * Create an instance of {@link InvoiceRowType.RowAnyPartyDetails }
	 * 
	 */
	public InvoiceRowType.RowAnyPartyDetails createInvoiceRowTypeRowAnyPartyDetails() {
		return new InvoiceRowType.RowAnyPartyDetails();
	}

	/**
	 * Create an instance of {@link Amount }
	 * 
	 */
	public Amount createAmount() {
		return new Amount();
	}

	/**
	 * Create an instance of {@link InvoiceRecipientCommunicationDetailsType }
	 * 
	 */
	public InvoiceRecipientCommunicationDetailsType createInvoiceRecipientCommunicationDetailsType() {
		return new InvoiceRecipientCommunicationDetailsType();
	}

	/**
	 * Create an instance of {@link AnyPartyDetailsType }
	 * 
	 */
	public AnyPartyDetailsType createAnyPartyDetailsType() {
		return new AnyPartyDetailsType();
	}

	/**
	 * Create an instance of {@link EpiPartyDetailsType }
	 * 
	 */
	public EpiPartyDetailsType createEpiPartyDetailsType() {
		return new EpiPartyDetailsType();
	}

	/**
	 * Create an instance of {@link PaymentOverDueFineDetailsType }
	 * 
	 */
	public PaymentOverDueFineDetailsType createPaymentOverDueFineDetailsType() {
		return new PaymentOverDueFineDetailsType();
	}

	/**
	 * Create an instance of {@link MessageTransmissionDetailsType }
	 * 
	 */
	public MessageTransmissionDetailsType createMessageTransmissionDetailsType() {
		return new MessageTransmissionDetailsType();
	}

	/**
	 * Create an instance of
	 * {@link SubInvoiceRowType.SubRowProgressiveDiscountDetails }
	 * 
	 */
	public SubInvoiceRowType.SubRowProgressiveDiscountDetails createSubInvoiceRowTypeSubRowProgressiveDiscountDetails() {
		return new SubInvoiceRowType.SubRowProgressiveDiscountDetails();
	}

	/**
	 * Create an instance of {@link EpiIdentificationDetailsType }
	 * 
	 */
	public EpiIdentificationDetailsType createEpiIdentificationDetailsType() {
		return new EpiIdentificationDetailsType();
	}

	/**
	 * Create an instance of {@link SellerAccountDetailsType }
	 * 
	 */
	public SellerAccountDetailsType createSellerAccountDetailsType() {
		return new SellerAccountDetailsType();
	}

	/**
	 * Create an instance of {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 createQuantityType014() {
		return new QuantityType014();
	}

	/**
	 * Create an instance of {@link SubInvoiceRowType }
	 * 
	 */
	public SubInvoiceRowType createSubInvoiceRowType() {
		return new SubInvoiceRowType();
	}

	/**
	 * Create an instance of {@link PartialPaymentDetailsType }
	 * 
	 */
	public PartialPaymentDetailsType createPartialPaymentDetailsType() {
		return new PartialPaymentDetailsType();
	}

	/**
	 * Create an instance of {@link EpiPaymentInstructionDetailsType }
	 * 
	 */
	public EpiPaymentInstructionDetailsType createEpiPaymentInstructionDetailsType() {
		return new EpiPaymentInstructionDetailsType();
	}

	/**
	 * Create an instance of
	 * {@link MessageTransmissionDetailsType.MessageSenderDetails }
	 * 
	 */
	public MessageTransmissionDetailsType.MessageSenderDetails createMessageTransmissionDetailsTypeMessageSenderDetails() {
		return new MessageTransmissionDetailsType.MessageSenderDetails();
	}

	/**
	 * Create an instance of {@link QuantityType }
	 * 
	 */
	public QuantityType createQuantityType() {
		return new QuantityType();
	}

	/**
	 * Create an instance of
	 * {@link MessageTransmissionDetailsType.MessageReceiverDetails }
	 * 
	 */
	public MessageTransmissionDetailsType.MessageReceiverDetails createMessageTransmissionDetailsTypeMessageReceiverDetails() {
		return new MessageTransmissionDetailsType.MessageReceiverDetails();
	}

	/**
	 * Create an instance of
	 * {@link InvoiceRowType.RowDefinitionDetails.RowDefinitionHeaderText }
	 * 
	 */
	public InvoiceRowType.RowDefinitionDetails.RowDefinitionHeaderText createInvoiceRowTypeRowDefinitionDetailsRowDefinitionHeaderText() {
		return new InvoiceRowType.RowDefinitionDetails.RowDefinitionHeaderText();
	}

	/**
	 * Create an instance of {@link InvoiceSenderPartyDetailsType }
	 * 
	 */
	public InvoiceSenderPartyDetailsType createInvoiceSenderPartyDetailsType() {
		return new InvoiceSenderPartyDetailsType();
	}

	/**
	 * Create an instance of
	 * {@link MessageTransmissionDetailsType.MessageDetails }
	 * 
	 */
	public MessageTransmissionDetailsType.MessageDetails createMessageTransmissionDetailsTypeMessageDetails() {
		return new MessageTransmissionDetailsType.MessageDetails();
	}

	/**
	 * Create an instance of {@link DeliveryPeriodDetailsType }
	 * 
	 */
	public DeliveryPeriodDetailsType createDeliveryPeriodDetailsType() {
		return new DeliveryPeriodDetailsType();
	}

	/**
	 * Create an instance of {@link DiscountDetailsType }
	 * 
	 */
	public DiscountDetailsType createDiscountDetailsType() {
		return new DiscountDetailsType();
	}

	/**
	 * Create an instance of {@link SellerPartyDetailsType }
	 * 
	 */
	public SellerPartyDetailsType createSellerPartyDetailsType() {
		return new SellerPartyDetailsType();
	}

	/**
	 * Create an instance of
	 * {@link SellerInformationDetailsType.SellerOfficialPostalAddressDetails }
	 * 
	 */
	public SellerInformationDetailsType.SellerOfficialPostalAddressDetails createSellerInformationDetailsTypeSellerOfficialPostalAddressDetails() {
		return new SellerInformationDetailsType.SellerOfficialPostalAddressDetails();
	}

	/**
	 * Create an instance of {@link Finvoice }
	 * 
	 */
	public Finvoice createFinvoice() {
		return new Finvoice();
	}

	/**
	 * Create an instance of {@link EpiAccountIDType }
	 * 
	 */
	public EpiAccountIDType createEpiAccountIDType() {
		return new EpiAccountIDType();
	}

	/**
	 * Create an instance of {@link PartyIdentifierType }
	 * 
	 */
	public PartyIdentifierType createPartyIdentifierType() {
		return new PartyIdentifierType();
	}

	/**
	 * Create an instance of {@link EpiChargeType }
	 * 
	 */
	public EpiChargeType createEpiChargeType() {
		return new EpiChargeType();
	}

	/**
	 * Create an instance of {@link TransactionDetailsType }
	 * 
	 */
	public TransactionDetailsType createTransactionDetailsType() {
		return new TransactionDetailsType();
	}

	/**
	 * Create an instance of
	 * {@link SubInvoiceRowType.SubRowOverDuePaymentDetails }
	 * 
	 */
	public SubInvoiceRowType.SubRowOverDuePaymentDetails createSubInvoiceRowTypeSubRowOverDuePaymentDetails() {
		return new SubInvoiceRowType.SubRowOverDuePaymentDetails();
	}

	/**
	 * Create an instance of {@link UnitAmount }
	 * 
	 */
	public UnitAmount createUnitAmount() {
		return new UnitAmount();
	}

	/**
	 * Create an instance of {@link BuyerPartyDetailsType }
	 * 
	 */
	public BuyerPartyDetailsType createBuyerPartyDetailsType() {
		return new BuyerPartyDetailsType();
	}

	/**
	 * Create an instance of {@link Date }
	 * 
	 */
	public Date createDate() {
		return new Date();
	}

	/**
	 * Create an instance of {@link CustomsInfoType }
	 * 
	 */
	public CustomsInfoType createCustomsInfoType() {
		return new CustomsInfoType();
	}

	/**
	 * Create an instance of {@link AnyPartyTextType }
	 * 
	 */
	public AnyPartyTextType createAnyPartyTextType() {
		return new AnyPartyTextType();
	}

	/**
	 * Create an instance of {@link AttachmentMessageDetailsType }
	 * 
	 */
	public AttachmentMessageDetailsType createAttachmentMessageDetailsType() {
		return new AttachmentMessageDetailsType();
	}

	/**
	 * Create an instance of {@link SubInvoiceRowType.SubRowAnyPartyDetails }
	 * 
	 */
	public SubInvoiceRowType.SubRowAnyPartyDetails createSubInvoiceRowTypeSubRowAnyPartyDetails() {
		return new SubInvoiceRowType.SubRowAnyPartyDetails();
	}

	/**
	 * Create an instance of
	 * {@link SubInvoiceRowType.SubRowDefinitionDetails.SubRowDefinitionHeaderText }
	 * 
	 */
	public SubInvoiceRowType.SubRowDefinitionDetails.SubRowDefinitionHeaderText createSubInvoiceRowTypeSubRowDefinitionDetailsSubRowDefinitionHeaderText() {
		return new SubInvoiceRowType.SubRowDefinitionDetails.SubRowDefinitionHeaderText();
	}

	/**
	 * Create an instance of {@link AnyPartyCommunicationDetailsType }
	 * 
	 */
	public AnyPartyCommunicationDetailsType createAnyPartyCommunicationDetailsType() {
		return new AnyPartyCommunicationDetailsType();
	}

	/**
	 * Create an instance of
	 * {@link FactoringAgreementDetailsType.FactoringPartyPostalAddressDetails }
	 * 
	 */
	public FactoringAgreementDetailsType.FactoringPartyPostalAddressDetails createFactoringAgreementDetailsTypeFactoringPartyPostalAddressDetails() {
		return new FactoringAgreementDetailsType.FactoringPartyPostalAddressDetails();
	}

	/**
	 * Create an instance of {@link EpiRemittanceInfoIdentifierType }
	 * 
	 */
	public EpiRemittanceInfoIdentifierType createEpiRemittanceInfoIdentifierType() {
		return new EpiRemittanceInfoIdentifierType();
	}

	/**
	 * Create an instance of {@link BuyerCommunicationDetailsType }
	 * 
	 */
	public BuyerCommunicationDetailsType createBuyerCommunicationDetailsType() {
		return new BuyerCommunicationDetailsType();
	}

	/**
	 * Create an instance of {@link SellerBicType }
	 * 
	 */
	public SellerBicType createSellerBicType() {
		return new SellerBicType();
	}

	/**
	 * Create an instance of {@link EpiBfiIdentifierType }
	 * 
	 */
	public EpiBfiIdentifierType createEpiBfiIdentifierType() {
		return new EpiBfiIdentifierType();
	}

	/**
	 * Create an instance of {@link EpiAmount }
	 * 
	 */
	public EpiAmount createEpiAmount() {
		return new EpiAmount();
	}

	/**
	 * Create an instance of
	 * {@link InvoiceRowType.RowAnyPartyDetails.RowAnyPartyPostalAddressDetails }
	 * 
	 */
	public InvoiceRowType.RowAnyPartyDetails.RowAnyPartyPostalAddressDetails createInvoiceRowTypeRowAnyPartyDetailsRowAnyPartyPostalAddressDetails() {
		return new InvoiceRowType.RowAnyPartyDetails.RowAnyPartyPostalAddressDetails();
	}

	/**
	 * Create an instance of {@link InvoiceRecipientPartyDetailsType }
	 * 
	 */
	public InvoiceRecipientPartyDetailsType createInvoiceRecipientPartyDetailsType() {
		return new InvoiceRecipientPartyDetailsType();
	}

	/**
	 * Create an instance of {@link DeliveryCommunicationDetailsType }
	 * 
	 */
	public DeliveryCommunicationDetailsType createDeliveryCommunicationDetailsType() {
		return new DeliveryCommunicationDetailsType();
	}

	/**
	 * Create an instance of
	 * {@link AnyPartyDetailsType.AnyPartyPostalAddressDetails }
	 * 
	 */
	public AnyPartyDetailsType.AnyPartyPostalAddressDetails createAnyPartyDetailsTypeAnyPartyPostalAddressDetails() {
		return new AnyPartyDetailsType.AnyPartyPostalAddressDetails();
	}

	/**
	 * Create an instance of
	 * {@link SubInvoiceRowType.SubRowAnyPartyDetails.SubRowAnyPartyPostalAddressDetails }
	 * 
	 */
	public SubInvoiceRowType.SubRowAnyPartyDetails.SubRowAnyPartyPostalAddressDetails createSubInvoiceRowTypeSubRowAnyPartyDetailsSubRowAnyPartyPostalAddressDetails() {
		return new SubInvoiceRowType.SubRowAnyPartyDetails.SubRowAnyPartyPostalAddressDetails();
	}

	/**
	 * Create an instance of {@link SellerAccountIDType }
	 * 
	 */
	public SellerAccountIDType createSellerAccountIDType() {
		return new SellerAccountIDType();
	}

	/**
	 * Create an instance of
	 * {@link SubRowDeliveryDetailsType.SubRowPackageDetails }
	 * 
	 */
	public SubRowDeliveryDetailsType.SubRowPackageDetails createSubRowDeliveryDetailsTypeSubRowPackageDetails() {
		return new SubRowDeliveryDetailsType.SubRowPackageDetails();
	}

	/**
	 * Create an instance of {@link InvoiceDetailsType.DefinitionDetails }
	 * 
	 */
	public InvoiceDetailsType.DefinitionDetails createInvoiceDetailsTypeDefinitionDetails() {
		return new InvoiceDetailsType.DefinitionDetails();
	}

	/**
	 * Create an instance of {@link QuantityType070 }
	 * 
	 */
	public QuantityType070 createQuantityType070() {
		return new QuantityType070();
	}

	/**
	 * Create an instance of {@link DeliveryDetailsType.ShipmentPartyDetails }
	 * 
	 */
	public DeliveryDetailsType.ShipmentPartyDetails createDeliveryDetailsTypeShipmentPartyDetails() {
		return new DeliveryDetailsType.ShipmentPartyDetails();
	}

	/**
	 * Create an instance of {@link ExternalSpecificationDetailsType }
	 * 
	 */
	public ExternalSpecificationDetailsType createExternalSpecificationDetailsType() {
		return new ExternalSpecificationDetailsType();
	}

	/**
	 * Create an instance of {@link DeliveryDetailsType }
	 * 
	 */
	public DeliveryDetailsType createDeliveryDetailsType() {
		return new DeliveryDetailsType();
	}

	/**
	 * Create an instance of {@link SubInvoiceRowType.SubRowDefinitionDetails }
	 * 
	 */
	public SubInvoiceRowType.SubRowDefinitionDetails createSubInvoiceRowTypeSubRowDefinitionDetails() {
		return new SubInvoiceRowType.SubRowDefinitionDetails();
	}

	/**
	 * Create an instance of {@link SpecificationDetailsType }
	 * 
	 */
	public SpecificationDetailsType createSpecificationDetailsType() {
		return new SpecificationDetailsType();
	}

	/**
	 * Create an instance of {@link EpiDetailsType }
	 * 
	 */
	public EpiDetailsType createEpiDetailsType() {
		return new EpiDetailsType();
	}

	/**
	 * Create an instance of {@link EpiBeneficiaryPartyDetailsType }
	 * 
	 */
	public EpiBeneficiaryPartyDetailsType createEpiBeneficiaryPartyDetailsType() {
		return new EpiBeneficiaryPartyDetailsType();
	}

	/**
	 * Create an instance of {@link Anypartytexttype035 }
	 * 
	 */
	public Anypartytexttype035 createAnypartytexttype035() {
		return new Anypartytexttype035();
	}

	/**
	 * Create an instance of {@link EpiBfiPartyDetailsType }
	 * 
	 */
	public EpiBfiPartyDetailsType createEpiBfiPartyDetailsType() {
		return new EpiBfiPartyDetailsType();
	}

	/**
	 * Create an instance of
	 * {@link PaymentTermsDetailsType.CashDiscountVatDetails }
	 * 
	 */
	public PaymentTermsDetailsType.CashDiscountVatDetails createPaymentTermsDetailsTypeCashDiscountVatDetails() {
		return new PaymentTermsDetailsType.CashDiscountVatDetails();
	}

	/**
	 * Create an instance of {@link SellerInformationDetailsType }
	 * 
	 */
	public SellerInformationDetailsType createSellerInformationDetailsType() {
		return new SellerInformationDetailsType();
	}

	/**
	 * Create an instance of {@link DeliveryPartyDetailsType }
	 * 
	 */
	public DeliveryPartyDetailsType createDeliveryPartyDetailsType() {
		return new DeliveryPartyDetailsType();
	}

	/**
	 * Create an instance of {@link SubRowDeliveryDetailsType }
	 * 
	 */
	public SubRowDeliveryDetailsType createSubRowDeliveryDetailsType() {
		return new SubRowDeliveryDetailsType();
	}

	/**
	 * Create an instance of {@link InvoiceRecipientPostalAddressDetailsType }
	 * 
	 */
	public InvoiceRecipientPostalAddressDetailsType createInvoiceRecipientPostalAddressDetailsType() {
		return new InvoiceRecipientPostalAddressDetailsType();
	}

}
