//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PartialPaymentDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PartialPaymentDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaidAmount" type="{}amount"/>
 *         &lt;element name="PaidVatExcludedAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="UnPaidAmount" type="{}amount"/>
 *         &lt;element name="UnPaidVatExcludedAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="InterestPercent" type="{}percentage" minOccurs="0"/>
 *         &lt;element name="ProsessingCostsAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="PartialPaymentVatIncludedAmount" type="{}amount" maxOccurs="unbounded"/>
 *         &lt;element name="PartialPaymentVatExcludedAmount" type="{}amount" maxOccurs="unbounded"/>
 *         &lt;element name="PartialPaymentDueDate" type="{}date" maxOccurs="unbounded"/>
 *         &lt;element name="PartialPaymentReferenceIdentifier" type="{}genericStringType2_35" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartialPaymentDetailsType", propOrder = { "paidAmount",
		"paidVatExcludedAmount", "unPaidAmount", "unPaidVatExcludedAmount",
		"interestPercent", "prosessingCostsAmount",
		"partialPaymentVatIncludedAmount", "partialPaymentVatExcludedAmount",
		"partialPaymentDueDate", "partialPaymentReferenceIdentifier" })
public class PartialPaymentDetailsType {

	@XmlElement(name = "PaidAmount", required = true)
	protected Amount paidAmount;
	@XmlElement(name = "PaidVatExcludedAmount")
	protected Amount paidVatExcludedAmount;
	@XmlElement(name = "UnPaidAmount", required = true)
	protected Amount unPaidAmount;
	@XmlElement(name = "UnPaidVatExcludedAmount")
	protected Amount unPaidVatExcludedAmount;
	@XmlElement(name = "InterestPercent")
	protected String interestPercent;
	@XmlElement(name = "ProsessingCostsAmount")
	protected Amount prosessingCostsAmount;
	@XmlElement(name = "PartialPaymentVatIncludedAmount", required = true)
	protected List<Amount> partialPaymentVatIncludedAmount;
	@XmlElement(name = "PartialPaymentVatExcludedAmount", required = true)
	protected List<Amount> partialPaymentVatExcludedAmount;
	@XmlElement(name = "PartialPaymentDueDate", required = true)
	protected List<Date> partialPaymentDueDate;
	@XmlElement(name = "PartialPaymentReferenceIdentifier", required = true)
	protected List<String> partialPaymentReferenceIdentifier;

	/**
	 * Gets the value of the paidAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getPaidAmount() {
		return paidAmount;
	}

	/**
	 * Sets the value of the paidAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setPaidAmount(Amount value) {
		this.paidAmount = value;
	}

	/**
	 * Gets the value of the paidVatExcludedAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getPaidVatExcludedAmount() {
		return paidVatExcludedAmount;
	}

	/**
	 * Sets the value of the paidVatExcludedAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setPaidVatExcludedAmount(Amount value) {
		this.paidVatExcludedAmount = value;
	}

	/**
	 * Gets the value of the unPaidAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getUnPaidAmount() {
		return unPaidAmount;
	}

	/**
	 * Sets the value of the unPaidAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setUnPaidAmount(Amount value) {
		this.unPaidAmount = value;
	}

	/**
	 * Gets the value of the unPaidVatExcludedAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getUnPaidVatExcludedAmount() {
		return unPaidVatExcludedAmount;
	}

	/**
	 * Sets the value of the unPaidVatExcludedAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setUnPaidVatExcludedAmount(Amount value) {
		this.unPaidVatExcludedAmount = value;
	}

	/**
	 * Gets the value of the interestPercent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInterestPercent() {
		return interestPercent;
	}

	/**
	 * Sets the value of the interestPercent property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInterestPercent(String value) {
		this.interestPercent = value;
	}

	/**
	 * Gets the value of the prosessingCostsAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getProsessingCostsAmount() {
		return prosessingCostsAmount;
	}

	/**
	 * Sets the value of the prosessingCostsAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setProsessingCostsAmount(Amount value) {
		this.prosessingCostsAmount = value;
	}

	/**
	 * Gets the value of the partialPaymentVatIncludedAmount property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the partialPaymentVatIncludedAmount property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPartialPaymentVatIncludedAmount().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Amount }
	 * 
	 * 
	 */
	public List<Amount> getPartialPaymentVatIncludedAmount() {
		if (partialPaymentVatIncludedAmount == null) {
			partialPaymentVatIncludedAmount = new ArrayList<Amount>();
		}
		return this.partialPaymentVatIncludedAmount;
	}

	/**
	 * Gets the value of the partialPaymentVatExcludedAmount property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the partialPaymentVatExcludedAmount property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPartialPaymentVatExcludedAmount().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Amount }
	 * 
	 * 
	 */
	public List<Amount> getPartialPaymentVatExcludedAmount() {
		if (partialPaymentVatExcludedAmount == null) {
			partialPaymentVatExcludedAmount = new ArrayList<Amount>();
		}
		return this.partialPaymentVatExcludedAmount;
	}

	/**
	 * Gets the value of the partialPaymentDueDate property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the partialPaymentDueDate property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPartialPaymentDueDate().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Date }
	 * 
	 * 
	 */
	public List<Date> getPartialPaymentDueDate() {
		if (partialPaymentDueDate == null) {
			partialPaymentDueDate = new ArrayList<Date>();
		}
		return this.partialPaymentDueDate;
	}

	/**
	 * Gets the value of the partialPaymentReferenceIdentifier property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the partialPaymentReferenceIdentifier
	 * property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPartialPaymentReferenceIdentifier().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getPartialPaymentReferenceIdentifier() {
		if (partialPaymentReferenceIdentifier == null) {
			partialPaymentReferenceIdentifier = new ArrayList<String>();
		}
		return this.partialPaymentReferenceIdentifier;
	}

}
