//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for SellerPostalAddressDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SellerPostalAddressDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SellerStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
 *         &lt;element name="SellerTownName" type="{}genericStringType2_35"/>
 *         &lt;element name="SellerPostCodeIdentifier" type="{}genericStringType2_35"/>
 *         &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
 *         &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SellerPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellerPostalAddressDetailsType", propOrder = {
		"sellerStreetName", "sellerTownName", "sellerPostCodeIdentifier",
		"countryCode", "countryName", "sellerPostOfficeBoxIdentifier" })
public class SellerPostalAddressDetailsType {

	@XmlElement(name = "SellerStreetName", required = true)
	protected List<String> sellerStreetName;
	@XmlElement(name = "SellerTownName", required = true)
	protected String sellerTownName;
	@XmlElement(name = "SellerPostCodeIdentifier", required = true)
	protected String sellerPostCodeIdentifier;
	@XmlElement(name = "CountryCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String countryCode;
	@XmlElement(name = "CountryName")
	protected String countryName;
	@XmlElement(name = "SellerPostOfficeBoxIdentifier")
	protected String sellerPostOfficeBoxIdentifier;

	/**
	 * Gets the value of the sellerStreetName property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the sellerStreetName property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSellerStreetName().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getSellerStreetName() {
		if (sellerStreetName == null) {
			sellerStreetName = new ArrayList<String>();
		}
		return this.sellerStreetName;
	}

	/**
	 * Gets the value of the sellerTownName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSellerTownName() {
		return sellerTownName;
	}

	/**
	 * Sets the value of the sellerTownName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSellerTownName(String value) {
		this.sellerTownName = value;
	}

	/**
	 * Gets the value of the sellerPostCodeIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSellerPostCodeIdentifier() {
		return sellerPostCodeIdentifier;
	}

	/**
	 * Sets the value of the sellerPostCodeIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSellerPostCodeIdentifier(String value) {
		this.sellerPostCodeIdentifier = value;
	}

	/**
	 * Gets the value of the countryCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountryCode() {
		return countryCode;
	}

	/**
	 * Sets the value of the countryCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountryCode(String value) {
		this.countryCode = value;
	}

	/**
	 * Gets the value of the countryName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountryName() {
		return countryName;
	}

	/**
	 * Sets the value of the countryName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountryName(String value) {
		this.countryName = value;
	}

	/**
	 * Gets the value of the sellerPostOfficeBoxIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSellerPostOfficeBoxIdentifier() {
		return sellerPostOfficeBoxIdentifier;
	}

	/**
	 * Sets the value of the sellerPostOfficeBoxIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSellerPostOfficeBoxIdentifier(String value) {
		this.sellerPostOfficeBoxIdentifier = value;
	}

}
