//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SellerPartyDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SellerPartyDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SellerPartyIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SellerPartyIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="SellerOrganisationName" type="{}genericStringType2_70" maxOccurs="unbounded"/>
 *         &lt;element name="SellerOrganisationDepartment" type="{}genericStringType0_35" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="SellerOrganisationTaxCode" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SellerOrganisationTaxCodeUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="SellerCode" type="{}PartyIdentifierType" minOccurs="0"/>
 *         &lt;element name="SellerPostalAddressDetails" type="{}SellerPostalAddressDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellerPartyDetailsType", propOrder = {
		"sellerPartyIdentifier", "sellerPartyIdentifierUrlText",
		"sellerOrganisationName", "sellerOrganisationDepartment",
		"sellerOrganisationTaxCode", "sellerOrganisationTaxCodeUrlText",
		"sellerCode", "sellerPostalAddressDetails" })
public class SellerPartyDetailsType {

	@XmlElement(name = "SellerPartyIdentifier")
	protected String sellerPartyIdentifier;
	@XmlElement(name = "SellerPartyIdentifierUrlText")
	protected String sellerPartyIdentifierUrlText;
	@XmlElement(name = "SellerOrganisationName", required = true)
	protected List<String> sellerOrganisationName;
	@XmlElement(name = "SellerOrganisationDepartment")
	protected List<String> sellerOrganisationDepartment;
	@XmlElement(name = "SellerOrganisationTaxCode")
	protected String sellerOrganisationTaxCode;
	@XmlElement(name = "SellerOrganisationTaxCodeUrlText")
	protected String sellerOrganisationTaxCodeUrlText;
	@XmlElement(name = "SellerCode")
	protected PartyIdentifierType sellerCode;
	@XmlElement(name = "SellerPostalAddressDetails")
	protected SellerPostalAddressDetailsType sellerPostalAddressDetails;

	/**
	 * Gets the value of the sellerPartyIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSellerPartyIdentifier() {
		return sellerPartyIdentifier;
	}

	/**
	 * Sets the value of the sellerPartyIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSellerPartyIdentifier(String value) {
		this.sellerPartyIdentifier = value;
	}

	/**
	 * Gets the value of the sellerPartyIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSellerPartyIdentifierUrlText() {
		return sellerPartyIdentifierUrlText;
	}

	/**
	 * Sets the value of the sellerPartyIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSellerPartyIdentifierUrlText(String value) {
		this.sellerPartyIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the sellerOrganisationName property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the sellerOrganisationName property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSellerOrganisationName().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getSellerOrganisationName() {
		if (sellerOrganisationName == null) {
			sellerOrganisationName = new ArrayList<String>();
		}
		return this.sellerOrganisationName;
	}

	/**
	 * Gets the value of the sellerOrganisationDepartment property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the sellerOrganisationDepartment property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSellerOrganisationDepartment().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getSellerOrganisationDepartment() {
		if (sellerOrganisationDepartment == null) {
			sellerOrganisationDepartment = new ArrayList<String>();
		}
		return this.sellerOrganisationDepartment;
	}

	/**
	 * Gets the value of the sellerOrganisationTaxCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSellerOrganisationTaxCode() {
		return sellerOrganisationTaxCode;
	}

	/**
	 * Sets the value of the sellerOrganisationTaxCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSellerOrganisationTaxCode(String value) {
		this.sellerOrganisationTaxCode = value;
	}

	/**
	 * Gets the value of the sellerOrganisationTaxCodeUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSellerOrganisationTaxCodeUrlText() {
		return sellerOrganisationTaxCodeUrlText;
	}

	/**
	 * Sets the value of the sellerOrganisationTaxCodeUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSellerOrganisationTaxCodeUrlText(String value) {
		this.sellerOrganisationTaxCodeUrlText = value;
	}

	/**
	 * Gets the value of the sellerCode property.
	 * 
	 * @return possible object is {@link PartyIdentifierType }
	 * 
	 */
	public PartyIdentifierType getSellerCode() {
		return sellerCode;
	}

	/**
	 * Sets the value of the sellerCode property.
	 * 
	 * @param value
	 *            allowed object is {@link PartyIdentifierType }
	 * 
	 */
	public void setSellerCode(PartyIdentifierType value) {
		this.sellerCode = value;
	}

	/**
	 * Gets the value of the sellerPostalAddressDetails property.
	 * 
	 * @return possible object is {@link SellerPostalAddressDetailsType }
	 * 
	 */
	public SellerPostalAddressDetailsType getSellerPostalAddressDetails() {
		return sellerPostalAddressDetails;
	}

	/**
	 * Sets the value of the sellerPostalAddressDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link SellerPostalAddressDetailsType }
	 * 
	 */
	public void setSellerPostalAddressDetails(
			SellerPostalAddressDetailsType value) {
		this.sellerPostalAddressDetails = value;
	}

}
