//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SellerAccountDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SellerAccountDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SellerAccountID" type="{}SellerAccountIDType"/>
 *         &lt;element name="SellerBic" type="{}SellerBicType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellerAccountDetailsType", propOrder = { "sellerAccountID",
		"sellerBic" })
public class SellerAccountDetailsType {

	@XmlElement(name = "SellerAccountID", required = true)
	protected SellerAccountIDType sellerAccountID;
	@XmlElement(name = "SellerBic", required = true)
	protected SellerBicType sellerBic;

	/**
	 * Gets the value of the sellerAccountID property.
	 * 
	 * @return possible object is {@link SellerAccountIDType }
	 * 
	 */
	public SellerAccountIDType getSellerAccountID() {
		return sellerAccountID;
	}

	/**
	 * Sets the value of the sellerAccountID property.
	 * 
	 * @param value
	 *            allowed object is {@link SellerAccountIDType }
	 * 
	 */
	public void setSellerAccountID(SellerAccountIDType value) {
		this.sellerAccountID = value;
	}

	/**
	 * Gets the value of the sellerBic property.
	 * 
	 * @return possible object is {@link SellerBicType }
	 * 
	 */
	public SellerBicType getSellerBic() {
		return sellerBic;
	}

	/**
	 * Sets the value of the sellerBic property.
	 * 
	 * @param value
	 *            allowed object is {@link SellerBicType }
	 * 
	 */
	public void setSellerBic(SellerBicType value) {
		this.sellerBic = value;
	}

}
