//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SpecificationDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SpecificationDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SpecificationFreeText" type="{}genericStringType0_80" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExternalSpecificationDetails" type="{}ExternalSpecificationDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecificationDetailsType", propOrder = {
		"specificationFreeText", "externalSpecificationDetails" })
public class SpecificationDetailsType {

	@XmlElement(name = "SpecificationFreeText")
	protected List<String> specificationFreeText;
	@XmlElement(name = "ExternalSpecificationDetails")
	protected ExternalSpecificationDetailsType externalSpecificationDetails;

	/**
	 * Gets the value of the specificationFreeText property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the specificationFreeText property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSpecificationFreeText().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getSpecificationFreeText() {
		if (specificationFreeText == null) {
			specificationFreeText = new ArrayList<String>();
		}
		return this.specificationFreeText;
	}

	/**
	 * Gets the value of the externalSpecificationDetails property.
	 * 
	 * @return possible object is {@link ExternalSpecificationDetailsType }
	 * 
	 */
	public ExternalSpecificationDetailsType getExternalSpecificationDetails() {
		return externalSpecificationDetails;
	}

	/**
	 * Sets the value of the externalSpecificationDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link ExternalSpecificationDetailsType }
	 * 
	 */
	public void setExternalSpecificationDetails(
			ExternalSpecificationDetailsType value) {
		this.externalSpecificationDetails = value;
	}

}
