//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for SubInvoiceRowType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SubInvoiceRowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowPositionIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubArticleIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubArticleGroupIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubArticleName" type="{}genericStringType0_100" minOccurs="0"/>
 *         &lt;element name="SubArticleInfoUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="SubBuyerArticleIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubEanCode" type="{}genericTokenType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowRegistrationNumberIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubSerialNumberIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowActionCode" type="{}genericTokenType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowDefinitionDetails" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SubRowDefinitionHeaderText">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;>genericStringType0_70">
 *                           &lt;attribute name="DefinitionCode" type="{}genericTokenType1_20" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SubRowDefinitionValue" type="{}QuantityType0_70" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SubOfferedQuantity" type="{}QuantityType0_14" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SubDeliveredQuantity" type="{}QuantityType0_14" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SubOrderedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="SubConfirmedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="SubPostDeliveredQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="SubInvoicedQuantity" type="{}QuantityType0_14" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SubCreditRequestedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="SubReturnedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="SubStartDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="SubEndDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="SubUnitPriceAmount" type="{}unitAmount" minOccurs="0"/>
 *         &lt;element name="SubUnitPriceVatIncludedAmount" type="{}unitAmount" minOccurs="0"/>
 *         &lt;element name="SubUnitPriceBaseQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="SubRowIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="SubRowIdentifierDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="SubRowOrdererName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowSalesPersonName" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowOrderConfirmationIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowOrderConfirmationDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="SubOriginalInvoiceNumber" type="{}genericStringType1_20" minOccurs="0"/>
 *         &lt;element name="SubRowDeliveryIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowDeliveryIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="SubRowDeliveryDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="SubRowQuotationIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowQuotationIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="SubRowAgreementIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowAgreementIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="SubRowRequestOfQuotationIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowRequestOfQuotationIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="SubRowPriceListIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowPriceListIdentifierUrlText" type="{}genericStringType0_512" minOccurs="0"/>
 *         &lt;element name="SubRowProjectReferenceIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowOverDuePaymentDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SubRowOriginalInvoiceIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="SubRowOriginalInvoiceDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="SubRowOriginalDueDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="SubRowOriginalInvoiceTotalAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="SubRowOriginalEpiRemittanceInfoIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="SubRowPaidVatExcludedAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="SubRowPaidVatIncludedAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="SubRowPaidDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="SubRowUnPaidVatExcludedAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="SubRowUnPaidVatIncludedAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="SubRowCollectionDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="SubRowCollectionQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *                   &lt;element name="SubRowCollectionChargeAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="SubRowInterestRate" type="{}percentage" minOccurs="0"/>
 *                   &lt;element name="SubRowInterestStartDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="SubRowInterestEndDate" type="{}date" minOccurs="0"/>
 *                   &lt;element name="SubRowInterestPeriodText" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="SubRowInterestDateNumber" type="{}genericNMtokenType0_14" minOccurs="0"/>
 *                   &lt;element name="SubRowInterestChargeAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="SubRowInterestChargeVatAmount" type="{}amount" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SubRowAnyPartyDetails" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SubRowAnyPartyText" type="{}anypartytexttype0_35"/>
 *                   &lt;element name="SubRowAnyPartyIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="SubRowAnyPartyOrganisationName" type="{}genericStringType2_35" maxOccurs="2"/>
 *                   &lt;element name="SubRowAnyPartyOrganisationDepartment" type="{}genericStringType0_35" maxOccurs="2" minOccurs="0"/>
 *                   &lt;element name="SubRowAnyPartyOrganisationTaxCode" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="SubRowAnyPartyPostalAddressDetails" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="SubRowAnyPartyStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
 *                             &lt;element name="SubRowAnyPartyTownName" type="{}genericStringType2_35"/>
 *                             &lt;element name="SubRowAnyPartyPostCodeIdentifier" type="{}genericStringType2_35"/>
 *                             &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
 *                             &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
 *                             &lt;element name="SubRowAnyPartyPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SubRowAnyPartyOrganisationUnitNumber" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="SubRowAnyPartySiteCode" type="{}genericStringType0_35" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SubRowDeliveryDetails" type="{}SubRowDeliveryDetailsType" minOccurs="0"/>
 *         &lt;element name="SubRowShortProposedAccountIdentifier" type="{}genericStringType0_4" minOccurs="0"/>
 *         &lt;element name="SubRowNormalProposedAccountIdentifier" type="{}genericStringType0_4" minOccurs="0"/>
 *         &lt;element name="SubRowProposedAccountText" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowAccountDimensionText" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowSellerAccountText" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowFreeText" type="{}genericStringType0_512" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SubRowUsedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="SubRowPreviousMeterReadingDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="SubRowLatestMeterReadingDate" type="{}date" minOccurs="0"/>
 *         &lt;element name="SubRowCalculatedQuantity" type="{}QuantityType0_14" minOccurs="0"/>
 *         &lt;element name="SubRowAveragePriceAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="SubRowDiscountPercent" type="{}percentage" minOccurs="0"/>
 *         &lt;element name="SubRowDiscountAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="SubRowDiscountTypeCode" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowDiscountTypeText" type="{}genericStringType0_35" minOccurs="0"/>
 *         &lt;element name="SubRowProgressiveDiscountDetails" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SubRowDiscountPercent" type="{}percentage" minOccurs="0"/>
 *                   &lt;element name="SubRowDiscountAmount" type="{}amount" minOccurs="0"/>
 *                   &lt;element name="SubRowDiscountTypeCode" type="{}genericStringType0_35" minOccurs="0"/>
 *                   &lt;element name="SubRowDiscountTypeText" type="{}genericStringType0_35" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SubRowVatRatePercent" type="{}percentage" minOccurs="0"/>
 *         &lt;element name="SubRowVatCode" type="{}genericStringType0_10" minOccurs="0"/>
 *         &lt;element name="SubRowVatAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="SubRowVatExcludedAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="SubRowAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="SubRowTransactionDetails" type="{}TransactionDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubInvoiceRowType", propOrder = { "subIdentifier",
		"subRowPositionIdentifier", "subArticleIdentifier",
		"subArticleGroupIdentifier", "subArticleName", "subArticleInfoUrlText",
		"subBuyerArticleIdentifier", "subEanCode",
		"subRowRegistrationNumberIdentifier", "subSerialNumberIdentifier",
		"subRowActionCode", "subRowDefinitionDetails", "subOfferedQuantity",
		"subDeliveredQuantity", "subOrderedQuantity", "subConfirmedQuantity",
		"subPostDeliveredQuantity", "subInvoicedQuantity",
		"subCreditRequestedQuantity", "subReturnedQuantity", "subStartDate",
		"subEndDate", "subUnitPriceAmount", "subUnitPriceVatIncludedAmount",
		"subUnitPriceBaseQuantity", "subRowIdentifier",
		"subRowIdentifierUrlText", "subRowIdentifierDate", "subRowOrdererName",
		"subRowSalesPersonName", "subRowOrderConfirmationIdentifier",
		"subRowOrderConfirmationDate", "subOriginalInvoiceNumber",
		"subRowDeliveryIdentifier", "subRowDeliveryIdentifierUrlText",
		"subRowDeliveryDate", "subRowQuotationIdentifier",
		"subRowQuotationIdentifierUrlText", "subRowAgreementIdentifier",
		"subRowAgreementIdentifierUrlText",
		"subRowRequestOfQuotationIdentifier",
		"subRowRequestOfQuotationIdentifierUrlText",
		"subRowPriceListIdentifier", "subRowPriceListIdentifierUrlText",
		"subRowProjectReferenceIdentifier", "subRowOverDuePaymentDetails",
		"subRowAnyPartyDetails", "subRowDeliveryDetails",
		"subRowShortProposedAccountIdentifier",
		"subRowNormalProposedAccountIdentifier", "subRowProposedAccountText",
		"subRowAccountDimensionText", "subRowSellerAccountText",
		"subRowFreeText", "subRowUsedQuantity",
		"subRowPreviousMeterReadingDate", "subRowLatestMeterReadingDate",
		"subRowCalculatedQuantity", "subRowAveragePriceAmount",
		"subRowDiscountPercent", "subRowDiscountAmount",
		"subRowDiscountTypeCode", "subRowDiscountTypeText",
		"subRowProgressiveDiscountDetails", "subRowVatRatePercent",
		"subRowVatCode", "subRowVatAmount", "subRowVatExcludedAmount",
		"subRowAmount", "subRowTransactionDetails" })
public class SubInvoiceRowType {

	@XmlElement(name = "SubIdentifier")
	protected String subIdentifier;
	@XmlElement(name = "SubRowPositionIdentifier")
	protected String subRowPositionIdentifier;
	@XmlElement(name = "SubArticleIdentifier")
	protected String subArticleIdentifier;
	@XmlElement(name = "SubArticleGroupIdentifier")
	protected String subArticleGroupIdentifier;
	@XmlElement(name = "SubArticleName")
	protected String subArticleName;
	@XmlElement(name = "SubArticleInfoUrlText")
	protected String subArticleInfoUrlText;
	@XmlElement(name = "SubBuyerArticleIdentifier")
	protected String subBuyerArticleIdentifier;
	@XmlElement(name = "SubEanCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String subEanCode;
	@XmlElement(name = "SubRowRegistrationNumberIdentifier")
	protected String subRowRegistrationNumberIdentifier;
	@XmlElement(name = "SubSerialNumberIdentifier")
	protected String subSerialNumberIdentifier;
	@XmlElement(name = "SubRowActionCode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String subRowActionCode;
	@XmlElement(name = "SubRowDefinitionDetails")
	protected List<SubInvoiceRowType.SubRowDefinitionDetails> subRowDefinitionDetails;
	@XmlElement(name = "SubOfferedQuantity")
	protected List<QuantityType014> subOfferedQuantity;
	@XmlElement(name = "SubDeliveredQuantity")
	protected List<QuantityType014> subDeliveredQuantity;
	@XmlElement(name = "SubOrderedQuantity")
	protected QuantityType014 subOrderedQuantity;
	@XmlElement(name = "SubConfirmedQuantity")
	protected QuantityType014 subConfirmedQuantity;
	@XmlElement(name = "SubPostDeliveredQuantity")
	protected QuantityType014 subPostDeliveredQuantity;
	@XmlElement(name = "SubInvoicedQuantity")
	protected List<QuantityType014> subInvoicedQuantity;
	@XmlElement(name = "SubCreditRequestedQuantity")
	protected QuantityType014 subCreditRequestedQuantity;
	@XmlElement(name = "SubReturnedQuantity")
	protected QuantityType014 subReturnedQuantity;
	@XmlElement(name = "SubStartDate")
	protected Date subStartDate;
	@XmlElement(name = "SubEndDate")
	protected Date subEndDate;
	@XmlElement(name = "SubUnitPriceAmount")
	protected UnitAmount subUnitPriceAmount;
	@XmlElement(name = "SubUnitPriceVatIncludedAmount")
	protected UnitAmount subUnitPriceVatIncludedAmount;
	@XmlElement(name = "SubUnitPriceBaseQuantity")
	protected QuantityType014 subUnitPriceBaseQuantity;
	@XmlElement(name = "SubRowIdentifier")
	protected String subRowIdentifier;
	@XmlElement(name = "SubRowIdentifierUrlText")
	protected String subRowIdentifierUrlText;
	@XmlElement(name = "SubRowIdentifierDate")
	protected Date subRowIdentifierDate;
	@XmlElement(name = "SubRowOrdererName")
	protected String subRowOrdererName;
	@XmlElement(name = "SubRowSalesPersonName")
	protected String subRowSalesPersonName;
	@XmlElement(name = "SubRowOrderConfirmationIdentifier")
	protected String subRowOrderConfirmationIdentifier;
	@XmlElement(name = "SubRowOrderConfirmationDate")
	protected Date subRowOrderConfirmationDate;
	@XmlElement(name = "SubOriginalInvoiceNumber")
	protected String subOriginalInvoiceNumber;
	@XmlElement(name = "SubRowDeliveryIdentifier")
	protected String subRowDeliveryIdentifier;
	@XmlElement(name = "SubRowDeliveryIdentifierUrlText")
	protected String subRowDeliveryIdentifierUrlText;
	@XmlElement(name = "SubRowDeliveryDate")
	protected Date subRowDeliveryDate;
	@XmlElement(name = "SubRowQuotationIdentifier")
	protected String subRowQuotationIdentifier;
	@XmlElement(name = "SubRowQuotationIdentifierUrlText")
	protected String subRowQuotationIdentifierUrlText;
	@XmlElement(name = "SubRowAgreementIdentifier")
	protected String subRowAgreementIdentifier;
	@XmlElement(name = "SubRowAgreementIdentifierUrlText")
	protected String subRowAgreementIdentifierUrlText;
	@XmlElement(name = "SubRowRequestOfQuotationIdentifier")
	protected String subRowRequestOfQuotationIdentifier;
	@XmlElement(name = "SubRowRequestOfQuotationIdentifierUrlText")
	protected String subRowRequestOfQuotationIdentifierUrlText;
	@XmlElement(name = "SubRowPriceListIdentifier")
	protected String subRowPriceListIdentifier;
	@XmlElement(name = "SubRowPriceListIdentifierUrlText")
	protected String subRowPriceListIdentifierUrlText;
	@XmlElement(name = "SubRowProjectReferenceIdentifier")
	protected String subRowProjectReferenceIdentifier;
	@XmlElement(name = "SubRowOverDuePaymentDetails")
	protected SubInvoiceRowType.SubRowOverDuePaymentDetails subRowOverDuePaymentDetails;
	@XmlElement(name = "SubRowAnyPartyDetails")
	protected List<SubInvoiceRowType.SubRowAnyPartyDetails> subRowAnyPartyDetails;
	@XmlElement(name = "SubRowDeliveryDetails")
	protected SubRowDeliveryDetailsType subRowDeliveryDetails;
	@XmlElement(name = "SubRowShortProposedAccountIdentifier")
	protected String subRowShortProposedAccountIdentifier;
	@XmlElement(name = "SubRowNormalProposedAccountIdentifier")
	protected String subRowNormalProposedAccountIdentifier;
	@XmlElement(name = "SubRowProposedAccountText")
	protected String subRowProposedAccountText;
	@XmlElement(name = "SubRowAccountDimensionText")
	protected String subRowAccountDimensionText;
	@XmlElement(name = "SubRowSellerAccountText")
	protected String subRowSellerAccountText;
	@XmlElement(name = "SubRowFreeText")
	protected List<String> subRowFreeText;
	@XmlElement(name = "SubRowUsedQuantity")
	protected QuantityType014 subRowUsedQuantity;
	@XmlElement(name = "SubRowPreviousMeterReadingDate")
	protected Date subRowPreviousMeterReadingDate;
	@XmlElement(name = "SubRowLatestMeterReadingDate")
	protected Date subRowLatestMeterReadingDate;
	@XmlElement(name = "SubRowCalculatedQuantity")
	protected QuantityType014 subRowCalculatedQuantity;
	@XmlElement(name = "SubRowAveragePriceAmount")
	protected Amount subRowAveragePriceAmount;
	@XmlElement(name = "SubRowDiscountPercent")
	protected String subRowDiscountPercent;
	@XmlElement(name = "SubRowDiscountAmount")
	protected Amount subRowDiscountAmount;
	@XmlElement(name = "SubRowDiscountTypeCode")
	protected String subRowDiscountTypeCode;
	@XmlElement(name = "SubRowDiscountTypeText")
	protected String subRowDiscountTypeText;
	@XmlElement(name = "SubRowProgressiveDiscountDetails")
	protected List<SubInvoiceRowType.SubRowProgressiveDiscountDetails> subRowProgressiveDiscountDetails;
	@XmlElement(name = "SubRowVatRatePercent")
	protected String subRowVatRatePercent;
	@XmlElement(name = "SubRowVatCode")
	protected String subRowVatCode;
	@XmlElement(name = "SubRowVatAmount")
	protected Amount subRowVatAmount;
	@XmlElement(name = "SubRowVatExcludedAmount")
	protected Amount subRowVatExcludedAmount;
	@XmlElement(name = "SubRowAmount")
	protected Amount subRowAmount;
	@XmlElement(name = "SubRowTransactionDetails")
	protected TransactionDetailsType subRowTransactionDetails;

	/**
	 * Gets the value of the subIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubIdentifier() {
		return subIdentifier;
	}

	/**
	 * Sets the value of the subIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubIdentifier(String value) {
		this.subIdentifier = value;
	}

	/**
	 * Gets the value of the subRowPositionIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowPositionIdentifier() {
		return subRowPositionIdentifier;
	}

	/**
	 * Sets the value of the subRowPositionIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowPositionIdentifier(String value) {
		this.subRowPositionIdentifier = value;
	}

	/**
	 * Gets the value of the subArticleIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubArticleIdentifier() {
		return subArticleIdentifier;
	}

	/**
	 * Sets the value of the subArticleIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubArticleIdentifier(String value) {
		this.subArticleIdentifier = value;
	}

	/**
	 * Gets the value of the subArticleGroupIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubArticleGroupIdentifier() {
		return subArticleGroupIdentifier;
	}

	/**
	 * Sets the value of the subArticleGroupIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubArticleGroupIdentifier(String value) {
		this.subArticleGroupIdentifier = value;
	}

	/**
	 * Gets the value of the subArticleName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubArticleName() {
		return subArticleName;
	}

	/**
	 * Sets the value of the subArticleName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubArticleName(String value) {
		this.subArticleName = value;
	}

	/**
	 * Gets the value of the subArticleInfoUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubArticleInfoUrlText() {
		return subArticleInfoUrlText;
	}

	/**
	 * Sets the value of the subArticleInfoUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubArticleInfoUrlText(String value) {
		this.subArticleInfoUrlText = value;
	}

	/**
	 * Gets the value of the subBuyerArticleIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubBuyerArticleIdentifier() {
		return subBuyerArticleIdentifier;
	}

	/**
	 * Sets the value of the subBuyerArticleIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubBuyerArticleIdentifier(String value) {
		this.subBuyerArticleIdentifier = value;
	}

	/**
	 * Gets the value of the subEanCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubEanCode() {
		return subEanCode;
	}

	/**
	 * Sets the value of the subEanCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubEanCode(String value) {
		this.subEanCode = value;
	}

	/**
	 * Gets the value of the subRowRegistrationNumberIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowRegistrationNumberIdentifier() {
		return subRowRegistrationNumberIdentifier;
	}

	/**
	 * Sets the value of the subRowRegistrationNumberIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowRegistrationNumberIdentifier(String value) {
		this.subRowRegistrationNumberIdentifier = value;
	}

	/**
	 * Gets the value of the subSerialNumberIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubSerialNumberIdentifier() {
		return subSerialNumberIdentifier;
	}

	/**
	 * Sets the value of the subSerialNumberIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubSerialNumberIdentifier(String value) {
		this.subSerialNumberIdentifier = value;
	}

	/**
	 * Gets the value of the subRowActionCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowActionCode() {
		return subRowActionCode;
	}

	/**
	 * Sets the value of the subRowActionCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowActionCode(String value) {
		this.subRowActionCode = value;
	}

	/**
	 * Gets the value of the subRowDefinitionDetails property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the subRowDefinitionDetails property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubRowDefinitionDetails().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SubInvoiceRowType.SubRowDefinitionDetails }
	 * 
	 * 
	 */
	public List<SubInvoiceRowType.SubRowDefinitionDetails> getSubRowDefinitionDetails() {
		if (subRowDefinitionDetails == null) {
			subRowDefinitionDetails = new ArrayList<SubInvoiceRowType.SubRowDefinitionDetails>();
		}
		return this.subRowDefinitionDetails;
	}

	/**
	 * Gets the value of the subOfferedQuantity property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the subOfferedQuantity property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubOfferedQuantity().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link QuantityType014 }
	 * 
	 * 
	 */
	public List<QuantityType014> getSubOfferedQuantity() {
		if (subOfferedQuantity == null) {
			subOfferedQuantity = new ArrayList<QuantityType014>();
		}
		return this.subOfferedQuantity;
	}

	/**
	 * Gets the value of the subDeliveredQuantity property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the subDeliveredQuantity property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubDeliveredQuantity().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link QuantityType014 }
	 * 
	 * 
	 */
	public List<QuantityType014> getSubDeliveredQuantity() {
		if (subDeliveredQuantity == null) {
			subDeliveredQuantity = new ArrayList<QuantityType014>();
		}
		return this.subDeliveredQuantity;
	}

	/**
	 * Gets the value of the subOrderedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getSubOrderedQuantity() {
		return subOrderedQuantity;
	}

	/**
	 * Sets the value of the subOrderedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setSubOrderedQuantity(QuantityType014 value) {
		this.subOrderedQuantity = value;
	}

	/**
	 * Gets the value of the subConfirmedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getSubConfirmedQuantity() {
		return subConfirmedQuantity;
	}

	/**
	 * Sets the value of the subConfirmedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setSubConfirmedQuantity(QuantityType014 value) {
		this.subConfirmedQuantity = value;
	}

	/**
	 * Gets the value of the subPostDeliveredQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getSubPostDeliveredQuantity() {
		return subPostDeliveredQuantity;
	}

	/**
	 * Sets the value of the subPostDeliveredQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setSubPostDeliveredQuantity(QuantityType014 value) {
		this.subPostDeliveredQuantity = value;
	}

	/**
	 * Gets the value of the subInvoicedQuantity property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the subInvoicedQuantity property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubInvoicedQuantity().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link QuantityType014 }
	 * 
	 * 
	 */
	public List<QuantityType014> getSubInvoicedQuantity() {
		if (subInvoicedQuantity == null) {
			subInvoicedQuantity = new ArrayList<QuantityType014>();
		}
		return this.subInvoicedQuantity;
	}

	/**
	 * Gets the value of the subCreditRequestedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getSubCreditRequestedQuantity() {
		return subCreditRequestedQuantity;
	}

	/**
	 * Sets the value of the subCreditRequestedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setSubCreditRequestedQuantity(QuantityType014 value) {
		this.subCreditRequestedQuantity = value;
	}

	/**
	 * Gets the value of the subReturnedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getSubReturnedQuantity() {
		return subReturnedQuantity;
	}

	/**
	 * Sets the value of the subReturnedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setSubReturnedQuantity(QuantityType014 value) {
		this.subReturnedQuantity = value;
	}

	/**
	 * Gets the value of the subStartDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getSubStartDate() {
		return subStartDate;
	}

	/**
	 * Sets the value of the subStartDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setSubStartDate(Date value) {
		this.subStartDate = value;
	}

	/**
	 * Gets the value of the subEndDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getSubEndDate() {
		return subEndDate;
	}

	/**
	 * Sets the value of the subEndDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setSubEndDate(Date value) {
		this.subEndDate = value;
	}

	/**
	 * Gets the value of the subUnitPriceAmount property.
	 * 
	 * @return possible object is {@link UnitAmount }
	 * 
	 */
	public UnitAmount getSubUnitPriceAmount() {
		return subUnitPriceAmount;
	}

	/**
	 * Sets the value of the subUnitPriceAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link UnitAmount }
	 * 
	 */
	public void setSubUnitPriceAmount(UnitAmount value) {
		this.subUnitPriceAmount = value;
	}

	/**
	 * Gets the value of the subUnitPriceVatIncludedAmount property.
	 * 
	 * @return possible object is {@link UnitAmount }
	 * 
	 */
	public UnitAmount getSubUnitPriceVatIncludedAmount() {
		return subUnitPriceVatIncludedAmount;
	}

	/**
	 * Sets the value of the subUnitPriceVatIncludedAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link UnitAmount }
	 * 
	 */
	public void setSubUnitPriceVatIncludedAmount(UnitAmount value) {
		this.subUnitPriceVatIncludedAmount = value;
	}

	/**
	 * Gets the value of the subUnitPriceBaseQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getSubUnitPriceBaseQuantity() {
		return subUnitPriceBaseQuantity;
	}

	/**
	 * Sets the value of the subUnitPriceBaseQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setSubUnitPriceBaseQuantity(QuantityType014 value) {
		this.subUnitPriceBaseQuantity = value;
	}

	/**
	 * Gets the value of the subRowIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowIdentifier() {
		return subRowIdentifier;
	}

	/**
	 * Sets the value of the subRowIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowIdentifier(String value) {
		this.subRowIdentifier = value;
	}

	/**
	 * Gets the value of the subRowIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowIdentifierUrlText() {
		return subRowIdentifierUrlText;
	}

	/**
	 * Sets the value of the subRowIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowIdentifierUrlText(String value) {
		this.subRowIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the subRowIdentifierDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getSubRowIdentifierDate() {
		return subRowIdentifierDate;
	}

	/**
	 * Sets the value of the subRowIdentifierDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setSubRowIdentifierDate(Date value) {
		this.subRowIdentifierDate = value;
	}

	/**
	 * Gets the value of the subRowOrdererName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowOrdererName() {
		return subRowOrdererName;
	}

	/**
	 * Sets the value of the subRowOrdererName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowOrdererName(String value) {
		this.subRowOrdererName = value;
	}

	/**
	 * Gets the value of the subRowSalesPersonName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowSalesPersonName() {
		return subRowSalesPersonName;
	}

	/**
	 * Sets the value of the subRowSalesPersonName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowSalesPersonName(String value) {
		this.subRowSalesPersonName = value;
	}

	/**
	 * Gets the value of the subRowOrderConfirmationIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowOrderConfirmationIdentifier() {
		return subRowOrderConfirmationIdentifier;
	}

	/**
	 * Sets the value of the subRowOrderConfirmationIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowOrderConfirmationIdentifier(String value) {
		this.subRowOrderConfirmationIdentifier = value;
	}

	/**
	 * Gets the value of the subRowOrderConfirmationDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getSubRowOrderConfirmationDate() {
		return subRowOrderConfirmationDate;
	}

	/**
	 * Sets the value of the subRowOrderConfirmationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setSubRowOrderConfirmationDate(Date value) {
		this.subRowOrderConfirmationDate = value;
	}

	/**
	 * Gets the value of the subOriginalInvoiceNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubOriginalInvoiceNumber() {
		return subOriginalInvoiceNumber;
	}

	/**
	 * Sets the value of the subOriginalInvoiceNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubOriginalInvoiceNumber(String value) {
		this.subOriginalInvoiceNumber = value;
	}

	/**
	 * Gets the value of the subRowDeliveryIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowDeliveryIdentifier() {
		return subRowDeliveryIdentifier;
	}

	/**
	 * Sets the value of the subRowDeliveryIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowDeliveryIdentifier(String value) {
		this.subRowDeliveryIdentifier = value;
	}

	/**
	 * Gets the value of the subRowDeliveryIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowDeliveryIdentifierUrlText() {
		return subRowDeliveryIdentifierUrlText;
	}

	/**
	 * Sets the value of the subRowDeliveryIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowDeliveryIdentifierUrlText(String value) {
		this.subRowDeliveryIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the subRowDeliveryDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getSubRowDeliveryDate() {
		return subRowDeliveryDate;
	}

	/**
	 * Sets the value of the subRowDeliveryDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setSubRowDeliveryDate(Date value) {
		this.subRowDeliveryDate = value;
	}

	/**
	 * Gets the value of the subRowQuotationIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowQuotationIdentifier() {
		return subRowQuotationIdentifier;
	}

	/**
	 * Sets the value of the subRowQuotationIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowQuotationIdentifier(String value) {
		this.subRowQuotationIdentifier = value;
	}

	/**
	 * Gets the value of the subRowQuotationIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowQuotationIdentifierUrlText() {
		return subRowQuotationIdentifierUrlText;
	}

	/**
	 * Sets the value of the subRowQuotationIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowQuotationIdentifierUrlText(String value) {
		this.subRowQuotationIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the subRowAgreementIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowAgreementIdentifier() {
		return subRowAgreementIdentifier;
	}

	/**
	 * Sets the value of the subRowAgreementIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowAgreementIdentifier(String value) {
		this.subRowAgreementIdentifier = value;
	}

	/**
	 * Gets the value of the subRowAgreementIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowAgreementIdentifierUrlText() {
		return subRowAgreementIdentifierUrlText;
	}

	/**
	 * Sets the value of the subRowAgreementIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowAgreementIdentifierUrlText(String value) {
		this.subRowAgreementIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the subRowRequestOfQuotationIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowRequestOfQuotationIdentifier() {
		return subRowRequestOfQuotationIdentifier;
	}

	/**
	 * Sets the value of the subRowRequestOfQuotationIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowRequestOfQuotationIdentifier(String value) {
		this.subRowRequestOfQuotationIdentifier = value;
	}

	/**
	 * Gets the value of the subRowRequestOfQuotationIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowRequestOfQuotationIdentifierUrlText() {
		return subRowRequestOfQuotationIdentifierUrlText;
	}

	/**
	 * Sets the value of the subRowRequestOfQuotationIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowRequestOfQuotationIdentifierUrlText(String value) {
		this.subRowRequestOfQuotationIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the subRowPriceListIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowPriceListIdentifier() {
		return subRowPriceListIdentifier;
	}

	/**
	 * Sets the value of the subRowPriceListIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowPriceListIdentifier(String value) {
		this.subRowPriceListIdentifier = value;
	}

	/**
	 * Gets the value of the subRowPriceListIdentifierUrlText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowPriceListIdentifierUrlText() {
		return subRowPriceListIdentifierUrlText;
	}

	/**
	 * Sets the value of the subRowPriceListIdentifierUrlText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowPriceListIdentifierUrlText(String value) {
		this.subRowPriceListIdentifierUrlText = value;
	}

	/**
	 * Gets the value of the subRowProjectReferenceIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowProjectReferenceIdentifier() {
		return subRowProjectReferenceIdentifier;
	}

	/**
	 * Sets the value of the subRowProjectReferenceIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowProjectReferenceIdentifier(String value) {
		this.subRowProjectReferenceIdentifier = value;
	}

	/**
	 * Gets the value of the subRowOverDuePaymentDetails property.
	 * 
	 * @return possible object is
	 *         {@link SubInvoiceRowType.SubRowOverDuePaymentDetails }
	 * 
	 */
	public SubInvoiceRowType.SubRowOverDuePaymentDetails getSubRowOverDuePaymentDetails() {
		return subRowOverDuePaymentDetails;
	}

	/**
	 * Sets the value of the subRowOverDuePaymentDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link SubInvoiceRowType.SubRowOverDuePaymentDetails }
	 * 
	 */
	public void setSubRowOverDuePaymentDetails(
			SubInvoiceRowType.SubRowOverDuePaymentDetails value) {
		this.subRowOverDuePaymentDetails = value;
	}

	/**
	 * Gets the value of the subRowAnyPartyDetails property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the subRowAnyPartyDetails property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubRowAnyPartyDetails().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SubInvoiceRowType.SubRowAnyPartyDetails }
	 * 
	 * 
	 */
	public List<SubInvoiceRowType.SubRowAnyPartyDetails> getSubRowAnyPartyDetails() {
		if (subRowAnyPartyDetails == null) {
			subRowAnyPartyDetails = new ArrayList<SubInvoiceRowType.SubRowAnyPartyDetails>();
		}
		return this.subRowAnyPartyDetails;
	}

	/**
	 * Gets the value of the subRowDeliveryDetails property.
	 * 
	 * @return possible object is {@link SubRowDeliveryDetailsType }
	 * 
	 */
	public SubRowDeliveryDetailsType getSubRowDeliveryDetails() {
		return subRowDeliveryDetails;
	}

	/**
	 * Sets the value of the subRowDeliveryDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link SubRowDeliveryDetailsType }
	 * 
	 */
	public void setSubRowDeliveryDetails(SubRowDeliveryDetailsType value) {
		this.subRowDeliveryDetails = value;
	}

	/**
	 * Gets the value of the subRowShortProposedAccountIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowShortProposedAccountIdentifier() {
		return subRowShortProposedAccountIdentifier;
	}

	/**
	 * Sets the value of the subRowShortProposedAccountIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowShortProposedAccountIdentifier(String value) {
		this.subRowShortProposedAccountIdentifier = value;
	}

	/**
	 * Gets the value of the subRowNormalProposedAccountIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowNormalProposedAccountIdentifier() {
		return subRowNormalProposedAccountIdentifier;
	}

	/**
	 * Sets the value of the subRowNormalProposedAccountIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowNormalProposedAccountIdentifier(String value) {
		this.subRowNormalProposedAccountIdentifier = value;
	}

	/**
	 * Gets the value of the subRowProposedAccountText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowProposedAccountText() {
		return subRowProposedAccountText;
	}

	/**
	 * Sets the value of the subRowProposedAccountText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowProposedAccountText(String value) {
		this.subRowProposedAccountText = value;
	}

	/**
	 * Gets the value of the subRowAccountDimensionText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowAccountDimensionText() {
		return subRowAccountDimensionText;
	}

	/**
	 * Sets the value of the subRowAccountDimensionText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowAccountDimensionText(String value) {
		this.subRowAccountDimensionText = value;
	}

	/**
	 * Gets the value of the subRowSellerAccountText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowSellerAccountText() {
		return subRowSellerAccountText;
	}

	/**
	 * Sets the value of the subRowSellerAccountText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowSellerAccountText(String value) {
		this.subRowSellerAccountText = value;
	}

	/**
	 * Gets the value of the subRowFreeText property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the subRowFreeText property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubRowFreeText().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getSubRowFreeText() {
		if (subRowFreeText == null) {
			subRowFreeText = new ArrayList<String>();
		}
		return this.subRowFreeText;
	}

	/**
	 * Gets the value of the subRowUsedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getSubRowUsedQuantity() {
		return subRowUsedQuantity;
	}

	/**
	 * Sets the value of the subRowUsedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setSubRowUsedQuantity(QuantityType014 value) {
		this.subRowUsedQuantity = value;
	}

	/**
	 * Gets the value of the subRowPreviousMeterReadingDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getSubRowPreviousMeterReadingDate() {
		return subRowPreviousMeterReadingDate;
	}

	/**
	 * Sets the value of the subRowPreviousMeterReadingDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setSubRowPreviousMeterReadingDate(Date value) {
		this.subRowPreviousMeterReadingDate = value;
	}

	/**
	 * Gets the value of the subRowLatestMeterReadingDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getSubRowLatestMeterReadingDate() {
		return subRowLatestMeterReadingDate;
	}

	/**
	 * Sets the value of the subRowLatestMeterReadingDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setSubRowLatestMeterReadingDate(Date value) {
		this.subRowLatestMeterReadingDate = value;
	}

	/**
	 * Gets the value of the subRowCalculatedQuantity property.
	 * 
	 * @return possible object is {@link QuantityType014 }
	 * 
	 */
	public QuantityType014 getSubRowCalculatedQuantity() {
		return subRowCalculatedQuantity;
	}

	/**
	 * Sets the value of the subRowCalculatedQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link QuantityType014 }
	 * 
	 */
	public void setSubRowCalculatedQuantity(QuantityType014 value) {
		this.subRowCalculatedQuantity = value;
	}

	/**
	 * Gets the value of the subRowAveragePriceAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getSubRowAveragePriceAmount() {
		return subRowAveragePriceAmount;
	}

	/**
	 * Sets the value of the subRowAveragePriceAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setSubRowAveragePriceAmount(Amount value) {
		this.subRowAveragePriceAmount = value;
	}

	/**
	 * Gets the value of the subRowDiscountPercent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowDiscountPercent() {
		return subRowDiscountPercent;
	}

	/**
	 * Sets the value of the subRowDiscountPercent property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowDiscountPercent(String value) {
		this.subRowDiscountPercent = value;
	}

	/**
	 * Gets the value of the subRowDiscountAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getSubRowDiscountAmount() {
		return subRowDiscountAmount;
	}

	/**
	 * Sets the value of the subRowDiscountAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setSubRowDiscountAmount(Amount value) {
		this.subRowDiscountAmount = value;
	}

	/**
	 * Gets the value of the subRowDiscountTypeCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowDiscountTypeCode() {
		return subRowDiscountTypeCode;
	}

	/**
	 * Sets the value of the subRowDiscountTypeCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowDiscountTypeCode(String value) {
		this.subRowDiscountTypeCode = value;
	}

	/**
	 * Gets the value of the subRowDiscountTypeText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowDiscountTypeText() {
		return subRowDiscountTypeText;
	}

	/**
	 * Sets the value of the subRowDiscountTypeText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowDiscountTypeText(String value) {
		this.subRowDiscountTypeText = value;
	}

	/**
	 * Gets the value of the subRowProgressiveDiscountDetails property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the subRowProgressiveDiscountDetails
	 * property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubRowProgressiveDiscountDetails().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SubInvoiceRowType.SubRowProgressiveDiscountDetails }
	 * 
	 * 
	 */
	public List<SubInvoiceRowType.SubRowProgressiveDiscountDetails> getSubRowProgressiveDiscountDetails() {
		if (subRowProgressiveDiscountDetails == null) {
			subRowProgressiveDiscountDetails = new ArrayList<SubInvoiceRowType.SubRowProgressiveDiscountDetails>();
		}
		return this.subRowProgressiveDiscountDetails;
	}

	/**
	 * Gets the value of the subRowVatRatePercent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowVatRatePercent() {
		return subRowVatRatePercent;
	}

	/**
	 * Sets the value of the subRowVatRatePercent property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowVatRatePercent(String value) {
		this.subRowVatRatePercent = value;
	}

	/**
	 * Gets the value of the subRowVatCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubRowVatCode() {
		return subRowVatCode;
	}

	/**
	 * Sets the value of the subRowVatCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubRowVatCode(String value) {
		this.subRowVatCode = value;
	}

	/**
	 * Gets the value of the subRowVatAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getSubRowVatAmount() {
		return subRowVatAmount;
	}

	/**
	 * Sets the value of the subRowVatAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setSubRowVatAmount(Amount value) {
		this.subRowVatAmount = value;
	}

	/**
	 * Gets the value of the subRowVatExcludedAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getSubRowVatExcludedAmount() {
		return subRowVatExcludedAmount;
	}

	/**
	 * Sets the value of the subRowVatExcludedAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setSubRowVatExcludedAmount(Amount value) {
		this.subRowVatExcludedAmount = value;
	}

	/**
	 * Gets the value of the subRowAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getSubRowAmount() {
		return subRowAmount;
	}

	/**
	 * Sets the value of the subRowAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setSubRowAmount(Amount value) {
		this.subRowAmount = value;
	}

	/**
	 * Gets the value of the subRowTransactionDetails property.
	 * 
	 * @return possible object is {@link TransactionDetailsType }
	 * 
	 */
	public TransactionDetailsType getSubRowTransactionDetails() {
		return subRowTransactionDetails;
	}

	/**
	 * Sets the value of the subRowTransactionDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link TransactionDetailsType }
	 * 
	 */
	public void setSubRowTransactionDetails(TransactionDetailsType value) {
		this.subRowTransactionDetails = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="SubRowAnyPartyText" type="{}anypartytexttype0_35"/>
	 *         &lt;element name="SubRowAnyPartyIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="SubRowAnyPartyOrganisationName" type="{}genericStringType2_35" maxOccurs="2"/>
	 *         &lt;element name="SubRowAnyPartyOrganisationDepartment" type="{}genericStringType0_35" maxOccurs="2" minOccurs="0"/>
	 *         &lt;element name="SubRowAnyPartyOrganisationTaxCode" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="SubRowAnyPartyPostalAddressDetails" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="SubRowAnyPartyStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
	 *                   &lt;element name="SubRowAnyPartyTownName" type="{}genericStringType2_35"/>
	 *                   &lt;element name="SubRowAnyPartyPostCodeIdentifier" type="{}genericStringType2_35"/>
	 *                   &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
	 *                   &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
	 *                   &lt;element name="SubRowAnyPartyPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="SubRowAnyPartyOrganisationUnitNumber" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="SubRowAnyPartySiteCode" type="{}genericStringType0_35" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "subRowAnyPartyText",
			"subRowAnyPartyIdentifier", "subRowAnyPartyOrganisationName",
			"subRowAnyPartyOrganisationDepartment",
			"subRowAnyPartyOrganisationTaxCode",
			"subRowAnyPartyPostalAddressDetails",
			"subRowAnyPartyOrganisationUnitNumber", "subRowAnyPartySiteCode" })
	public static class SubRowAnyPartyDetails {

		@XmlElement(name = "SubRowAnyPartyText", required = true)
		protected Anypartytexttype035 subRowAnyPartyText;
		@XmlElement(name = "SubRowAnyPartyIdentifier")
		protected String subRowAnyPartyIdentifier;
		@XmlElement(name = "SubRowAnyPartyOrganisationName", required = true)
		protected List<String> subRowAnyPartyOrganisationName;
		@XmlElement(name = "SubRowAnyPartyOrganisationDepartment")
		protected List<String> subRowAnyPartyOrganisationDepartment;
		@XmlElement(name = "SubRowAnyPartyOrganisationTaxCode")
		protected String subRowAnyPartyOrganisationTaxCode;
		@XmlElement(name = "SubRowAnyPartyPostalAddressDetails")
		protected SubInvoiceRowType.SubRowAnyPartyDetails.SubRowAnyPartyPostalAddressDetails subRowAnyPartyPostalAddressDetails;
		@XmlElement(name = "SubRowAnyPartyOrganisationUnitNumber")
		protected String subRowAnyPartyOrganisationUnitNumber;
		@XmlElement(name = "SubRowAnyPartySiteCode")
		protected String subRowAnyPartySiteCode;

		/**
		 * Gets the value of the subRowAnyPartyText property.
		 * 
		 * @return possible object is {@link Anypartytexttype035 }
		 * 
		 */
		public Anypartytexttype035 getSubRowAnyPartyText() {
			return subRowAnyPartyText;
		}

		/**
		 * Sets the value of the subRowAnyPartyText property.
		 * 
		 * @param value
		 *            allowed object is {@link Anypartytexttype035 }
		 * 
		 */
		public void setSubRowAnyPartyText(Anypartytexttype035 value) {
			this.subRowAnyPartyText = value;
		}

		/**
		 * Gets the value of the subRowAnyPartyIdentifier property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowAnyPartyIdentifier() {
			return subRowAnyPartyIdentifier;
		}

		/**
		 * Sets the value of the subRowAnyPartyIdentifier property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowAnyPartyIdentifier(String value) {
			this.subRowAnyPartyIdentifier = value;
		}

		/**
		 * Gets the value of the subRowAnyPartyOrganisationName property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the subRowAnyPartyOrganisationName
		 * property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getSubRowAnyPartyOrganisationName().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getSubRowAnyPartyOrganisationName() {
			if (subRowAnyPartyOrganisationName == null) {
				subRowAnyPartyOrganisationName = new ArrayList<String>();
			}
			return this.subRowAnyPartyOrganisationName;
		}

		/**
		 * Gets the value of the subRowAnyPartyOrganisationDepartment property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the subRowAnyPartyOrganisationDepartment
		 * property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getSubRowAnyPartyOrganisationDepartment().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getSubRowAnyPartyOrganisationDepartment() {
			if (subRowAnyPartyOrganisationDepartment == null) {
				subRowAnyPartyOrganisationDepartment = new ArrayList<String>();
			}
			return this.subRowAnyPartyOrganisationDepartment;
		}

		/**
		 * Gets the value of the subRowAnyPartyOrganisationTaxCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowAnyPartyOrganisationTaxCode() {
			return subRowAnyPartyOrganisationTaxCode;
		}

		/**
		 * Sets the value of the subRowAnyPartyOrganisationTaxCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowAnyPartyOrganisationTaxCode(String value) {
			this.subRowAnyPartyOrganisationTaxCode = value;
		}

		/**
		 * Gets the value of the subRowAnyPartyPostalAddressDetails property.
		 * 
		 * @return possible object is
		 *         {@link SubInvoiceRowType.SubRowAnyPartyDetails.SubRowAnyPartyPostalAddressDetails }
		 * 
		 */
		public SubInvoiceRowType.SubRowAnyPartyDetails.SubRowAnyPartyPostalAddressDetails getSubRowAnyPartyPostalAddressDetails() {
			return subRowAnyPartyPostalAddressDetails;
		}

		/**
		 * Sets the value of the subRowAnyPartyPostalAddressDetails property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link SubInvoiceRowType.SubRowAnyPartyDetails.SubRowAnyPartyPostalAddressDetails }
		 * 
		 */
		public void setSubRowAnyPartyPostalAddressDetails(
				SubInvoiceRowType.SubRowAnyPartyDetails.SubRowAnyPartyPostalAddressDetails value) {
			this.subRowAnyPartyPostalAddressDetails = value;
		}

		/**
		 * Gets the value of the subRowAnyPartyOrganisationUnitNumber property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowAnyPartyOrganisationUnitNumber() {
			return subRowAnyPartyOrganisationUnitNumber;
		}

		/**
		 * Sets the value of the subRowAnyPartyOrganisationUnitNumber property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowAnyPartyOrganisationUnitNumber(String value) {
			this.subRowAnyPartyOrganisationUnitNumber = value;
		}

		/**
		 * Gets the value of the subRowAnyPartySiteCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowAnyPartySiteCode() {
			return subRowAnyPartySiteCode;
		}

		/**
		 * Sets the value of the subRowAnyPartySiteCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowAnyPartySiteCode(String value) {
			this.subRowAnyPartySiteCode = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="SubRowAnyPartyStreetName" type="{}genericStringType2_35" maxOccurs="3"/>
		 *         &lt;element name="SubRowAnyPartyTownName" type="{}genericStringType2_35"/>
		 *         &lt;element name="SubRowAnyPartyPostCodeIdentifier" type="{}genericStringType2_35"/>
		 *         &lt;element name="CountryCode" type="{}CountryCodeType" minOccurs="0"/>
		 *         &lt;element name="CountryName" type="{}genericStringType0_35" minOccurs="0"/>
		 *         &lt;element name="SubRowAnyPartyPostOfficeBoxIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "subRowAnyPartyStreetName",
				"subRowAnyPartyTownName", "subRowAnyPartyPostCodeIdentifier",
				"countryCode", "countryName",
				"subRowAnyPartyPostOfficeBoxIdentifier" })
		public static class SubRowAnyPartyPostalAddressDetails {

			@XmlElement(name = "SubRowAnyPartyStreetName", required = true)
			protected List<String> subRowAnyPartyStreetName;
			@XmlElement(name = "SubRowAnyPartyTownName", required = true)
			protected String subRowAnyPartyTownName;
			@XmlElement(name = "SubRowAnyPartyPostCodeIdentifier", required = true)
			protected String subRowAnyPartyPostCodeIdentifier;
			@XmlElement(name = "CountryCode")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String countryCode;
			@XmlElement(name = "CountryName")
			protected String countryName;
			@XmlElement(name = "SubRowAnyPartyPostOfficeBoxIdentifier")
			protected String subRowAnyPartyPostOfficeBoxIdentifier;

			/**
			 * Gets the value of the subRowAnyPartyStreetName property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the subRowAnyPartyStreetName
			 * property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getSubRowAnyPartyStreetName().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getSubRowAnyPartyStreetName() {
				if (subRowAnyPartyStreetName == null) {
					subRowAnyPartyStreetName = new ArrayList<String>();
				}
				return this.subRowAnyPartyStreetName;
			}

			/**
			 * Gets the value of the subRowAnyPartyTownName property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSubRowAnyPartyTownName() {
				return subRowAnyPartyTownName;
			}

			/**
			 * Sets the value of the subRowAnyPartyTownName property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSubRowAnyPartyTownName(String value) {
				this.subRowAnyPartyTownName = value;
			}

			/**
			 * Gets the value of the subRowAnyPartyPostCodeIdentifier property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSubRowAnyPartyPostCodeIdentifier() {
				return subRowAnyPartyPostCodeIdentifier;
			}

			/**
			 * Sets the value of the subRowAnyPartyPostCodeIdentifier property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSubRowAnyPartyPostCodeIdentifier(String value) {
				this.subRowAnyPartyPostCodeIdentifier = value;
			}

			/**
			 * Gets the value of the countryCode property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCountryCode() {
				return countryCode;
			}

			/**
			 * Sets the value of the countryCode property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCountryCode(String value) {
				this.countryCode = value;
			}

			/**
			 * Gets the value of the countryName property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCountryName() {
				return countryName;
			}

			/**
			 * Sets the value of the countryName property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCountryName(String value) {
				this.countryName = value;
			}

			/**
			 * Gets the value of the subRowAnyPartyPostOfficeBoxIdentifier
			 * property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSubRowAnyPartyPostOfficeBoxIdentifier() {
				return subRowAnyPartyPostOfficeBoxIdentifier;
			}

			/**
			 * Sets the value of the subRowAnyPartyPostOfficeBoxIdentifier
			 * property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSubRowAnyPartyPostOfficeBoxIdentifier(String value) {
				this.subRowAnyPartyPostOfficeBoxIdentifier = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="SubRowDefinitionHeaderText">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;>genericStringType0_70">
	 *                 &lt;attribute name="DefinitionCode" type="{}genericTokenType1_20" />
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="SubRowDefinitionValue" type="{}QuantityType0_70" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "subRowDefinitionHeaderText",
			"subRowDefinitionValue" })
	public static class SubRowDefinitionDetails {

		@XmlElement(name = "SubRowDefinitionHeaderText", required = true)
		protected SubInvoiceRowType.SubRowDefinitionDetails.SubRowDefinitionHeaderText subRowDefinitionHeaderText;
		@XmlElement(name = "SubRowDefinitionValue")
		protected QuantityType070 subRowDefinitionValue;

		/**
		 * Gets the value of the subRowDefinitionHeaderText property.
		 * 
		 * @return possible object is
		 *         {@link SubInvoiceRowType.SubRowDefinitionDetails.SubRowDefinitionHeaderText }
		 * 
		 */
		public SubInvoiceRowType.SubRowDefinitionDetails.SubRowDefinitionHeaderText getSubRowDefinitionHeaderText() {
			return subRowDefinitionHeaderText;
		}

		/**
		 * Sets the value of the subRowDefinitionHeaderText property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link SubInvoiceRowType.SubRowDefinitionDetails.SubRowDefinitionHeaderText }
		 * 
		 */
		public void setSubRowDefinitionHeaderText(
				SubInvoiceRowType.SubRowDefinitionDetails.SubRowDefinitionHeaderText value) {
			this.subRowDefinitionHeaderText = value;
		}

		/**
		 * Gets the value of the subRowDefinitionValue property.
		 * 
		 * @return possible object is {@link QuantityType070 }
		 * 
		 */
		public QuantityType070 getSubRowDefinitionValue() {
			return subRowDefinitionValue;
		}

		/**
		 * Sets the value of the subRowDefinitionValue property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType070 }
		 * 
		 */
		public void setSubRowDefinitionValue(QuantityType070 value) {
			this.subRowDefinitionValue = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;>genericStringType0_70">
		 *       &lt;attribute name="DefinitionCode" type="{}genericTokenType1_20" />
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "value" })
		public static class SubRowDefinitionHeaderText {

			@XmlValue
			protected String value;
			@XmlAttribute(name = "DefinitionCode")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			protected String definitionCode;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the definitionCode property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDefinitionCode() {
				return definitionCode;
			}

			/**
			 * Sets the value of the definitionCode property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDefinitionCode(String value) {
				this.definitionCode = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="SubRowOriginalInvoiceIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="SubRowOriginalInvoiceDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="SubRowOriginalDueDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="SubRowOriginalInvoiceTotalAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="SubRowOriginalEpiRemittanceInfoIdentifier" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="SubRowPaidVatExcludedAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="SubRowPaidVatIncludedAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="SubRowPaidDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="SubRowUnPaidVatExcludedAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="SubRowUnPaidVatIncludedAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="SubRowCollectionDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="SubRowCollectionQuantity" type="{}QuantityType0_14" minOccurs="0"/>
	 *         &lt;element name="SubRowCollectionChargeAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="SubRowInterestRate" type="{}percentage" minOccurs="0"/>
	 *         &lt;element name="SubRowInterestStartDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="SubRowInterestEndDate" type="{}date" minOccurs="0"/>
	 *         &lt;element name="SubRowInterestPeriodText" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="SubRowInterestDateNumber" type="{}genericNMtokenType0_14" minOccurs="0"/>
	 *         &lt;element name="SubRowInterestChargeAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="SubRowInterestChargeVatAmount" type="{}amount" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "subRowOriginalInvoiceIdentifier",
			"subRowOriginalInvoiceDate", "subRowOriginalDueDate",
			"subRowOriginalInvoiceTotalAmount",
			"subRowOriginalEpiRemittanceInfoIdentifier",
			"subRowPaidVatExcludedAmount", "subRowPaidVatIncludedAmount",
			"subRowPaidDate", "subRowUnPaidVatExcludedAmount",
			"subRowUnPaidVatIncludedAmount", "subRowCollectionDate",
			"subRowCollectionQuantity", "subRowCollectionChargeAmount",
			"subRowInterestRate", "subRowInterestStartDate",
			"subRowInterestEndDate", "subRowInterestPeriodText",
			"subRowInterestDateNumber", "subRowInterestChargeAmount",
			"subRowInterestChargeVatAmount" })
	public static class SubRowOverDuePaymentDetails {

		@XmlElement(name = "SubRowOriginalInvoiceIdentifier")
		protected String subRowOriginalInvoiceIdentifier;
		@XmlElement(name = "SubRowOriginalInvoiceDate")
		protected Date subRowOriginalInvoiceDate;
		@XmlElement(name = "SubRowOriginalDueDate")
		protected Date subRowOriginalDueDate;
		@XmlElement(name = "SubRowOriginalInvoiceTotalAmount")
		protected Amount subRowOriginalInvoiceTotalAmount;
		@XmlElement(name = "SubRowOriginalEpiRemittanceInfoIdentifier")
		protected String subRowOriginalEpiRemittanceInfoIdentifier;
		@XmlElement(name = "SubRowPaidVatExcludedAmount")
		protected Amount subRowPaidVatExcludedAmount;
		@XmlElement(name = "SubRowPaidVatIncludedAmount")
		protected Amount subRowPaidVatIncludedAmount;
		@XmlElement(name = "SubRowPaidDate")
		protected Date subRowPaidDate;
		@XmlElement(name = "SubRowUnPaidVatExcludedAmount")
		protected Amount subRowUnPaidVatExcludedAmount;
		@XmlElement(name = "SubRowUnPaidVatIncludedAmount")
		protected Amount subRowUnPaidVatIncludedAmount;
		@XmlElement(name = "SubRowCollectionDate")
		protected Date subRowCollectionDate;
		@XmlElement(name = "SubRowCollectionQuantity")
		protected QuantityType014 subRowCollectionQuantity;
		@XmlElement(name = "SubRowCollectionChargeAmount")
		protected Amount subRowCollectionChargeAmount;
		@XmlElement(name = "SubRowInterestRate")
		protected String subRowInterestRate;
		@XmlElement(name = "SubRowInterestStartDate")
		protected Date subRowInterestStartDate;
		@XmlElement(name = "SubRowInterestEndDate")
		protected Date subRowInterestEndDate;
		@XmlElement(name = "SubRowInterestPeriodText")
		protected String subRowInterestPeriodText;
		@XmlElement(name = "SubRowInterestDateNumber")
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		protected String subRowInterestDateNumber;
		@XmlElement(name = "SubRowInterestChargeAmount")
		protected Amount subRowInterestChargeAmount;
		@XmlElement(name = "SubRowInterestChargeVatAmount")
		protected Amount subRowInterestChargeVatAmount;

		/**
		 * Gets the value of the subRowOriginalInvoiceIdentifier property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowOriginalInvoiceIdentifier() {
			return subRowOriginalInvoiceIdentifier;
		}

		/**
		 * Sets the value of the subRowOriginalInvoiceIdentifier property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowOriginalInvoiceIdentifier(String value) {
			this.subRowOriginalInvoiceIdentifier = value;
		}

		/**
		 * Gets the value of the subRowOriginalInvoiceDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getSubRowOriginalInvoiceDate() {
			return subRowOriginalInvoiceDate;
		}

		/**
		 * Sets the value of the subRowOriginalInvoiceDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setSubRowOriginalInvoiceDate(Date value) {
			this.subRowOriginalInvoiceDate = value;
		}

		/**
		 * Gets the value of the subRowOriginalDueDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getSubRowOriginalDueDate() {
			return subRowOriginalDueDate;
		}

		/**
		 * Sets the value of the subRowOriginalDueDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setSubRowOriginalDueDate(Date value) {
			this.subRowOriginalDueDate = value;
		}

		/**
		 * Gets the value of the subRowOriginalInvoiceTotalAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getSubRowOriginalInvoiceTotalAmount() {
			return subRowOriginalInvoiceTotalAmount;
		}

		/**
		 * Sets the value of the subRowOriginalInvoiceTotalAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setSubRowOriginalInvoiceTotalAmount(Amount value) {
			this.subRowOriginalInvoiceTotalAmount = value;
		}

		/**
		 * Gets the value of the subRowOriginalEpiRemittanceInfoIdentifier
		 * property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowOriginalEpiRemittanceInfoIdentifier() {
			return subRowOriginalEpiRemittanceInfoIdentifier;
		}

		/**
		 * Sets the value of the subRowOriginalEpiRemittanceInfoIdentifier
		 * property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowOriginalEpiRemittanceInfoIdentifier(String value) {
			this.subRowOriginalEpiRemittanceInfoIdentifier = value;
		}

		/**
		 * Gets the value of the subRowPaidVatExcludedAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getSubRowPaidVatExcludedAmount() {
			return subRowPaidVatExcludedAmount;
		}

		/**
		 * Sets the value of the subRowPaidVatExcludedAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setSubRowPaidVatExcludedAmount(Amount value) {
			this.subRowPaidVatExcludedAmount = value;
		}

		/**
		 * Gets the value of the subRowPaidVatIncludedAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getSubRowPaidVatIncludedAmount() {
			return subRowPaidVatIncludedAmount;
		}

		/**
		 * Sets the value of the subRowPaidVatIncludedAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setSubRowPaidVatIncludedAmount(Amount value) {
			this.subRowPaidVatIncludedAmount = value;
		}

		/**
		 * Gets the value of the subRowPaidDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getSubRowPaidDate() {
			return subRowPaidDate;
		}

		/**
		 * Sets the value of the subRowPaidDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setSubRowPaidDate(Date value) {
			this.subRowPaidDate = value;
		}

		/**
		 * Gets the value of the subRowUnPaidVatExcludedAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getSubRowUnPaidVatExcludedAmount() {
			return subRowUnPaidVatExcludedAmount;
		}

		/**
		 * Sets the value of the subRowUnPaidVatExcludedAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setSubRowUnPaidVatExcludedAmount(Amount value) {
			this.subRowUnPaidVatExcludedAmount = value;
		}

		/**
		 * Gets the value of the subRowUnPaidVatIncludedAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getSubRowUnPaidVatIncludedAmount() {
			return subRowUnPaidVatIncludedAmount;
		}

		/**
		 * Sets the value of the subRowUnPaidVatIncludedAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setSubRowUnPaidVatIncludedAmount(Amount value) {
			this.subRowUnPaidVatIncludedAmount = value;
		}

		/**
		 * Gets the value of the subRowCollectionDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getSubRowCollectionDate() {
			return subRowCollectionDate;
		}

		/**
		 * Sets the value of the subRowCollectionDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setSubRowCollectionDate(Date value) {
			this.subRowCollectionDate = value;
		}

		/**
		 * Gets the value of the subRowCollectionQuantity property.
		 * 
		 * @return possible object is {@link QuantityType014 }
		 * 
		 */
		public QuantityType014 getSubRowCollectionQuantity() {
			return subRowCollectionQuantity;
		}

		/**
		 * Sets the value of the subRowCollectionQuantity property.
		 * 
		 * @param value
		 *            allowed object is {@link QuantityType014 }
		 * 
		 */
		public void setSubRowCollectionQuantity(QuantityType014 value) {
			this.subRowCollectionQuantity = value;
		}

		/**
		 * Gets the value of the subRowCollectionChargeAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getSubRowCollectionChargeAmount() {
			return subRowCollectionChargeAmount;
		}

		/**
		 * Sets the value of the subRowCollectionChargeAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setSubRowCollectionChargeAmount(Amount value) {
			this.subRowCollectionChargeAmount = value;
		}

		/**
		 * Gets the value of the subRowInterestRate property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowInterestRate() {
			return subRowInterestRate;
		}

		/**
		 * Sets the value of the subRowInterestRate property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowInterestRate(String value) {
			this.subRowInterestRate = value;
		}

		/**
		 * Gets the value of the subRowInterestStartDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getSubRowInterestStartDate() {
			return subRowInterestStartDate;
		}

		/**
		 * Sets the value of the subRowInterestStartDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setSubRowInterestStartDate(Date value) {
			this.subRowInterestStartDate = value;
		}

		/**
		 * Gets the value of the subRowInterestEndDate property.
		 * 
		 * @return possible object is {@link Date }
		 * 
		 */
		public Date getSubRowInterestEndDate() {
			return subRowInterestEndDate;
		}

		/**
		 * Sets the value of the subRowInterestEndDate property.
		 * 
		 * @param value
		 *            allowed object is {@link Date }
		 * 
		 */
		public void setSubRowInterestEndDate(Date value) {
			this.subRowInterestEndDate = value;
		}

		/**
		 * Gets the value of the subRowInterestPeriodText property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowInterestPeriodText() {
			return subRowInterestPeriodText;
		}

		/**
		 * Sets the value of the subRowInterestPeriodText property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowInterestPeriodText(String value) {
			this.subRowInterestPeriodText = value;
		}

		/**
		 * Gets the value of the subRowInterestDateNumber property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowInterestDateNumber() {
			return subRowInterestDateNumber;
		}

		/**
		 * Sets the value of the subRowInterestDateNumber property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowInterestDateNumber(String value) {
			this.subRowInterestDateNumber = value;
		}

		/**
		 * Gets the value of the subRowInterestChargeAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getSubRowInterestChargeAmount() {
			return subRowInterestChargeAmount;
		}

		/**
		 * Sets the value of the subRowInterestChargeAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setSubRowInterestChargeAmount(Amount value) {
			this.subRowInterestChargeAmount = value;
		}

		/**
		 * Gets the value of the subRowInterestChargeVatAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getSubRowInterestChargeVatAmount() {
			return subRowInterestChargeVatAmount;
		}

		/**
		 * Sets the value of the subRowInterestChargeVatAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setSubRowInterestChargeVatAmount(Amount value) {
			this.subRowInterestChargeVatAmount = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="SubRowDiscountPercent" type="{}percentage" minOccurs="0"/>
	 *         &lt;element name="SubRowDiscountAmount" type="{}amount" minOccurs="0"/>
	 *         &lt;element name="SubRowDiscountTypeCode" type="{}genericStringType0_35" minOccurs="0"/>
	 *         &lt;element name="SubRowDiscountTypeText" type="{}genericStringType0_35" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "subRowDiscountPercent",
			"subRowDiscountAmount", "subRowDiscountTypeCode",
			"subRowDiscountTypeText" })
	public static class SubRowProgressiveDiscountDetails {

		@XmlElement(name = "SubRowDiscountPercent")
		protected String subRowDiscountPercent;
		@XmlElement(name = "SubRowDiscountAmount")
		protected Amount subRowDiscountAmount;
		@XmlElement(name = "SubRowDiscountTypeCode")
		protected String subRowDiscountTypeCode;
		@XmlElement(name = "SubRowDiscountTypeText")
		protected String subRowDiscountTypeText;

		/**
		 * Gets the value of the subRowDiscountPercent property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowDiscountPercent() {
			return subRowDiscountPercent;
		}

		/**
		 * Sets the value of the subRowDiscountPercent property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowDiscountPercent(String value) {
			this.subRowDiscountPercent = value;
		}

		/**
		 * Gets the value of the subRowDiscountAmount property.
		 * 
		 * @return possible object is {@link Amount }
		 * 
		 */
		public Amount getSubRowDiscountAmount() {
			return subRowDiscountAmount;
		}

		/**
		 * Sets the value of the subRowDiscountAmount property.
		 * 
		 * @param value
		 *            allowed object is {@link Amount }
		 * 
		 */
		public void setSubRowDiscountAmount(Amount value) {
			this.subRowDiscountAmount = value;
		}

		/**
		 * Gets the value of the subRowDiscountTypeCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowDiscountTypeCode() {
			return subRowDiscountTypeCode;
		}

		/**
		 * Sets the value of the subRowDiscountTypeCode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowDiscountTypeCode(String value) {
			this.subRowDiscountTypeCode = value;
		}

		/**
		 * Gets the value of the subRowDiscountTypeText property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSubRowDiscountTypeText() {
			return subRowDiscountTypeText;
		}

		/**
		 * Sets the value of the subRowDiscountTypeText property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSubRowDiscountTypeText(String value) {
			this.subRowDiscountTypeText = value;
		}

	}

}
