//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TransactionDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OtherCurrencyAmount" type="{}amount" minOccurs="0"/>
 *         &lt;element name="ExchangeRate" type="{}exchangeRate" minOccurs="0"/>
 *         &lt;element name="ExchangeDate" type="{}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionDetailsType", propOrder = { "otherCurrencyAmount",
		"exchangeRate", "exchangeDate" })
public class TransactionDetailsType {

	@XmlElement(name = "OtherCurrencyAmount")
	protected Amount otherCurrencyAmount;
	@XmlElement(name = "ExchangeRate")
	protected String exchangeRate;
	@XmlElement(name = "ExchangeDate")
	protected Date exchangeDate;

	/**
	 * Gets the value of the otherCurrencyAmount property.
	 * 
	 * @return possible object is {@link Amount }
	 * 
	 */
	public Amount getOtherCurrencyAmount() {
		return otherCurrencyAmount;
	}

	/**
	 * Sets the value of the otherCurrencyAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link Amount }
	 * 
	 */
	public void setOtherCurrencyAmount(Amount value) {
		this.otherCurrencyAmount = value;
	}

	/**
	 * Gets the value of the exchangeRate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExchangeRate() {
		return exchangeRate;
	}

	/**
	 * Sets the value of the exchangeRate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExchangeRate(String value) {
		this.exchangeRate = value;
	}

	/**
	 * Gets the value of the exchangeDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getExchangeDate() {
		return exchangeDate;
	}

	/**
	 * Sets the value of the exchangeDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setExchangeDate(Date value) {
		this.exchangeDate = value;
	}

}
