//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 10:26:42 ap. EET 
//

package com.kuroshfarsimadan.demonstration.finvoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for unitAmount complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="unitAmount">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;>unitAmountType">
 *       &lt;attribute name="AmountCurrencyIdentifier" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;length value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="UnitPriceUnitCode" type="{}genericStringType0_14" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "unitAmount", propOrder = { "value" })
public class UnitAmount {

	@XmlValue
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String value;
	@XmlAttribute(name = "AmountCurrencyIdentifier", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String amountCurrencyIdentifier;
	@XmlAttribute(name = "UnitPriceUnitCode")
	protected String unitPriceUnitCode;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the amountCurrencyIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAmountCurrencyIdentifier() {
		return amountCurrencyIdentifier;
	}

	/**
	 * Sets the value of the amountCurrencyIdentifier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAmountCurrencyIdentifier(String value) {
		this.amountCurrencyIdentifier = value;
	}

	/**
	 * Gets the value of the unitPriceUnitCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnitPriceUnitCode() {
		return unitPriceUnitCode;
	}

	/**
	 * Sets the value of the unitPriceUnitCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUnitPriceUnitCode(String value) {
		this.unitPriceUnitCode = value;
	}

}
